### PR TITLE
fix_: saving profile image changes ens display name to non-ens

### LINKED ISSUE #14048: Saving profile image changes ENS display name to non-ENS
# Bug Report

## Description

1. Restore account that uses ENS
2. Remove restored profile picture
3. Add new profile picture
4. Click on save
5. ENS name is overwritten with display name set during restore

Note: ENS display name is reapplied after restart

https://github.com/status-im/status-desktop/assets/50769329/2a25d37e-b297-404d-881a-b677924a7bfa

- Status desktop version: 2.27
- Operating System: Mac

### PR DESCRIPTION
**Pull request by kounkou**
### Description

When a user updates the preferred name, we should just ignore if the name is an ENS name, because the ENS name is set only in the ENS popup. But this also means that if a user set the profile name to an ENS name, this change will also be ignored.

### Detailed description/Analysis

I think I understand the problem. Let me try to summarize it.

Previously, we faced [issue](https://github.com/status-im/status-desktop/issues/14128) where the user could change the displayed name to `x.y.z`, and this prevented other clients from displaying messages due to the validation on the display name.

However, ENS names have the format `x.y.z`, for example : `kounkou.stateofus.eth`, and in the current ticket, we fall into a dilemma where we have 2 cases : 

1- If we have a display name not being in the `x.y.z` format and we want to change to the `x.y.z` format, the validation will fail.

2- If we had 2 ENS names to choose from, and we decided to move from one to another ENS name, then the validation will fail for the same.

Case 2 raises the question : 

- How is the ENS name set in the first place ?

This is because upon updating the ENS name, the actual call to update settings is https://github.com/status-im/status-desktop/blob/master/src/app_service/service/settings/service.nim#L148

### Solution Proposal

When a user update the preferred name, we should just ignore if the name is an ENS name, because the ENS name is set only in the ENS popup. But this also means that if a user set the profile  name to an ENS name, this change will also be ignored.

fixes https://github.com/status-im/status-desktop/issues/14048

### CODE REVIEW

File: common/utils.go [hunk 1]
```diff
@@ -55,3 +59,18 @@ func ValidateDisplayName(displayName *string) error {
...
 	return nil
 }
+
+// implementation referenced from https://github.com/embarklabs/embark/blob/master/packages/plugins/ens/src/index.js
+func IsENSName(displayName string) bool {
+	if len(displayName) == 0 {
+		return false
+	}
+
+	for _, ensExt := range ENS_ALLOWLIST {
```
Comment (jrainville) [inline common/utils.go]: This is not entirely true. We block above `_eth` and `-eth` because they look like ENS names, but they are not. Only `.eth` is a real ENS name.

So here you should only check for `.eth`

**Review by jrainville — COMMENTED** [review]
Looks good apart from the IsENS function needing a small fix

**Review by MishkaRogachev — APPROVED** [review]
Looks good!

**Review by jrainville — APPROVED** [review]
