### PR TITLE
fix(edit)_: make sure the contentType stays the same after an edit

### LINKED ISSUE #16741: Album is gone after application restart. Leading text message is duplicated
# Bug Report

## Steps to reproduce

1. in any chat, send 2 images with leading text
2. edit the text
3. restart the app
4. check on the images and text

#### Expected behavior

- 2 images are present
- text is present, edited as it was

#### Actual behavior

- images are gone
- text is duplicated

Image

### Additional Information

- Status desktop version: master commit 3e9e8bfe077b7a4ca1102066db57e85f75a62b2e
- Operating System: any

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/16741

The issue was that in image messages, you can update the text, but then the ContentType would become Text and lose the image. The solution is to ignore ContentType changes, since there is no way to change the type of message.

I'm not sure if I should mark as a breaking change or not since I deprecate one of `EditMessage`'s param. You can still send it obviously, but we should remove it as it's no longer used. cc @igor-sirotin @ilmotta

### CODE REVIEW

File: protocol/requests/edit_message.go [hunk 1]
```diff
@@ -12,11 +12,12 @@ var ErrEditMessageInvalidID = errors.New("edit-message: invalid id")
...
-	Text               string                           `json:"text"`
-	ContentType        protobuf.ChatMessage_ContentType `json:"content-type"`
-	LinkPreviews       []common.LinkPreview             `json:"linkPreviews"`
-	StatusLinkPreviews []common.StatusLinkPreview       `json:"statusLinkPreviews"`
+	ID                 types.HexBytes             `json:"id"`
+	Text               string                     `json:"text"`
+	LinkPreviews       []common.LinkPreview       `json:"linkPreviews"`
+	StatusLinkPreviews []common.StatusLinkPreview `json:"statusLinkPreviews"`
+	// Deprecated: The ContentType cannot be edited
+	ContentType protobuf.ChatMessage_ContentType `json:"content-type"`
```
Comment (ilmotta) [inline protocol/requests/edit_message.go]: This field is only used now in a test. Wouldn't it be safe to remove the field from the struct, or would that cause the endpoint using the request struct to blow up?

**Review by ilmotta — APPROVED** [review]
LGTM 👍🏼

File: protocol/requests/edit_message.go (hunk 1 above)
Comment (jrainville) [reply protocol/requests/edit_message.go]: I assumed that if clients still use it it would cause the request to fail, but I haven't tested. I'll give it a go and report.

Comment (jrainville) [reply protocol/requests/edit_message.go]: I just tested and the request accepts "unknown" params. So even if mobile still send ContentType, it would still work. I can remove it completely then

Comment (ilmotta) [reply protocol/requests/edit_message.go]: After @churik confirms the bug is gone and https://github.com/status-im/status-mobile/issues/21540 is closed we will have an ~~issue~~ PR to stop sending the parameter as well @jrainville.

File: protocol/messenger_edit_message_test.go [hunk 2]
```diff
@@ -90,6 +90,88 @@ func (s *MessengerEditMessageSuite) TestEditMessage() {
...
+	s.Require().NoError(err)
+
+	ourChat := CreateOneToOneChat("Our 1TO1", &theirMessenger.identity.PublicKey, s.m.transport)
+	err = s.m.SaveChat(ourChat)
+	s.Require().NoError(err)
+
+	const messageCount = 1
+	var album []*common.Message
+
+	for i := 0; i < messageCount; i++ {
```
Comment (osmaczko) [inline protocol/messenger_edit_message_test.go:108]: `const messageCount = 1` :eyes:

**Review by osmaczko — APPROVED** [review]

File: protocol/messenger_edit_message_test.go (hunk 2 above)
Comment (jrainville) [reply protocol/messenger_edit_message_test.go:108]: lol yes. I didn't know how to send only one image so I copied the code from the album test which sends multiple images.

The test becomes way more complex for no reason when using more than one image, so I decided to just put `messageCount = 1` :sweat_smile:

**Comment by jrainville** [comment]
This was tested on [Desktop](https://github.com/status-im/status-desktop/pull/16827#pullrequestreview-2474058491) and [Mobile](https://github.com/status-im/status-mobile/issues/21540#issuecomment-2512972902) and it works on both
