### PR TITLE
fix(keypair): fix crash when when updating display name twice

### LINKED ISSUE #18503: Changing display name a couple of times in a row stops syncing the updates
If i have 2 synced devices and i change display name a couple of times, the updates stop coming to the synced instance

```
2025-08-05T14:40:44.887Z    INFO    protocol/messenger.go:1339    handling private-chat ChatIdentity
2025-08-05T14:40:44.887Z    DEBUG    protocol/messenger.go:1021    attached chat identity    {"images len": 0}

2025-08-05T14:41:15.546Z    INFO    protocol/messenger.go:1339    handling private-chat ChatIdentity
2025-08-05T14:41:15.546Z    DEBUG    protocol/messenger.go:1021    attached chat identity    {"images len": 0}
2025-08-05T14:41:15.547Z    DEBUG    common/message_segmentation.go:64    message segmented    {"segments": 1}
```

Image

Image

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/18503

I'm not sure if I fixed the root cause, but what was happening is that each time the display name was update, the keypairs were also sent with it and it caused a signal to be sent that "keypairs were added", which is not true. That signal triggered a refetch of collectibles, which in turn caused the crash. This is where I'm a bit lost. I don't know why it would crash exactly. I assume it's because it was calling the fetches in too rapid a succession so the previous one was not over, hence deleting the previous one in the middle of it and crashing.

[display-name-change.webm](https://github.com/user-attachments/assets/012c1f16-4be1-4471-b022-4168ad72e954)

### CODE REVIEW

File: protocol/messenger_handler.go [hunk 1]
```diff
@@ -3733,22 +3737,21 @@ func (m *Messenger) handleSyncKeypair(message *protobuf.SyncKeypair, fromLocalPa
...
-				pubsub.Publish(m.config.accountsPublisher, accountsevent.AccountsAddedEvent{
-					Accounts: addedAddresses,
-				})
-			}
-			if len(removedAddresses) > 0 {
-				pubsub.Publish(m.config.accountsPublisher, accountsevent.AccountsRemovedEvent{
-					Accounts: removedAddresses,
-				})
-			}
+
```
Comment (dlipicar) [inline protocol/messenger_handler.go:3750]: the `if m.config.accountsPublisher != nil` check was there mainly to prevent crashes in tests where we don't initialize every possible thing, did you remove it for some particular reason?

Comment (jrainville) [reply protocol/messenger_handler.go:3750]: It's not shown directly on Github, but on line 3722/3726, there is that condition already.

So I,m just removing duplicated code

File: protocol/messenger_handler.go [hunk 2]
```diff
@@ -3733,22 +3741,23 @@ func (m *Messenger) handleSyncKeypair(message *protobuf.SyncKeypair, fromLocalPa
 				}
 				if acc.Removed {
 					removedAddresses = append(removedAddresses, gethcommon.Address(acc.Address))
```
Comment (saledjenic) [inline protocol/messenger_handler.go:3744]: @jrainville do we need similar logic for the removed addresses?

File: common/utils.go [hunk 3]
```diff
@@ -158,3 +159,12 @@ func TruncateWithDot(s string) string {
 func Ptr[T any](v T) *T {
 	return &v
 }
+
+func ContainsAddress(addresses []types.Address, address types.Address) bool {
```
Comment (dlipicar) [inline common/utils.go]: https://pkg.go.dev/slices#Contains

Comment (jrainville) [reply common/utils.go]: I asked AI if there was a function to do that and it said no :unamused: Stupid clankers

Comment (dlipicar) [reply common/utils.go]: AI not taking muh job for a little while longer

**Comment by jrainville** [comment]
@saledjenic added the similar logic for removed accounts too

**Review by saledjenic — APPROVED** [review]

**Review by dlipicar — APPROVED** [review]
