### PR TITLE
fix(wallet): do not create databases on verifyDatabasePassword call.

### LINKED ISSUE #11979: Cannot login
# Bug Report

## Description

Cannot login anymore. Getting "incorrect password" when I know it's correct (using a password manager).

Logs:

```
▶ ~/.local/bin/StatusIm-Desktop-230821-200320-7274e6-x86_64.AppImage
INFO [08-22|16:53:26.189] Status backend initialized               backend=geth version=0.163.11 commit=3bf0bed78 IpfsGatewayURL=https://ipfs.status.im/
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. (:0, )
INF 2023-08-22 16:53:27.438+10:00 Version: 0.9.90                            topics="status-app" tid=103272 file=nim_status_client.nim:189
INF 2023-08-22 16:53:27.439+10:00 Commit: 7274e6156                          topics="status-app" tid=103272 file=nim_status_client.nim:190
INF 2023-08-22 16:53:27.439+10:00 Current date:                              topics="status-app" tid=103272 file=nim_status_client.nim:191 currentDateTime=2023-08-22T16:53:27+10:00
INF 2023-08-22 16:53:27.439+10:00 starting application controller...         topics="status-app" tid=103272 file=nim_status_client.nim:193
INF 2023-08-22 16:53:36.595+10:00 starting application...                    topics="status-app" tid=103272 file=nim_status_client.nim:196
WRN 2023-08-22 16:53:36.596+10:00 Error decoding signal                      topics="signals-manager" tid=103272 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
Debug: Network Cache Dir:  "/home/fryorcraken/.config/Status/tmp/netcache" (:0, )
Warning: QQuickItem::stackBefore: Cannot stack AccountMenuItemPanel_QMLTYPE_484(0x559f34e39010, parent=0x559f34ba1cd0, geometry=0,0 342x64) before AccountMenuItemPanel_QMLTYPE_484(0x559f349e9100, name = "LoginView_addNewUserItem"), which must be a sibling (:0, )
ERROR[08-22|16:53:45.816] failed to initialize wallet db           package=status-go/api.GethStatusBackend err="failed to set `journal_mode` pragma: file is not a database"
failed to set `journal_mode` pragma: file is not a database
ERR 2023-08-22 16:53:45.816+10:00 error:                                     topics="accounts-service" tid=103272 file=service.nim:619 procName=verifyDatabasePassword errDesription="failed to set `journal_mode` pragma: file is not a database"
ERROR[08-22|16:53:48.348] failed to initialize wallet db           package=status-go/api.GethStatusBackend err="failed to set `journal_mode` pragma: file is not a database"
ERROR[08-22|16:53:48.348] failed to start a node                   key-uid=0x74c9c15fe362623c55226f9ba674fd9cca46f83c280a0fd75a7d256b0639a390 error="failed to set `journal_mode` pragma: file is not a database"
ERR 2023-08-22 16:53:48.348+10:00 node.login                                 topics="signals-manager" tid=103272 file=signals_manager.nim:48 error="failed to set `journal_mode` pragma: file is not a database"
ERR 2023-08-22 16:53:48.352+10:00 login error                                topics="app-controller" tid=103272 file=module.nim:436 methodName=onNodeLogin errDesription="failed to set `journal_mode` pragma: file is not a database"

```

### Additional Information

- Status desktop version: StatusIm-Desktop-230821-200320-7274e6-x86_64.AppImage
- Operating System: Fedora Linux

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
UI called `verifyDatabasePassword` which created a database if not existed with the old (uppercase) password due to UI implementation. This caused wallet DB to be created with that password, that does not match app db password.

Closes [#11979](https://github.com/status-im/status-desktop/issues/11979)

### CODE REVIEW

File: api/geth_backend.go [hunk 1]
```diff
@@ -1363,6 +1418,10 @@ func (b *GethStatusBackend) VerifyDatabasePassword(keyUID string, password strin
 		return err
 	}
 
+	if !b.appDBExists(keyUID) || !b.walletDBExists(keyUID) {
```
Comment (IvanBelyakoff) [inline api/geth_backend.go:1421]: The actual fix is here

**Review by jrainville — APPROVED** [review]
