### PR TITLE
fix(backup)_: dont generate a CR if the synced contact is mutual

### LINKED ISSUE #15849: Strange private chat content after restoring from seed phrase
# Bug Report

## Description

After successful account restoring, in every private chat there was a message sent from me: "Please add me to your contacts" with incorrect date: 1.01.1970. This message was not seen by another user.

image

## Steps to reproduce

Have a private chat with another account.
Restore account from seed phrase.
Restoring completed successfully.
Go to private chat and check content.

### Additional Information

- Status desktop version:  release/2.30.x
- Operating System: macosx

_NOTE_
This issue was also mentioned in https://github.com/status-im/status-desktop/issues/14052

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/15849

The problem was that we generated a "fake" contact request for all synced contacts. While it's true that even mutual contacts have a contact request, we don't need it anymore once mutual and since we don't sync messages, we had to generate it with a default message and that message looked very out of place after a recovery.

Mutual contact:
image

Contact that sent us a CR (not sure why the image and name don't show:
image

Contact to whom we sent a CR:
image

Now, the CR messages at least make sense

### CODE REVIEW

File: protocol/messenger_contacts.go [hunk 1]
```diff
@@ -601,6 +601,7 @@ func (m *Messenger) generateContactRequest(clock uint64, timestamp uint64, conta
 	contactRequest := common.NewMessage()
 	contactRequest.ChatId = contact.ID
 	contactRequest.WhisperTimestamp = timestamp
+	contactRequest.Timestamp = timestamp
```
Comment (jrainville) [inline protocol/messenger_contacts.go:604]: Without this, the message showed as being sent in 1970

**Comment by jrainville** [comment]
@osmaczko @igor-sirotin friendly reminder to review

**Review by osmaczko — COMMENTED** [review]
`TestPairAcceptContactRequest` is failing, can you please take a look?

**Comment by jrainville** [comment]
@osmaczko fixed! Tests are green now. @igor-sirotin you can review too

**Review by osmaczko — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]
