### PR TITLE
fix_: nightly test runs

### LINKED ISSUE #5401: Nightly tests coverage is broken
# Problem

```
03:51:03  2024/06/21 02:50:55 failed to parse profiles: open /home/jenkins/workspace/status-go/tests-nightly/abi-spec/coverage.out.rerun.*: no such file or directory
````

https://ci.status.im/job/status-go/job/tests-nightly/258/consoleFull

# Implementation

This is probably happening because nightly tests are running in parallel.
So code like `rm -f ${package_dir}/coverage.out.rerun.*` simply deletes the coverage reports of other runs.

We should add the `${iteration}` to the wildcard.

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/status-im/status-go/issues/5401

https://github.com/status-im/status-go/pull/5731 made nightly tests extremely long.

`go test ./protocol -test.count=20` was run in a single process, so it was taking `~30min * 20runs = 10hours`.
This is not acceptable. Quickly making the `protocol` package run faster didn't seem possible, so I reverted the solution to spawn multiple processes.

Yet, the result utilizes both approaches.
The `protocol` package is now an exclusion, all other packages are run with default `go test` behaviour.

Also fixed the coverage reporting for nightly tests

Test run for `count=20`: https://ci.status.im/job/status-go/job/tests-nightly/366/

NOTE: I currently included https://github.com/status-im/status-go/pull/5793 into this PR. 
Will remove it when it's merged.

### CODE REVIEW

**Comment by igor-sirotin** [comment]
The first group of tests is still timing out, even with 5 minutes per run 🤔 
```
panic: test timed out after 1h40m0s
```

**Comment by igor-sirotin** [comment]
Alright, no timeout panics now:
image

File: _assets/scripts/run_unit_tests.sh [hunk 1]
```diff
@@ -83,33 +101,70 @@ fi
...
+PROTOCOL_TIMEOUT_MINUTES=45
+
+HAS_PROTOCOL_PACKAGE=true
+if [[ $(echo "${UNIT_TEST_PACKAGES}" | grep -E '\s?\S+protocol\s+') == "" ]]; then
+  HAS_PROTOCOL_PACKAGE=false
+fi
+
+if [[ $HAS_PROTOCOL_PACKAGE == 'false' ]]; then
+  # This is the default single-line flow for testing all packages
+  # The `else` branch is temporary and will be removed once the `protocol` package runtime is optimized.
```
Comment (osmaczko) [inline _assets/scripts/run_unit_tests.sh:115]: This will stay with us for a while :D

**Review by osmaczko — APPROVED** [review]

File: _assets/scripts/test.sh
Comment (osmaczko) [inline _assets/scripts/test.sh:1]: Empty file :police_officer:

File: _assets/scripts/run_unit_tests.sh (hunk 1 above)
Comment (igor-sirotin) [reply _assets/scripts/run_unit_tests.sh:115]: true 🥲

File: _assets/scripts/test.sh
Comment (igor-sirotin) [reply _assets/scripts/test.sh:1]: oops
