### PR TITLE
fix_: when preparing a balance map skip chains where cannot get the balance, instead of returning the error

### LINKED ISSUE #16053: Can't send in send modal if one of processors failed
# Bug Report

## Description

Cant send on Mainnet if Arb fails

## Steps to reproduce

on testnet for example (to replicate faster) try to send on Mainnet when you see a red banner for Arb

#### Expected behavior

Can send

#### Actual behavior

Screenshot 2024-08-09 144909

Screenshot 2024-08-09 144836

### Additional Information

- Status desktop version: 2.30 rc5
- Operating System: MacOS, Windows, Linux

### PR DESCRIPTION
**Pull request by saledjenic**
In this PR, instead of returning from the router when a network error for fetching balance occurs we just skip it and try to fetch balances from other chains. This way if at least one provider is live and the user has a positive balance on it the router will return that route as a possible one. While fetching balances we chain errors per chain and symbol so that we can have better insight into what went wrong.

Closes https://github.com/status-im/status-desktop/issues/16053

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

File: services/wallet/router/router_v2.go [hunk 1]
```diff
@@ -541,38 +542,57 @@ func (r *Router) getBalanceMapForTokenOnChains(ctx context.Context, input *Route
...
 		}
 
+		// add native token balance for the chain
 		nativeBalance, err := r.getBalance(ctx, chain.ChainID, nativeToken, input.AddrFrom)
 		if err != nil {
-			return nil, errors.CreateErrorResponseFromError(err)
+			chainError(chain.ChainID, token.Symbol, errors.CreateErrorResponseFromError(err))
+		}
+		// add only if balance is not nil
+		if nativeBalance != nil {
```
Comment (ilmotta) [inline services/wallet/router/router_v2.go:593]: Quick question, is this new behavior of trying chains in succession covered by test(s)?

File: services/wallet/router/router_v2.go [hunk 2]
```diff
@@ -541,38 +542,57 @@ func (r *Router) getBalanceMapForTokenOnChains(ctx context.Context, input *Route
...
+		} else {
+			err = fmt.Errorf("%s; chain %d, token %s: %w", err.Error(), chainId, token, intErr)
+		}
+	}
+
 	for _, chain := range selectedFromChains {
+		// check token existance
 		token := input.SendType.FindToken(r.tokenManager, r.collectiblesService, input.AddrFrom, chain, input.TokenID)
 		if token == nil {
+			chainError(chain.ChainID, token.Symbol, ErrTokenNotFound)
```
Comment (ilmotta) [inline services/wallet/router/router_v2.go:557]: A point of improvement for a follow-up is to apply the circuit breaker pattern, thus, if the input params are the same, we wouldn't even try to use chains that failed previously (within a small window of time of course).

**Review by ilmotta — APPROVED** [review]

File: services/wallet/router/router_v2.go (hunk 1 above)
Comment (saledjenic) [reply services/wallet/router/router_v2.go:593]: Hi @ilmotta we don't have tests that simulate failed network calls, thus the answer is no, it's not covered.

File: services/wallet/router/router_v2.go (hunk 2 above)
Comment (saledjenic) [reply services/wallet/router/router_v2.go:557]: @ilmotta thanks for the proposal. Yes, if we would implement that within a very small time window it would make sense, but, here is another story, actually its two aspects are:
- providers are that flaky (for some reason) that you can in two consecutive calls  once get the data and next  time don't, or vice versa,
- another point is, that this call to prepare the balance map is called at the beginning of the router algorithm and that once for each call for generating the best route, so not sure even if we would implement a circuit breaker if it would pay off since the time between two consecutive calls if for sure more than a second (depends on input params), even more, and many things might be changed within that time window.

File: services/wallet/router/router_v2.go [hunk 3]
```diff
@@ -499,7 +499,8 @@ func (r *Router) SuggestedRoutesV2(ctx context.Context, input *RouteInputParams)
 	}
 
 	balanceMap, err := r.getBalanceMapForTokenOnChains(ctx, input, selectedFromChains)
-	if err != nil {
+	// return only if there are no balances, otherwise try to resolve the candidates for chains we know the balances for
+	if len(balanceMap) == 0 && err != nil {
```
Comment (cammellos) [inline services/wallet/router/router_v2.go:503]: Is it an error condition that there are no balances?

Comment (cammellos) [reply services/wallet/router/router_v2.go:503]: nevermind, misread
