### PR TITLE
fix: ensure `CommunityDescription` reprocessing on decryption failure

### LINKED ISSUE #13647: Community Member list disappearing issue is still present randomly
# Bug Report

## Description

We were testing communities on mainnet.

I joined the community and the `#general` (only channel at the time) member list was empty. I could chat normally though.
After a restart, the list was there.

Later, the owner created a new channel and again, it was empty.

## Steps to reproduce

This issue is kinda random, but here were the steps we did:

0. Have a Community with a permission to join using a community NFT
1. Have yourself be the owner of both the TM token and that NFT to join
2. Join the community
3. No member list
4. Restart the app
5. Member list is there
6. Owner creates a new channel with a permission to Write on it using a new token
7. I can still access it because I'm a TM
8. No member list

#### Expected behavior

The member list is always present

#### Actual behavior

The member list is not there at first join and creation

### Additional Information

- Status desktop version: 2.27RC2
- Operating System: Ubuntu 20

### PR DESCRIPTION
**Pull request by osmaczko**
Previously, `CommunityDescription` instances failing partial decryption were not reprocessed due to duplicate message check. This commit fixes the issue by bypassing the check for such descriptions, allowing their reprocessing upon receiving missing encryption key.

fixes: status-im/status-desktop#13647

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

File: protocol/messenger.go [hunk 1]
```diff
@@ -3704,6 +3704,19 @@ func (m *Messenger) outputToCSV(timestamp uint32, messageID types.HexBytes, from
 	}
 }
 
+func (m *Messenger) shouldSkipDuplicate(messageType protobuf.ApplicationMetadataMessage_Type) bool {
+	// Permit re-processing of ApplicationMetadataMessage_COMMUNITY_DESCRIPTION messages,
+	// as they may be queued pending receipt of decryption keys.
+	allowedDuplicateTypes := []protobuf.ApplicationMetadataMessage_Type{protobuf.ApplicationMetadataMessage_COMMUNITY_DESCRIPTION}
```
Comment (cammellos) [inline protocol/messenger.go]: not that it matters so much, but I would make it a map, with a single message, it doesn't matter, but as we add more, then it becomes O(number of elements) rather than constants

**Review by cammellos — APPROVED** [review]
