### PR TITLE
fix(communities)_: ensure community sync doesn't override joined state

### LINKED ISSUE #15009: Getting kicked out of community - checked with owner who did not kick me out
# Bug Report

## Description

Second time that after a weekend of not using laptop (Status desktop kept open) I am getting kicked of Status Inu community on Monday. I checked with owner who did not take such action.

## Steps to reproduce

Unsure...

Join Status Inu
Get approved
chat during the week
dont use laptop during weekend
kicked out on Monday

#### Expected behavior

Only get kicked out when the owner actually does the action

#### Actual behavior

Getting kicked out without owner action

### Additional Information

- Status desktop version: 2.28.1 App Image
- Operating System: Fedora x8_64

[app_20240531_145729.log](https://github.com/user-attachments/files/15528171/app_20240531_145729.log)

geth.log:
- https://drive.proton.me/urls/E3HS67YNNM#etYSfpS3TxJi
- https://drive.proton.me/urls/Y1STNH8A4G#Ma2SsWIsDmet

### PR DESCRIPTION
**Pull request by osmaczko**
potentially fixes: status-im/status-desktop#15009

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Nice find!

File: protocol/messenger_communities.go [hunk 1]
```diff
@@ -3785,6 +3785,7 @@ func (m *Messenger) handleSyncInstallationCommunity(messageState *ReceivedMessag
 		logger.Debug("m.handleCommunityDescription error", zap.Error(err))
 		return err
 	}
+	descriptionOutdated := err == communities.ErrInvalidCommunityDescriptionClockOutdated
```
Comment (igor-sirotin) [inline protocol/messenger_communities.go:3788]: Not your code, but how about renaming 
`ErrInvalidCommunityDescriptionClockOutdated` to 
`ErrCommunityDescriptionOutdated`?

Because it's either Invalid or outdated.
Also, `Outdated` already means time, so no reason for explicit `Clock`.

**Review by igor-sirotin — APPROVED** [review]

File: protocol/messenger_communities.go (hunk 1 above)
Comment (osmaczko) [reply protocol/messenger_communities.go:3788]: I agree with your points, but also there is a convention I tried to follow:
```
var ErrInvalidCommunityDescriptionClockOutdated = errors.New("invalid community description outdated clock")
var ErrInvalidCommunityDescriptionNoOrgPermissions = errors.New("invalid community description no org permissions")
var ErrInvalidCommunityDescriptionNoChatPermissions = errors.New("invalid community description no chat permissions")
var ErrInvalidCommunityDescriptionUnknownChatAccess = errors.New("invalid community description unknown chat access")
var ErrInvalidCommunityDescriptionUnknownOrgAccess = errors.New("invalid community description unknown org access")
var ErrInvalidCommunityDescriptionMemberInChatButNotInOrg = errors.New("invalid community description member in chat but not in org")
var ErrInvalidCommunityDescriptionCategoryNoID = errors.New("invalid community category id")
var ErrInvalidCommunityDescriptionCategoryNoName = errors.New("invalid community category name")
var ErrInvalidCommunityDescriptionChatIdentity = errors.New("invalid community chat name, missing")
var ErrInvalidCommunityDescriptionDuplicatedName = errors.New("invalid community chat name, duplicated")
var ErrInvalidCommunityDescriptionUnknownChatCategory = errors.New("invalid community category in chat")
```

To keep the convention, I tried to change it to `ErrInvalidCommunityDescriptionOutdated`, but it sounds even more odd :sweat_smile:

Comment (igor-sirotin) [reply protocol/messenger_communities.go:3788]: 🆗
