### PR TITLE
feat_: recovery retracking pending transsactions

### LINKED ISSUE #14699: Owner token stuck on "Minting..."
# Bug Report

## Description

Some tokens can get stuck in the "Minting..." state, and it can even be  the Owner token. If that happens, it basically borks the community as you cannot try again.

We need to not only try to make sure if never happens, but also find a way to fix that state if it happened previously (retroactively fix those that were stuck previously).

## Steps to reproduce

1. Mint a token in a community
2. Wait
3. Maybe it gets stuck
Restart 1 until it gets stuck

#### Expected behavior

Tokens get updated when the transaction is minted, or at least end up being updated with a decent delay

#### Actual behavior

tokens have a chance to get forever stuck in the Minting state

### Additional Information

- Status desktop version: 2.28.1

### PR DESCRIPTION
**Pull request by endulab**
Add ReTrackOwnerTokenDeploymentTransaction function which will run community tokens transactions listening.
This function will be used to recover some stucked tokens in the situation that: token is in minting state and there is no pending transaction in database.
Add deployment transaction hash to community_tokens table.

Issue [#14699](https://github.com/status-im/status-desktop/issues/14699)

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

File: services/communitytokens/service.go [hunk 1]
```diff
@@ -531,17 +532,32 @@ func (s *Service) CreateCommunityTokenAndSave(chainID int, deploymentParameters
...
 
 	return s.Messenger.SaveCommunityToken(tokenToSave, deploymentParameters.CroppedImage)
 }
 
+const (
+	MasterSuffix = "-master"
+	OwnerSuffix  = "-owner"
+)
+
 func (s *Service) TemporaryMasterContractAddress(hash string) string {
```
Comment (stefandunca) [inline services/communitytokens/service.go:546]: Just a note that this name is misleading, it is not returning a contract address but some kind of identifier made form contract address and the sufix label. How about changing in a follow up PR to something like `TemporaryMasterContractID`?
The same down the line where this is used should be identified by the right naming convention. Also using named types instead of plain string might help.
We had the same issue in `transfers` table where the "hash" column is not always a hash but might be a derived Unique ID so spent some time debugging code to find out this.

**Review by stefandunca — APPROVED** [review]
I'm glad you found a way to retroactively fix things.

One note is that the `ReTrackOwnerTokenDeploymentTransaction` has so many conditions and exit states that it will be good to follow up with some basic unit tests to cover the main expected flow.

I also left a note inline about some improvements I can see for a future refactoring.
