### PR TITLE
fix: flaky test request profile info

### LINKED ISSUE #4845: Flaky test: TestRequestProfileInfo
[TestMessengerStoreNodeRequestSuite/TestRequestProfileInfo: 10.0% (2 of 20 failed)](https://ci.status.im/job/status-go/job/tests-nightly/142/Reports/)

```
/home/jenkins/workspace/status-go/tests-nightly/protocol/messenger_storenode_request_test.go:586
        	Error:      	Expected value not to be nil.
        	Test:       	TestMessengerStoreNodeRequestSuite/TestRequestProfileInfo
    --- FAIL: TestMessengerStoreNodeRequestSuite/TestRequestProfileInfo (2.35s)
```

https://ci.status.im/job/status-go/job/tests-nightly/142/testReport/github/com_status-im_status-go_protocol/TestMessengerStoreNodeRequestSuite_TestRequestProfileInfo/

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-go/issues/4845

### CODE REVIEW

File: protocol/messenger_storenode_request_test.go [hunk 1]
```diff
@@ -353,13 +365,32 @@ func (s *MessengerStoreNodeRequestSuite) wakuListenAddress(waku *waku2.Waku) str
...
+	s.logger.Debug("store node query result", zap.Int("messagesCount", len(result.Messages)))
+}
+
 func (s *MessengerStoreNodeRequestSuite) TestRequestCommunityInfo() {
 	s.createOwner()
 	s.createBob()
 
 	community := s.createCommunity(s.owner)
 
-	s.waitForAvailableStoreNode(s.bob)
```
Comment (igor-sirotin) [inline protocol/messenger_storenode_request_test.go:362]: This is already done inside `fetchCommunity`

File: protocol/messenger_storenode_request_test.go [hunk 2]
```diff
@@ -183,8 +187,11 @@ func (s *MessengerStoreNodeRequestSuite) createOwner() {
 	s.owner = s.newMessenger(s.ownerWaku, messengerLogger, s.storeNodeAddress)
 
 	// We force the owner to use the store node as relay peer
-	err := s.owner.DialPeer(s.storeNodeAddress)
-	s.Require().NoError(err)
+	WaitForPeersConnected(&s.Suite, gethbridge.GetGethWakuV2From(s.ownerWaku), func() []string {
```
Comment (igor-sirotin) [inline protocol/messenger_storenode_request_test.go:190]: FIX #1: Wait for owner to connect to store node.

File: protocol/messenger_testing_utils.go [hunk 3]
```diff
@@ -240,6 +240,8 @@ func WaitForPeersConnected(s *suite.Suite, waku *waku2.Waku, action func() []str
 		select {
 		case status := <-subscription.C:
 			if hasAllPeers(status.Peers, peerIDs) {
+				// Give some time for p2p events, otherwise might look lik peer is available, but fail to send a message.
+				<-time.After(100 * time.Millisecond)
```
Comment (igor-sirotin) [inline protocol/messenger_testing_utils.go]: FIX #2: Give some time for p2p events to process

File: protocol/messenger_storenode_request_test.go [hunk 4]
```diff
@@ -578,12 +610,20 @@ func (s *MessengerStoreNodeRequestSuite) TestRequestProfileInfo() {
...
+	contentTopicString := transport.ContactCodeTopic(&s.owner.identity.PublicKey)
+	contentTopic := wakuV2common.BytesToTopic(transport.ToTopic(contentTopicString))
+	storeNodeSubscription := s.setupStoreNodeEnvelopesWatcher(&contentTopic)
+
 	// Set display name, this will also publish contact code
 	err = s.owner.SetDisplayName("super-owner")
 	s.Require().NoError(err)
 
+	s.waitForEnvelopes(storeNodeSubscription, 1)
+	s.ensureStoreNodeEnvelopes(&contentTopic, 1)
```
Comment (igor-sirotin) [inline protocol/messenger_storenode_request_test.go:622]: FIX #3: Wait for envelopes to arrive to store node.

`ensureStoreNodeEnvelopes` is not really important here, but in case of error the test will fail 5 seconds faster.
And it's a good thing to have this kind of check in general.

File: protocol/messenger_storenode_request_test.go [hunk 5]
```diff
@@ -353,13 +365,32 @@ func (s *MessengerStoreNodeRequestSuite) wakuListenAddress(waku *waku2.Waku) str
 	return addresses[0]
 }
 
+func (s *MessengerStoreNodeRequestSuite) ensureStoreNodeEnvelopes(contentTopic *wakuV2common.TopicType, minimumCount int) {
+	// Give some time for store node to put envelope into database. Otherwise, the test is flaky.
+	// Although we subscribed to EnvelopeEvents and waited, the actual saving to database happens asynchronously.
+	// It would be nice to implement a subscription for database storing event, but it doesn't worth it right now.
+	<-time.After(100 * time.Millisecond)
```
Comment (plopezlpz) [inline protocol/messenger_storenode_request_test.go]: don't you like to use `time.Sleep(100 * time.Millisecond)`

File: protocol/messenger_testing_utils.go (hunk 3 above)
Comment (plopezlpz) [reply protocol/messenger_testing_utils.go]: I like better `time.Sleep` but up to you

**Review by plopezlpz — APPROVED** [review]

File: protocol/messenger_storenode_request_test.go (hunk 5 above)
Comment (igor-sirotin) [reply protocol/messenger_storenode_request_test.go]: Good point, no idea what came over me 😄

File: protocol/messenger_storenode_request_test.go [hunk 6]
```diff
@@ -353,13 +365,32 @@ func (s *MessengerStoreNodeRequestSuite) wakuListenAddress(waku *waku2.Waku) str
 	return addresses[0]
 }
 
+func (s *MessengerStoreNodeRequestSuite) ensureStoreNodeEnvelopes(contentTopic *wakuV2common.TopicType, minimumCount int) {
+	// Give some time for store node to put envelope into database. Otherwise, the test is flaky.
+	// Although we subscribed to EnvelopeEvents and waited, the actual saving to database happens asynchronously.
+	// It would be nice to implement a subscription for database storing event, but it doesn't worth it right now.
```
Comment (siddarthkay) [inline protocol/messenger_storenode_request_test.go]:
```suggestion
	// It would be nice to implement a subscription for database storing event, but it isn't worth it right now.
```

File: protocol/messenger_testing_utils.go [hunk 7]
```diff
@@ -240,6 +240,8 @@ func WaitForPeersConnected(s *suite.Suite, waku *waku2.Waku, action func() []str
 		select {
 		case status := <-subscription.C:
 			if hasAllPeers(status.Peers, peerIDs) {
+				// Give some time for p2p events, otherwise might look lik peer is available, but fail to send a message.
```
Comment (siddarthkay) [inline protocol/messenger_testing_utils.go]:
```suggestion
				// Give some time for p2p events, otherwise might look like peer is available, but fail to send a message.
```

**Review by siddarthkay — APPROVED** [review]
🧐🧐🧐
