### PR TITLE
fix(wallet)_: fix rpc limiter to reset counters on timeout

### LINKED ISSUE #14642: No collectibles and activity reflected in added watched address account (Testnet)
# Bug Report

After I add watched address account with recent activity and collectibles on it, it is not reflected in wallet (only assets)

## Steps to reproduce

1. Turn on Testnet
2. Add account with watched address ( https://sepolia.etherscan.io/address/0x26d6e10a6af4eb4d12ff4cf133a843eb4fa88d0b )
3. Go to Assets tab - all good
4. Go to Collectibles tab - there is nothing
5. Go to Activity tab - also nothing

### Additional Information

https://github.com/status-im/status-desktop/assets/141633821/f8386dbe-3389-4a98-b3e8-aa4744bdedf2

- Status desktop version: the latest master
- Operating System: macOS Ventura 13.5

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
Fixes:

- fix rpc limiter to reset counters on timeout
- fix rpc limiter to delete limits on account removal
- fix rpc limiter to not overwrite existing account limit on startup
- fix providers down banner on limit reached error

Closes [#14642](https://github.com/status-im/status-desktop/issues/14642)

### CODE REVIEW

File: rpc/chain/rpc_limiter.go [hunk 1]
```diff
@@ -166,10 +188,21 @@ func (rl *RPCRequestLimiter) Allow(tag string) (bool, error) {
 		return true, nil
 	}
 
+	// Check if the interval has passed and reset the number of requests
+	if time.Since(data.CreatedAt) >= data.Period && data.Period.Milliseconds() != LimitInfinitely {
+		err = rl.saveToStorage(tag, data.MaxReqs, data.Period, 0, time.Now())
+		if err != nil {
+			return true, err
```
Comment (saledjenic) [inline rpc/chain/rpc_limiter.go:195]: Do we really want to return `true` in both cases?
If so then just: 
`return true, rl.saveToStorage(tag, data.MaxReqs, data.Period, 0, time.Now())`

File: rpc/chain/rpc_limiter_test.go [hunk 2]
```diff
@@ -84,7 +111,7 @@ func TestAllowWithinPeriod(t *testing.T) {
 
 	// Call the Allow method again
 	allow, err := rl.Allow(tag)
-	require.NoError(t, err)
+	require.ErrorIs(t, ErrRequestsOverLimit, err)
```
Comment (saledjenic) [inline rpc/chain/rpc_limiter_test.go]:
```suggestion
	require.ErrorIs(t, err, ErrRequestsOverLimit)
```

File: rpc/chain/rpc_limiter_test.go [hunk 3]
```diff
@@ -135,7 +162,7 @@ func TestAllowRestrictInfinitelyWhenLimitReached(t *testing.T) {
 
 	// Call the Allow method
 	allow, err := rl.Allow(tag)
-	require.NoError(t, err)
+	require.ErrorIs(t, ErrRequestsOverLimit, err)
```
Comment (saledjenic) [inline rpc/chain/rpc_limiter_test.go]:
```suggestion
	require.ErrorIs(t, err, ErrRequestsOverLimit)
```

File: services/wallet/transfer/commands_sequential.go [hunk 4]
```diff
@@ -1318,3 +1305,42 @@ func nextRange(maxRangeSize int, prevFrom, zeroBlockNumber *big.Int) (*big.Int,
...
+	return transferHistoryTag + "_" + account.String()
+}
+
+func createChainClientWithLimiter(client chain.ClientInterface, account common.Address, limiter chain.RequestLimiter) (chain.ClientInterface, error) {
+	// Each account has its own limit and a global limit for all accounts
+	accountTag := accountLimiterTag(account)
+	chainClient := chain.ClientWithTag(client, accountTag, transferHistoryTag)
+
+	// Check if limit is already reached, then skip the comamnd
+	if allow, err := limiter.Allow(accountTag); !allow {
```
Comment (saledjenic) [inline services/wallet/transfer/commands_sequential.go:1319]: Do we disallow clients with limiter creation if the limit for an account is reached, but for history isn't?

File: services/wallet/transfer/commands_sequential.go [hunk 5]
```diff
@@ -1318,3 +1305,42 @@ func nextRange(maxRangeSize int, prevFrom, zeroBlockNumber *big.Int) (*big.Int,
...
+	if allow, err := limiter.Allow(transferHistoryTag); !allow {
+		log.Info("fetchHistoryBlocksForAccount common limit reached", "chain", chainClient.NetworkID(), "error", err)
+		return nil, err
+	}
+
+	limit, _ := limiter.GetLimit(accountTag)
+	if limit == nil {
+		err := limiter.SetLimit(accountTag, transferHistoryLimitPerAccount, chain.LimitInfinitely)
+		if err != nil {
+			log.Error("fetchHistoryBlocksForAccount SetLimit", "error", err, "accountTag", accountTag)
```
Comment (saledjenic) [inline services/wallet/transfer/commands_sequential.go:1333]: Why we don't return on error? I mean, if saving to the storage fails isn't that an error worth returning, cause no point in having a client with limits anymore?

File: services/wallet/transfer/commands_sequential.go (hunk 4 above)
Comment (IvanBelyakoff) [reply services/wallet/transfer/commands_sequential.go:1319]: we only use this function (and this RPC limiter) for history requests, so yes, in case limit is reached, we dont proceed with searching for transfers.

File: services/wallet/transfer/commands_sequential.go (hunk 5 above)
Comment (IvanBelyakoff) [reply services/wallet/transfer/commands_sequential.go:1333]: I believe limiter is optional in general. So this is not a user feature, this is for us to save on requests. So in case limiter fails for some reason, we dont want to stop requests and cause user some issues with fetching history, but we just behave like there is no limiter at all, like it was before we implemented the limiter.
If that is a common DB issue, we ll have a bunch of other failures when writing to DB and those will be crucial and we normally return error, but if that is specific to the limiter, I dont think we should return error.

File: rpc/chain/rpc_limiter.go (hunk 1 above)
Comment (IvanBelyakoff) [reply rpc/chain/rpc_limiter.go:195]: yes, as I replied below, this is not a critical error, we want to let the user get the history

**Review by saledjenic — APPROVED** [review]
