### PR TITLE
fix_: flaky TestJoinCommunityAsMemberWithMemberAndAdminPermission

### LINKED ISSUE #4760: Flaky test - `TestJoinCommunityAsMemberWithMemberAndAdminPermission`
```go
    communities_messenger_token_permissions_test.go:888: 
                Error Trace:    /Users/igorsirotin/Repositories/Status/status-go/protocol/communities_messenger_token_permissions_test.go:888
                Error:          Received unexpected error:
                                timed out when waiting for communities event
                Test:           TestMessengerCommunitiesTokenPermissionsSuite/TestJoinCommunityAsMemberWithMemberAndAdminPermission
```

### PR DESCRIPTION
**Pull request by osmaczko**
`waitOnCommunitiesEvent` must be invoked before action that triggers the event.

fixes: #4760

### CODE REVIEW

File: protocol/communities_messenger_token_permissions_test.go [hunk 1]
```diff
@@ -959,14 +959,15 @@ func (s *MessengerCommunitiesTokenPermissionsSuite) TestJoinCommunityAsMemberWit
...
-	s.Require().Len(response.Communities(), 1)
 
 	waitOnCommunityPermissionCreated = waitOnCommunitiesEvent(s.owner, func(sub *communities.Subscription) bool {
 		return len(sub.Community.TokenPermissions()) == 2
 	})
 
+	response, err = s.owner.CreateCommunityTokenPermission(&permissionRequestAdmin)
+	s.Require().NoError(err)
+	s.Require().Len(response.Communities(), 1)
+
```
Comment (jrainville) [inline protocol/communities_messenger_token_permissions_test.go:970]: I think you didn't change anything. The function call is on line 971.

Comment (osmaczko) [reply protocol/communities_messenger_token_permissions_test.go:970]: I did :sweat_smile: 

Before:
```
CreateCommunityTokenPermission
waitOnCommunitiesEvent
<-waitOnCommunityPermissionCreated
```


Now:
```
waitOnCommunitiesEvent
CreateCommunityTokenPermission
<-waitOnCommunityPermissionCreated
```

The issue with the former is that `CreateCommunityTokenPermission` can trigger the event before `waitOnCommunitiesEvent` is called. This is causing the flakiness, because sometimes `CreateCommunityTokenPermission` is quick enough to do so. That's why we need to `waitOnCommunitiesEvent` before the action that triggers the event.

Comment (osmaczko) [reply protocol/communities_messenger_token_permissions_test.go:970]: (That's not a function call, it is waiting on a channel).

Comment (jrainville) [reply protocol/communities_messenger_token_permissions_test.go:970]: omg sorry. I misread the function above and thought it was a function being put in a variable that was called below. I just completely misread.

**Review by jrainville — APPROVED** [review]

File: protocol/communities_messenger_token_permissions_test.go (hunk 1 above)
Comment (osmaczko) [reply protocol/communities_messenger_token_permissions_test.go:970]: No worries, thanks for review :+1:

**Review by mprakhov — APPROVED** [review]
