### PR TITLE
fix: set pubsubTopic in request community info from mailserver

### LINKED ISSUE #12465: Community: import community within private key results in an error
### Description

1. create community (on 0.14 release)
2. get its private key
3. try to import this community, for example `0xa9a3bd1828ed35a90f91c6c1ad1945b1b8b816ab273fcf16a07ceda273721c5c` im master

Screenshot 2023-10-17 at 16 28 55

```
DBG 2023-10-17 16:28:35.284+03:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=7117567 file=threadpool.nim:54 messageType=AsyncRequestCommunityInfoTaskArg:ObjectType threadid=7117567 task="{\"$type\":\"AsyncRequestCommunityInfoTaskArg:ObjectType\",\"communityId\":\"0x0213233f281bbe1fd54b3dbae8a418dfd58e78645feedc10bb6a19f1a3db73ce9e\",\"importing\":false,\"vptr\":105553166051456,\"slot\":\"asyncCommunityInfoLoaded\",\"tptr\":4307006544}"
DBG 2023-10-17 16:28:35.285+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=7117567 file=core.nim:27 rpc_method=wakuext_requestCommunityInfoFromMailserver
ERR 2023-10-17 16:28:52.017+03:00 rpc response error                         topics="rpc" tid=7117567 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_requestCommunityInfoFromMailserver, code:-32000, message:failed to request community info for id \'0x0213233f281bbe1fd54b3dbae8a418dfd58e78645feedc10bb6a19f1a3db73ce9e\' from mailserver: context deadline exceeded ]\n"
ERR 2023-10-17 16:28:52.018+03:00 error doing rpc request                    topics="rpc" tid=7117567 file=core.nim:40 methodName=wakuext_requestCommunityInfoFromMailserver exception="\nstatus-go error [methodName:wakuext_requestCommunityInfoFromMailserver, code:-32000, message:failed to request community info for id \'0x0213233f281bbe1fd54b3dbae8a418dfd58e78645feedc10bb6a19f1a3db73ce9e\' from mailserver: context deadline exceeded ]\n"
```

### PR DESCRIPTION
**Pull request by igor-sirotin**
Partially fixes https://github.com/status-im/status-desktop/issues/12465
A more proper and general should be done later: https://github.com/status-im/status-go/issues/4192

1. Set `PubsubTopic` in the created `MailserverBatch`
2. In `requestCommunitiesFromMailserver` make several requests, one for each `PubsubTopic`
3. Lock `mailserverCycle` for reading only during `performMailserverRequest`
4. defer call `forgetCommunityRequest` in `requestCommunitiesFromMailserver`

### CODE REVIEW

File: protocol/messenger_communities.go [hunk 1]
```diff
@@ -2692,7 +2702,9 @@ func (m *Messenger) requestCommunitiesFromMailserver(communities []communities.C
 	m.requestedCommunitiesLock.Lock()
 	defer m.requestedCommunitiesLock.Unlock()
 
-	var topics []types.TopicType
+	// we group topics by PubsubTopic
+	groupedTopics := map[string][]types.TopicType{}
```
Comment (richard-ramos) [inline protocol/messenger_communities.go]: This could allow duplicated TopicTypes. If that's okay, feel free to ignore, otherwise, i'd suggest to maybedefine the groupedTopics like this:
```
groupedTopics := map[string]map[types.TopicType]struct{}
```

and that way, instead of doing an append like  line 2736, you'd do it like this:
```
groupedTopics[filter.PubsubTopic][filter.ContentTopic] = struct{}{}
```

and then in line 2757, you'd obtain the contentTopics with
```
import "golang.org/x/exp/maps"

maps.Keys(contentTopics)
```

File: protocol/messenger_communities.go [hunk 2]
```diff
@@ -2720,24 +2732,44 @@ func (m *Messenger) requestCommunitiesFromMailserver(communities []communities.C
...
+		wg.Add(1)
+		go func(pubsubTopic string, contentTopics []types.TopicType) {
+			_, err := m.performMailserverRequest(func() (*MessengerResponse, error) {
+				batch := MailserverBatch{
+					From:        from,
+					To:          to,
+					Topics:      contentTopics,
+					PubsubTopic: pubsubTopic,
+				}
+				m.logger.Info("requesting historic", zap.Any("batch", batch))
```
Comment (richard-ramos) [inline protocol/messenger_communities.go:2765]: Consider logging the communityID here too:
```suggestion
				m.logger.Info("requesting historic", zap.Any("batch", batch), zap.String("communityID", communityID))
```

File: protocol/messenger_communities.go [hunk 3]
```diff
@@ -2720,24 +2732,44 @@ func (m *Messenger) requestCommunitiesFromMailserver(communities []communities.C
...
+				err := m.processMailserverBatch(batch)
+				return nil, err
+			})
+			if err != nil {
+				m.logger.Error("error performing mailserver request", zap.Error(err))
```
Comment (richard-ramos) [inline protocol/messenger_communities.go]:
```suggestion
				m.logger.Error("error performing mailserver request", zap.String("communityID", communityID), zap.Error(err))
```

**Review by richard-ramos — APPROVED** [review]

File: protocol/messenger_communities.go (hunk 2 above)
Comment (igor-sirotin) [reply protocol/messenger_communities.go:2765]: hmm, we don't really have `communityID` at this stage 🤔

Comment (richard-ramos) [reply protocol/messenger_communities.go:2765]: nvm then! :)

File: protocol/messenger_communities.go (hunk 3 above)
Comment (igor-sirotin) [reply protocol/messenger_communities.go]: there's no `communityID` available at this point, but I added the `batch` to be logged here 👌

File: protocol/messenger_communities.go (hunk 1 above)
Comment (igor-sirotin) [reply protocol/messenger_communities.go]: Nice idea, thank you! 👍
