### PR TITLE
fix: remove communities control/content sharding

### LINKED ISSUE #7401: Revert manual sharding for communities
# Description

Revert the changes made in:
- https://github.com/status-im/status-go/pull/6573

I.e. stop listening to shard `128` and `256` for communities control and content messages.

# Reasoning

The plan has changed since the original task was planned. 

1. `logos-delivery` will be integrated in Status with auto-sharding, which will discard the manual sharding.
2. Community description is planned to be moved off-messaging.

So at the moment, while it's not too late, there is not point to proceed with the breaking change of manual sharding (separate shards for communities control and content). Note that no breaking changes has been made yet.

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-go/issues/7401

status-app pr: https://github.com/status-im/status-app/pull/20369

### CODE REVIEW

File: protocol/messenger_store_node_request_manager.go [hunk 1]
```diff
@@ -81,12 +81,7 @@ func (m *StoreNodeRequestManager) FetchCommunity(ctx context.Context, communityI
 		zap.Any("config", cfg))
 
 	fetch := func() (*communities.Community, StoreNodeRequestStats, error) {
-		// Since now we could have this community description in shards 32 and 128 we are doing the following:
-		//  1. trying to fetch in shards 32 and 128
-		//  2. returning the first non-nil community result
-		//
-		// Eventually we should just go to shard 128, once full migration to Global Community Control and Content Topic is done.
-		return m.fetchCommunity(ctx, communityID, cfg, types2.DefaultShard(), types2.GlobalCommunityControlShard())
+		return m.fetchCommunity(ctx, communityID, cfg, types2.DefaultShard())
```
Comment (igor-sirotin) [inline protocol/messenger_store_node_request_manager.go]: `fetchCommunity` should be simplified, it doesn't need to take multiple shards anymore.

**Review by plopezlpz — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]
