### PR TITLE
fix(communities)_: delay starting torrent client until connection is established

### LINKED ISSUE #14510: 100% of the CPU is used when there is no network
# Bug Report

## Description

When running Status Desktop without an Internet connection, CPU usage is very high.
Doesn't reproduce when network is enabled.

## Steps to reproduce
1. Turn off the network on the computer
2. Launch the application

#### Expected behavior
CPU usage should be as low as possible (around 0-3%).

#### Actual behavior
High CPU usage on application startup

### Additional Information

CPU usage is low when network is on

https://github.com/status-im/status-desktop/assets/1083341/8e3104a0-9b0f-4f6a-b30d-0044ba62d693

CPU usage is *high* when there is no network

https://github.com/status-im/status-desktop/assets/1083341/21ca0f24-5475-435f-a18b-ecff0920843d

- Status desktop version: master on [e8a78e21](https://github.com/status-im/status-desktop/commit/e8a78e21)

<kbd>
image

</kbd>

- Operating System: Macos

### PR DESCRIPTION
**Pull request by friofry**
* `Messenger` is subscribed to connectivity status updates. Whenever status is updated, `Messenger` calls `Manager.setOnline` 
* `Manager` launches TorrentClient on first connection

Closes https://github.com/status-im/status-desktop/issues/14510

### CODE REVIEW

File: protocol/communities/manager.go [hunk 1]
```diff
@@ -445,15 +445,18 @@ func (m *Manager) Start() error {
...
-		err := m.StartTorrentClient()
-		if err != nil {
-			m.LogStdout("couldn't start torrent client", zap.Error(err))
+func (m *Manager) SetOnline(online bool) {
+	if online {
+		if m.torrentConfig != nil && m.torrentConfig.Enabled && !m.TorrentClientStarted() {
+			err := m.StartTorrentClient()
+			if err != nil {
+				m.LogStdout("couldn't start torrent client", zap.Error(err))
+			}
```
Comment (0x-r4bbit) [inline protocol/communities/manager.go:456]: Should this also stop the client if `!online` ?

**Review by 0x-r4bbit — APPROVED** [review]
LGTM, just a minor question

File: protocol/communities/manager.go (hunk 1 above)
Comment (friofry) [reply protocol/communities/manager.go:456]: Hey @0x-r4bbit, 
yeah, I have thought about stopping the client when `!online`. But I have 2 concerns:

1. `StartTorrentClient` creates a new instance of `TorrentClient`. This means that any previous calls to `torrentClient.AddTorrent` may be lost (e.g. it's called from `SeedHistoryArchiveTorrent`). And the same for `AddMagnet`. Is it okay to rebuild `torrentClient` without restoring torrents/magents?
To be on the safe side I only use the `setOnline` method to delay the creation of the `TorrentClient`. 

2.  There is also an api call `EnableCommunityHistoryArchiveProtocol (and Disable)` that starts/stops the `torrentClient` (which could currently be called from the Desktop Settings). And I thought that the behaviour of `setOnline` and `EnableCommunityHistoryArchiveProtocol` might be inconsistent.

Maybe I'm missing other problems.

Comment (0x-r4bbit) [reply protocol/communities/manager.go:456]: > There is also an api call EnableCommunityHistoryArchiveProtocol (and Disable) that starts/stops the torrentClient (which could currently be called from the Desktop Settings). And I thought that the behaviour of setOnline and EnableCommunityHistoryArchiveProtocol might be inconsistent.

Yes, as a matter of fact, back then, it was a requirement for the torrent to always be bootstrapped when using desktop clients. The setting to enable/disable the protocol was more of a thing for development (this might have changed by now).

Considering that, it indeed makes sense to keep the client running once it has started (unless the protocol is disabled entirely).
The reason I brought this up here is because I thought, when `!online`, the torrent client might cause high CPU usage again, but maybe that's not the case?

Comment (friofry) [reply protocol/communities/manager.go:456]: > Yes, as a matter of fact, back then, it was a requirement for the torrent to always be bootstrapped when using desktop clients. The setting to enable/disable the protocol was more of a thing for development (this might have changed by now).
> 
> Considering that, it indeed makes sense to keep the client running once it has started (unless the protocol is disabled entirely).

I see, thank you for clarifying that.

> The reason I brought this up here is because I thought, when !online, the torrent client might cause high CPU usage again, but maybe that's not the case?

Yes, the torrent client only uses a lot of CPU when it's started while offline.

Here I'm enabling and disabling the network, but the CPU usage remains low:

https://github.com/status-im/status-go/assets/1083341/fc1bd684-8525-4095-8818-541407646583

**Review by jrainville — APPROVED** [review]
LGTM
