### PR TITLE
Cover transaction manager with additional test cases #561

### LINKED ISSUE #561: Cover transaction manager with additional test cases
# Problem

Transaction manager (`txqueue_manager.go`) should be covered with additional test cases to ensure that it won't get accidentally broken after next changes. 

Test cases that are currently missing:
1. Verify that gas value and gas price is not ignored if received from a user
2. Verify that a transaction is signed as we expect it to be signed

# Implementation

1. We definitely need to have additional test case with gas and gas price defined by a user. Might be 2 different test cases or 1 with both values defined.
2. Second part of the issue is about verifying that we are sending transaction that we are expecting to send. I was planning to prepare a Transaction with all expected values, sign it the same way we do in transaction manager, rlp encode and provide as an expected value to a mock.

### PR DESCRIPTION
**Pull request by canercidam**
Changes `setupTransactionPoolAPI` to prepare mock functions in a more strictly covering way, regarding gas, gas price and resulting transaction.

Closes #561

@dshulyak

### CODE REVIEW

**Comment by canercidam** [comment]
I'm going to extend `TestCompleteTransaction` in a table-driven manner with non-nil gas and gas price cases, if these changes look good enough.

**Comment by dshulyak** [comment]
Yes, this approach looks good. https://github.com/status-im/status-go/pull/537 was merged, so now it is possible to overwrite timeout for waiting. 

But what about that wg.Wait? Did you found what was causing that problem?

**Comment by canercidam** [comment]
```go
ctx, cancel = context.WithTimeout(context.Background(), defaultTimeout)
defer cancel()
if err := m.ethTxClient.SendTransaction(ctx, signedTx); err != nil {
	return hash, err
}
```
Looks like `defaultTimeout` affects that, so I'm trying to see in source code how context timeout keeps
```go
return ec.c.CallContext(ctx, nil, "eth_sendRawTransaction", common.ToHex(data))
```
line in `SendTransaction` from finalizing. I think the quick solution at the moment is having a `ctxTimeout` field in `Manager` as well and setting it to a low value in tests.

**Comment by canercidam** [comment]
go-ethereum/rpc/initproc.go, L29:
```go
go handler.ServeCodec(NewJSONCodec(p1), OptionMethodInvocation|OptionSubscriptions)
```
I believe that goroutine is getting killed on the server side so client context is still alive until it times out.

**Comment by canercidam** [comment]
It's also possible to pull `TestAccountMismatch` and `TestInvalidPassword` into `TestCompleteTransaction` now.

**Comment by dshulyak** [comment]
@canercidam thanks for a research, i think you are right. adding default timeout that is used for context to transaction manager and then overwriting it in tests sounds goods. i think that we should even use transaction context for every call, but it is definitely not for this PR.

i will do a review tomorrow probably

File: geth/transactions/txqueue_manager.go [hunk 1]
```diff
@@ -32,6 +32,7 @@ type Manager struct {
 	addrLock          *AddrLocker
 	notify            bool
 	completionTimeout time.Duration
+	ctxTimeout        time.Duration
```
Comment (dshulyak) [inline geth/transactions/txqueue_manager.go]: rpcCallTimeout ?

File: geth/transactions/txqueue_manager_test.go [hunk 2]
```diff
@@ -61,19 +63,53 @@ func (s *TxQueueTestSuite) TearDownTest() {
 	s.client.Close()
 }
 
-func (s *TxQueueTestSuite) setupTransactionPoolAPI(account *common.SelectedExtKey, nonce hexutil.Uint64, gas hexutil.Big, txErr error) {
-	s.txServiceMock.EXPECT().GetTransactionCount(gomock.Any(), account.Address, gethrpc.PendingBlockNumber).Return(&nonce, nil)
-	s.txServiceMock.EXPECT().GasPrice(gomock.Any()).Return(big.NewInt(10), nil)
-	s.txServiceMock.EXPECT().EstimateGas(gomock.Any(), gomock.Any()).Return(&gas, nil)
-	s.txServiceMock.EXPECT().SendRawTransaction(gomock.Any(), gomock.Any()).Return(gethcommon.Hash{}, txErr)
+func (s *TxQueueTestSuite) setupTransactionPoolAPI(tx *common.QueuedTx, config *params.NodeConfig, account *common.SelectedExtKey, nonce *hexutil.Uint64, gas *hexutil.Big, txErr error) {
```
Comment (dshulyak) [inline geth/transactions/txqueue_manager_test.go]: what do you think about preparing tx earlier and passing it to this method? it looks like it will cleanup an interface

File: geth/transactions/txqueue_manager_test.go [hunk 3]
```diff
@@ -83,41 +119,72 @@ func (s *TxQueueTestSuite) TestCompleteTransaction() {
...
 
-	rst := txQueueManager.WaitForTransaction(tx)
-	// Check that error is assigned to the transaction.
-	s.NoError(rst.Error)
-	// Transaction should be already removed from the queue.
-	s.False(txQueueManager.TransactionQueue().Has(tx.ID))
-	s.NoError(WaitClosed(w, time.Second))
-	s.Equal(hash, rst.Hash)
+	for _, testCase := range testCases {
+		s.T().Run(testCase.name, func(t *testing.T) {
```
Comment (dshulyak) [inline geth/transactions/txqueue_manager_test.go:152]: never used it with testify, will it allow to use testify.m the same way as before?

**Review by dshulyak — CHANGES_REQUESTED** [review]
overall looks good, need to verify how it works with testify and added a couple of style comments

File: geth/transactions/txqueue_manager_test.go (hunk 2 above)
Comment (canercidam) [reply geth/transactions/txqueue_manager_test.go]: Hmm, what do you mean by "preparing tx earlier and passing it to this method"? Isn't that already how it works?

Comment (dshulyak) [reply geth/transactions/txqueue_manager_test.go]: i thought  that it is possible to pass types.Transaction instead of `tx *common.QueuedTx, config *params.NodeConfig, account *common.SelectedExtKey, nonce *hexutil.Uint64, gas *hexutil.Big`

File: geth/transactions/txqueue_manager_test.go (hunk 3 above)
Comment (canercidam) [reply geth/transactions/txqueue_manager_test.go:152]: Looks like it doesn't detect that. But IMHO, it's certainly more readable & DRY and all tests run in few seconds anyway.

Comment (dshulyak) [reply geth/transactions/txqueue_manager_test.go:152]: looks good i think

> go test ./geth/transactions/ -v -testify.m=TestCompleteTransaction$
=== RUN   TestTxQueueTestSuite
=== RUN   TestTxQueueTestSuite/TestCompleteTransaction
=== RUN   TestTxQueueTestSuite/TestCompleteTransaction/noGasDef
=== RUN   TestTxQueueTestSuite/TestCompleteTransaction/gasDefined
=== RUN   TestTxQueueTestSuite/TestCompleteTransaction/gasPriceDefined
--- PASS: TestTxQueueTestSuite (0.01s)
    --- PASS: TestTxQueueTestSuite/TestCompleteTransaction (0.01s)
        --- PASS: TestTxQueueTestSuite/TestCompleteTransaction/noGasDef (0.00s)
        --- PASS: TestTxQueueTestSuite/TestCompleteTransaction/gasDefined (0.00s)
        --- PASS: TestTxQueueTestSuite/TestCompleteTransaction/gasPriceDefined (0.00s)
PASS
ok  	github.com/status-im/status-go/geth/transactions	0.055s

File: geth/transactions/txqueue_manager_test.go (hunk 2 above)
Comment (canercidam) [reply geth/transactions/txqueue_manager_test.go]: I see what you mean, I may be able to further reduce the code using `types.Transaction`. I'll look into it.

Comment (canercidam) [reply geth/transactions/txqueue_manager_test.go]: On a second glance, it will just result in moving lines elsewhere because one has to form both `types.Transaction` and `common.QueuedTx` objects in the same case. In other words, if I define a `types.Transaction` object in the test case and pass it to `setupTransactionPoolAPI` instead, that means I can remove forming a new object from `s.rlpEncode` and it doesn't make a difference about how I handle rest of the args such as gas, gas price and nonce.

But it's definitely possible to reduce the amount of args there by having default test values so I'm going to do that instead.

Comment (dshulyak) [reply geth/transactions/txqueue_manager_test.go]: ok, thanks for checking

**Review by dshulyak — APPROVED** [review]
Needs to be rebased ofcourse

**Comment by canercidam** [comment]
@dshulyak Can you please review the last small change?

File: geth/transactions/txqueue_manager_test.go [hunk 4]
```diff
@@ -63,25 +63,31 @@ func (s *TxQueueTestSuite) TearDownTest() {
 	s.client.Close()
 }
 
-func (s *TxQueueTestSuite) setupTransactionPoolAPI(tx *common.QueuedTx, config *params.NodeConfig, account *common.SelectedExtKey, nonce *hexutil.Uint64, gas *hexutil.Big, txErr error) {
+var (
+	testGas      = (*hexutil.Big)(big.NewInt(defaultGas + 1))
+	testGasPrice = (*hexutil.Big)(big.NewInt(10))
+	testNonce    = hexutil.Uint64(10)
```
Comment (dshulyak) [inline geth/transactions/txqueue_manager_test.go]: i will be using non-default nonce here https://github.com/status-im/status-go/pull/538 , so it is not very good idea. but you can leave it if you want. i can rebase

**Review by dshulyak — APPROVED** [review]

File: geth/transactions/txqueue_manager_test.go (hunk 4 above)
Comment (canercidam) [reply geth/transactions/txqueue_manager_test.go]: Oh, okay. I'll just revert changes for nonce then.

**Review by mandrigin — APPROVED** [review]
Looks good 👍

**Comment by canercidam** [comment]
@mandrigin Whoops, it wasn't ready yet. :)

**Comment by canercidam** [comment]
Anyway, doesn't make a big difference. I was going to rollback a change and squash commits. Thanks for your time and efforts! @mandrigin @dshulyak
