### PR TITLE
fix(wallet)_: reduce block range size for `eth_getLogs` request for Sepolia

### LINKED ISSUE #5167: `eth_getLogs` fails on Sepolia for POKT
# Problem

We are using too big block range for POKT in `getLogs` request (500K) which causes failures for POKT and spending limit of Infura.
This was not handled when we switched from Goerli to Sepolia.

It can cause reaching limits per day at RPC providers

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
For POKT (Grove) the limit for block range of `eth_getLogs` call is 100K.
For Infura, according to #3837 the limit for Arbitrum and Optimism is 10K.
For now, we keep 10K for Arbitrum and Optimism to satisfy both providers, reducing 500K for mainnet (Infura) to 100K (POKT) since POKT is our main provider.

TBD: Implement block range for `getLogs` based on provider's capacity.

Closes #5167

### CODE REVIEW

File: services/wallet/common/const.go [hunk 1]
```diff
@@ -14,16 +14,18 @@ const (
...
+	EthereumMainnet    uint64 = 1
+	EthereumGoerli     uint64 = 5
+	EthereumSepolia    uint64 = 11155111
+	OptimismMainnet    uint64 = 10
+	OptimismGoerli     uint64 = 420
+	OptimismSepolia    uint64 = 11155420
+	ArbitrumMainnet    uint64 = 42161
+	ArbitrumGoerli     uint64 = 421613
+	ArbitrumSepolia    uint64 = 421614
+	BinanceChainID     uint64 = 56 // obsolete?
```
Comment (saledjenic) [inline services/wallet/common/const.go:27]: @IvanBelyakoff why did you add this?

**Review by saledjenic — APPROVED** [review]

**Review by Cuteivist — APPROVED** [review]
