### PR TITLE
fix:  Update timestamp when upserting multi tx

### LINKED ISSUE #12500: Dates of transactions are incorrect
# Bug Report

Opened activity tab for account 0x333c5dba8179822056f2289bdede1b53a863f577 (NOT a test network)
While transactions are being loaded, "New transactions" button appears and on clicking it, the transactions appear, but their dates are wrong - seem to be the dates they were discovered by Status app.
Have a look at Optimism scanner for this address: https://optimistic.etherscan.io/address/0x333c5dba8179822056f2289bdede1b53a863f577

There are no transactions dated 20/10/2023
image

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/master/3543/
- Operating System: MacOS 13.5

### PR DESCRIPTION
**Pull request by Cuteivist**
Closes https://github.com/status-im/status-desktop/issues/12500

### CODE REVIEW

File: services/wallet/transfer/transaction.go [hunk 1]
```diff
@@ -188,15 +188,21 @@ func rowsToMultiTransactions(rows *sql.Rows) ([]*MultiTransaction, error) {
 	return multiTransactions, nil
 }
 
+func getMultiTransactionTimestamp(multiTransaction *MultiTransaction) uint64 {
+	if multiTransaction.Timestamp != 0 {
+		return multiTransaction.Timestamp
+	}
+	return uint64(time.Now().Unix())
```
Comment (dlipicar) [inline services/wallet/transfer/transaction.go:195]: is there an expected, valid situation where the Tx shouldn't have a timestamp and we should return Now() instead? If not, perhaps add a log here.

**Review by dlipicar — APPROVED** [review]

File: services/wallet/transfer/transaction.go (hunk 1 above)
Comment (Cuteivist) [reply services/wallet/transfer/transaction.go:195]: Idea here is to check if Timestamp was set. In case it was not, then return current time, like before. 

We don't want the case where the timestamp is 0, because it will point to year 1970. Blockchain didn't exist yet :D
