### PR TITLE
fix(RequestCommunityInfoFromMailserver): Add useDatabase flag to read…

### LINKED ISSUE #2878: RequestCommunityInfoFromMailserver should not read db during community import
# Problem

During community import there is a request to mailserver to fetch recent community description.
However, RequestCommunityInfoFromMailserver first looks for community in database and returns an empty community.

# Implementation

Add flag to RequestCommunityInfoFromMailserver in order to do not check database.

### PR DESCRIPTION
**Pull request by endulab**
Add useDatabase flag to read/not read community info before requesting mailserver.

Fix #2878

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]

**Review by 0x-r4bbit — APPROVED** [review]

File: services/ext/api.go [hunk 1]
```diff
@@ -1032,7 +1032,7 @@ func (api *PublicAPI) EnsVerified(pk, ensName string) error {
 }
 
 func (api *PublicAPI) RequestCommunityInfoFromMailserver(communityID string) (*communities.Community, error) {
-	return api.service.messenger.RequestCommunityInfoFromMailserver(communityID)
+	return api.service.messenger.RequestCommunityInfoFromMailserver(communityID, true)
```
Comment (siddarthkay) [inline services/ext/api.go:1035]: Wouldn't passing `true` here make sure that community info is always checked from local db instead of mailserver?

My assumption is that if a community is created by another device then we would not have the community info in our device local db ? unless we fetch from mailserver? @cammellos @endulab 

Should we perhaps add a parameter in the function to accept this flag and if no flag is provided we then default to true?

Comment (siddarthkay) [reply services/ext/api.go:1035]: I would love to know your thoughts before I make this change in my upcoming PR :)

Comment (endulab) [reply services/ext/api.go:1035]: @siddarthkay 
If we get deeper into the code into communities/persistence.go GetByID() we will see that in case of ErrNoRows nil, nil (community, error) is returned. This means that if useDatabase is true, then db will be checked first. But when there is no such a community in db, then requestCommunityInfoFromMailserver will be executed.
Is it a good approach ?
Can you explain how an additional parameter will help here ?

Comment (siddarthkay) [reply services/ext/api.go:1035]: Hi @endulab  I had not dug deeper into the code and had no idea that `requestCommunityInfoFromMailserver` is executed when community is not found in db.
In this case additional parameter is not needed.

Thanks for explanation and for clarification :)

Comment (siddarthkay) [reply services/ext/api.go:1035]: btw having `requestCommunityInfoFromMailserver` and `RequestCommunityInfoFromMailserver` in the same file is really confusing  😅
