### PR TITLE
Fixing test imports

### LINKED ISSUE #592: Broken tests due to wrong imports
# Problem

Tests are broken due to incorrect imports

# Implementation

Fixing imports, certain problems with that appeared while running vet.

### PR DESCRIPTION
**Pull request by denismakogon**
Includes:
 - correct mock imports
 - fixes for things reported by vet

Closes: #592

A short summary which serves as a squashed-commit message.

A description to understand introduced changes without reading the code.

Important changes:
- [x] Something worth noting for reviewers.

Closes #592

### CODE REVIEW

File: geth/node/utils.go [hunk 1]
```diff
@@ -10,16 +10,16 @@ import (
...
 		signal.Send(signal.Envelope{
 			Type: signal.EventNodeCrashed,
 			Event: signal.NodeCrashEvent{
-				Error: err.Error(),
+				Error: strErr,
 			},
 		})
 
-		common.Fatalf(err) // os.exit(1) is called internally
+		common.Fatalf(ErrNodeRunFailure, r) // os.exit(1) is called internally
```
Comment (mandrigin) [inline geth/node/utils.go:23]: I know it was there. But I really not sure if we should use `common.Fatalf` here. @adambabik @divan what's your opinion?

**Review by mandrigin — APPROVED** [review]
Looks good!

File: geth/node/utils.go (hunk 1 above)
Comment (dshulyak) [reply geth/node/utils.go:23]: @mandrigin i am changing this, it will be reported as a regular error to a caller of status backend

Comment (denismakogon) [reply geth/node/utils.go:23]: So, @dshulyak if you are about to change this there are no problems to rebase to presented changes since the code doesn't really change the interaction interface. AFAIU, there's no particular blockers.

Comment (dshulyak) [reply geth/node/utils.go:23]: it was an answer to a question about fatalf usage. i wasn't implying that these changes are giving me any additional problems

Comment (adambabik) [inline geth/node/utils.go:23]: Shouldn't it be `common.Fatalf(strErr)` in order not to change the logic? I doubt this is tested.

**Review by adambabik — APPROVED** [review]
LGTM overall but left one question.

File: geth/node/utils.go (hunk 1 above)
Comment (denismakogon) [reply geth/node/utils.go:23]: if we can use logrus here which is the better option than `fmt.Fprintf` for writing errors to STDERR we'd have more stable and predictable code.

Meanwhile, it works okay: https://play.golang.org/p/4hU_kWV359C

File: geth/common/utils.go [hunk 2]
```diff
@@ -143,7 +131,7 @@ func Fatalf(reason interface{}, args ...interface{}) {
 	// find out whether error or string has been passed as a reason
 	r := reflect.ValueOf(reason)
 	if r.Kind() == reflect.String {
-		fmt.Fprintf(w, "Fatal Failure: "+reason.(string)+"\n", args) //nolint: gas
+		fmt.Fprintf(w, "Fatal Failure: %v\n%v", reason.(string), args) //nolint: gas
```
Comment (mandrigin) [inline geth/common/utils.go]: One tiny thing that is also not your fault, but it is nice to fix. We probably need to add `\n` after the second `%v`. Otherwise, the output of this log entry will overflow the next one.
