### PR TITLE
fix: test backup settings

### LINKED ISSUE #4863: Flaky test - TestMessengerBackupSuite/TestBackupSettings
```
  messenger_backup_test.go:415: 
          Error Trace:  /../go/src/github.com/status-im/status-go/protocol/messenger_backup_test.go:415
          Error:        Not equal: 
                        expected: "talent"
                        actual  : "bobby"
                        
                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1 +1 @@
                        -talent
                        +bobby
          Test:         TestMessengerBackupSuite/TestBackupSettings
```

could be easily reproduced on latest branch `develop` locally.

### PR DESCRIPTION
**Pull request by qfrank**
Closes #4863

Pls review the changes by commit

relate [PR](https://github.com/status-im/status-go/pull/4850) introduced the test failure

status: ready.

### CODE REVIEW

**Review by igor-sirotin — APPROVED** [review]
Nice catch, thank you!

you sure everything's ok with out `lint-fix`? 😄

**Comment by qfrank** [comment]
> Nice catch, thank you!
> 
> you sure everything's ok with out `lint-fix`? 😄

the green button looks good 🤦‍♂️ @igor-sirotin

File: protocol/messenger_identity.go [hunk 1]
```diff
@@ -106,8 +106,19 @@ func (m *Messenger) SaveSyncDisplayName(displayName string, clock uint64) error
...
-	return m.multiAccounts.SaveAccount(*m.account)
+	preferredNameClock, err := m.settings.GetSettingLastSynced(settings.PreferredName)
+	if err != nil {
+		return err
+	}
+	// When either the display name or preferred name changes, m.account.Name should be updated.
+	// However, a race condition can occur during BackupData, where m.account.Name could be incorrectly updated.
+	// The final value of m.account.Name depending on which backup message(BackedUpProfile/BackedUpSettings) arrives later.
+	// So we should check the clock of the preferred name and only update m.account.Name if it's older than the display name.
+	if preferredNameClock < clock {
```
Comment (saledjenic) [inline protocol/messenger_identity.go:117]: @qfrank this will never happen, cause `preferredNameClock` will be always newer than `clock`. 

The only place where we're calling this function from is `handleBackedUpProfile`. It is called only in case when user is recovering his Status account. In order to start recovering we usually call `StartNodeWithAccount` function which creates Status account and also sets details to `accounts` table with the clock set to the time of recovering which is always newer than the clock that refers to the backed-up profile data.

So, because of this condition, after recovering, when you restart the app we will see 3-words name instead of backed-up display name.

Plase either handle this other way or revert changes made in this function.

**Review by saledjenic — CHANGES_REQUESTED** [review]

File: protocol/messenger_identity.go (hunk 1 above)
Comment (saledjenic) [reply protocol/messenger_identity.go:117]: @qfrank thinking now, one of the quickest things we can do to overcome this and keep the code you've added is to update `preferredNameClock` to `-1` if `ProcessBackedupMessages` in the node config is set to `true`, when `SaveAccountAndStartNodeWithKey` and `StartNodeWithAccountAndInitialConfig` are called.

Comment (qfrank) [reply protocol/messenger_identity.go:117]: oh, sounds good, let me try. @saledjenic

Comment (qfrank) [reply protocol/messenger_identity.go:117]: > @qfrank this will never happen, cause `preferredNameClock` will be always newer than `clock`.
> 
> The only place where we're calling this function from is `handleBackedUpProfile`. It is called only in case when user is recovering his Status account. In order to start recovering we usually call `StartNodeWithAccount` function which creates Status account and also sets details to `accounts` table with the clock set to the time of recovering which is always newer than the clock that refers to the backed-up profile data.
> 
> So, because of this condition, after recovering, when you restart the app we will see 3-words name instead of backed-up display name.
> 
> Plase either handle this other way or revert changes made in this function.

After checking the code, it seems there was a misunderstanding between us. 🙂 My solution looks good

Comment (saledjenic) [reply protocol/messenger_identity.go:117]: Discussed all these with @qfrank offline, so his point in setting the display name as the name in `accounts.sql` if the display name clock is newer than the preferred name clock (preferred name states for selected ens name) comes from our requirement "if a user has registered ens name, it has higher priority over display name".

But I am not sure if that should be the case for profiles recovered from backup.
What if the display name expires in the meantime?

Only for recovered Status profiles, I am more for an option to set the display name and if the user has an ens name registered for his profile he will need to go to the ens management part of the app and register it (in this case we don't need even to backup preferred name).

What do you think about it?

Comment (qfrank) [reply protocol/messenger_identity.go:117]: > What if the display name expires in the meantime?

I think it's okay for the receiver to handle `BackedUpSettings` which contains PreferredName even ens name exprired, if i remember correctly we have a go routine which will check the state of ENS name. It's not friendly that user need to go to ens management part manually to register from user view.  Note: we also support backup ENS names! @saledjenic  cc @igor-sirotin

Comment (igor-sirotin) [reply protocol/messenger_identity.go:117]: > if i remember correctly we have a go routine which will check the state of ENS name. It's not friendly that user need to go to ens management part manually to register from user view

I agree with @qfrank 👍 
If there will be problems about this, we can open a separate issue and discuss it when ENS rework is done. It's planned in a few milestones afaik.

**Review by igor-sirotin — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]
