### PR TITLE
fix(config)_: fix TorrentConfig when loading node config from DB

### LINKED ISSUE #14813: add missing "required" fields to node_config table
# Bug Report

## Description

`KeycardPairingDataFile string validate:"required"` is marked as required in config.go 

But it's not inserted/loaded in node_config.go:

```
insertNodeConfig:
    INSERT OR REPLACE INTO node_config (
        network_id, data_dir, keystore_dir, node_key, no_discovery, rendezvous,
        listen_addr, advertise_addr, name, version, api_modules, tls_enabled,
        max_peers, max_pending_peers, enable_status_service, enable_ntp_sync,
        bridge_enabled, wallet_enabled, local_notifications_enabled,
        browser_enabled, permissions_enabled, mailservers_enabled,
        swarm_enabled, mailserver_registry_address, web3provider_enabled, synthetic_id
    ) 

```
Having a valid config would allow us to avoid infinite crashes like #14643 when an invalid config was written to the database.

## Steps to reproduce
Try adding the following test:

```
func TestConfigValidate(t *testing.T) {
	// GIVEN
	db, stop := setupTestDB(t)
	defer stop()

	tmpdir := t.TempDir()
	nodeConfig, err := params.NewNodeConfig(tmpdir, 1777)

	require.NoError(t, err)
	err = nodeConfig.Validate()
	require.NoError(t, err)
	require.NoError(t, nodecfg.SaveNodeConfig(db, nodeConfig))

	// WHEN
	dbNodeConfig, err := nodecfg.GetNodeConfigFromDB(db)
	require.NoError(t, err)

	// THEN
	err = dbNodeConfig.Validate()
	require.NoError(t, err)
}
```
it fails with
```
Error:      	Received unexpected error:
	Key: 'NodeConfig.KeycardPairingDataFile' Error:Field validation for 'KeycardPairingDataFile' failed on the 'required' tag
```

#### Expected behavior
Node Config in the database should be valid 

#### Actual behavior
Required fields are missing

### PR DESCRIPTION
**Pull request by friofry**
Closes [status-desktop/issues/14813](https://github.com/status-im/status-desktop/issues/14813)

* Repair TorrentConfig when starting the app (`UpdateWithDefaults`)
* Fix TorrentConfig validation condition `func (c *TorrentConfig) Validate`
* Do not save invalid configs in `SaveNodeConfig` (optional)
* Add tests
* Should help existing users who cannot login to the app:
<kbd>

image

</kbd>

## Room for improvement

I found a similar code in the `setDefaultNodeConfig` function that fixes missing values. I wish the whole configuration was encapsulated (ideally behind an interface(s)), with read-only access methods and methods to modify config without corrupting it, and an API to serialise/deserialise. 
It seems there are multiple places with ad-hoc code that patches nodeconfig with default values.
(`UpdateWithDefaults`, `setDefaultNodeConfig`, `OverwriteNodeConfigValues`, `prepareConfig`).

## Related tickets
related to
https://github.com/status-im/status-desktop/issues/14643
https://github.com/status-im/status-desktop/issues/12918

### CODE REVIEW

File: nodecfg/node_config.go [hunk 1]
```diff
@@ -402,6 +402,11 @@ func SaveConfigWithTx(tx *sql.Tx, c *params.NodeConfig) error {
 }
 
 func SaveNodeConfig(db *sql.DB, c *params.NodeConfig) error {
+	// Validate before saving
```
Comment (friofry) [inline nodecfg/node_config.go]: Maybe logging a warning is enough?

File: params/config.go [hunk 2]
```diff
@@ -1124,7 +1137,7 @@ func (c *TorrentConfig) Validate(validate *validator.Validate) error {
 		return err
 	}
 
-	if c.Enabled && c.DataDir == "" || c.TorrentDir == "" {
+	if c.Enabled && (c.DataDir == "" || c.TorrentDir == "") {
```
Comment (friofry) [inline params/config.go:1137]: https://go.dev/ref/spec#Operators
```
Precedence    Operator
    5             *  /  %  <<  >>  &  &^
    4             +  -  |  ^
    3             ==  !=  <  <=  >  >=
    2             &&
    1             ||
```

**Review by jrainville — APPROVED** [review]

**Review by kounkou — APPROVED** [review]
LGTM

File: params/config.go [hunk 3]
```diff
@@ -819,6 +819,19 @@ func (c *NodeConfig) UpdateWithDefaults() error {
 		c.WakuConfig.MinimumPoW = WakuMinimumPoW
 	}
 
+	// Ensure TorrentConfig is valid
+	if c.TorrentConfig.Enabled {
+		if c.TorrentConfig.Port == 0 {
+			c.TorrentConfig.Port = 9025
```
Comment (qfrank) [inline params/config.go]: I would prefer port 0 rather than fixed port, we already have [getTCPandUDPport](https://github.com/status-im/status-go/blob/33ccf784c52e56d98f2928b4618db5490a1e1f95/protocol/communities/manager.go#L755), fixed port could cause port conflict problem some times.

File: params/config.go [hunk 4]
```diff
@@ -819,6 +819,19 @@ func (c *NodeConfig) UpdateWithDefaults() error {
...
+		}
+		if c.TorrentConfig.DataDir == "" {
+			c.TorrentConfig.DataDir = c.DataDir + "/archivedata"
```
Comment (qfrank) [inline params/config.go]: It would be great if can we have the same concat logic between `setDefaultNodeConfig` and `UpdateWithDefaults` and `defaultNodeConfig` etc. Current implementation is not the case

File: params/config.go [hunk 5]
```diff
@@ -819,6 +819,19 @@ func (c *NodeConfig) UpdateWithDefaults() error {
...
+		}
+		if c.TorrentConfig.TorrentDir == "" {
+			c.TorrentConfig.TorrentDir = c.DataDir + "/torrents"
```
Comment (qfrank) [inline params/config.go]: same as above

File: nodecfg/node_config.go [hunk 6]
```diff
@@ -402,6 +402,11 @@ func SaveConfigWithTx(tx *sql.Tx, c *params.NodeConfig) error {
...
+	if err := c.Validate(); err != nil {
```
Comment (qfrank) [inline nodecfg/node_config.go]: 10 test failed after adding `Validate` here, it's ideal if we can add it here without doing a refactor for the history code. FYI, it's been called [here](https://github.com/status-im/status-go/blob/33ccf784c52e56d98f2928b4618db5490a1e1f95/api/geth_backend.go#L1891). WDYT of adding a migration script to fix the broken data? I saw it loaded back [here](https://github.com/status-im/status-go/blob/33ccf784c52e56d98f2928b4618db5490a1e1f95/nodecfg/node_config.go#L672) sounds simpler?

Comment (friofry) [reply nodecfg/node_config.go]: Hi @qfrank 
I've added a migration to fill api_modules with the default value. And also removed this validation from `SaveNodeConfig` as it's already done on startup Please let me know if this looks right

File: params/defaults.go [hunk 7]
```diff
@@ -6,6 +6,9 @@ const (
 	// StatusDatabase path relative to DataDir.
 	StatusDatabase = "status-db"
 
+	ArchivesRelativePath        = "data/archivedata"
```
Comment (friofry) [inline params/defaults.go:9]: I moved these constants to the "params" package, otherwise there will be a circular dependency between api and params

File: params/config.go [hunk 8]
```diff
@@ -819,6 +819,16 @@ func (c *NodeConfig) UpdateWithDefaults() error {
 		c.WakuConfig.MinimumPoW = WakuMinimumPoW
 	}
 
+	// Ensure TorrentConfig is valid
+	if c.TorrentConfig.Enabled {
```
Comment (qfrank) [inline params/config.go:823]: I meant move these code(updating TorrentConfig) into a migration script rather than updating `api_modules` in a script, but we can also not use the migration just like you did(update with default value) here, I feel overkill using migration only for `api_modules`, you could keep the old code relate to `api_modules` here

**Review by qfrank — APPROVED** [review]

File: params/config.go (hunk 8 above)
Comment (friofry) [reply params/config.go:823]: Fixed
