### PR TITLE
fix(communities/manager): use sync.map to fix concurrent map writes err

### LINKED ISSUE #10483: Crash on login with community permissions
# Bug Report

## Description

Experienced by @mprakhov 

Here are the logs: 
[crash.txt](https://github.com/status-im/status-desktop/files/11355039/crash.txt)

The important part seems here:
```
github.com/status-im/status-go/protocol/communities.(*Manager).CheckMemberPermissionsPeriodically(0x1c00265ed80, {0x1c000fbeed0, 0x21, 0x21})
	/Users/mprakhov/Work/status/status-desktop/vendor/status-go/protocol/communities/manager.go:626 +0x2d8
created by github.com/status-im/status-go/protocol.(*Messenger).Start
	/Users/mprakhov/Work/status/status-desktop/vendor/status-go/protocol/messenger.go:751 +0xd6a
```

## Steps to reproduce

Not fully clear.

Most likely, have a community with permissions, and login a couple of times fast.

#### Expected behavior

No crash

#### Actual behavior

Sometimes crashes

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/10483

I wasn't able to properly reproduce the issue, but from the error log, I could deduce that this was the problem. `periodicMemberPermissionsTasks` is a map that is accessed from multiple threads at the same time, so using a `sync.Map` is safer.

logs for reference:
```
fatal error: concurrent map writes

goroutine 1054 [running]:
github.com/status-im/status-go/protocol/communities.(*Manager).CheckMemberPermissionsPeriodically(0x1c00265ed80, {0x1c000fbeed0, 0x21, 0x21})
	/Users/mprakhov/Work/status/status-desktop/vendor/status-go/protocol/communities/manager.go:626 +0x2d8
created by github.com/status-im/status-go/protocol.(*Messenger).Start
	/Users/mprakhov/Work/status/status-desktop/vendor/status-go/protocol/messenger.go:751 +0xd6a
```

@mprakhov can you test this change to see if it fixes your crash?

### CODE REVIEW

File: protocol/communities/manager.go [hunk 1]
```diff
@@ -76,7 +76,7 @@ type Manager struct {
 	walletConfig                   *params.WalletConfig
 	historyArchiveTasksWaitGroup   sync.WaitGroup
 	historyArchiveTasks            map[string]chan struct{}
-	periodicMemberPermissionsTasks map[string]chan struct{}
+	periodicMemberPermissionsTasks sync.Map
```
Comment (0x-r4bbit) [inline protocol/communities/manager.go]: Since we're losing type information here, maybe add a commit behind `sync.Map` that this stores `chan struct{}`?

**Review by 0x-r4bbit — APPROVED** [review]

**Review by mprakhov — APPROVED** [review]
Tested, no crashes is observing any more
