### PR TITLE
fix(health-manager)_: fix nil healthmanager in copied rpc client

### LINKED ISSUE #6462: panic in `healthmanager.Aggregator.Update`
Sentry Issue: [STATUS-GO-V](https://sentry.infra.status.im/organizations/sentry/issues/161/?referrer=github_integration)

```
github.com/status-im/status-go/common/utils.go in LogOnPanic at line 104
github.com/status-im/status-go/healthmanager/aggregator/aggregator.go in (*Aggregator).Update at line 54
github.com/status-im/status-go/healthmanager/providers_health_manager.go in (*ProvidersHealthManager).Update at line 38
github.com/status-im/status-go/rpc/chain/client.go in (*ClientWithFallback).makeCall at line 249
github.com/status-im/status-go/rpc/chain/client.go in (*ClientWithFallback).CallContract at line 627
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go in (*BoundContract).Call at line 189
github.com/status-im/status-go/contracts/community-tokens/ownertoken/OwnerToken.go in (*OwnerTokenCaller).SignerPublicKey at line 551
github.com/status-im/status-go/services/communitytokens/service.go in (*Service).GetSignerPubKey at line 367
github.com/status-im/status-go/services/communitytokens/service.go in (*Service).SafeGetSignerPubKey at line 382
github.com/status-im/status-go/protocol/communities/manager.go in (*Manager).validateCommunity at line 706
github.com/status-im/status-go/protocol/communities/manager.go in (*Manager).runOwnerVerificationLoop.func1 at line 669
```

### PR DESCRIPTION
**Pull request by friofry**
Issue from Sentry: https://sentry.infra.status.im/organizations/sentry/issues/161/events/3db6b31551c5474ea45d2b9069c61a19/?project=7

The identified root cause of the panics was likely related to improper copying in the ClientWithFallback implementation. The Copy() method was not properly copying the providersHealthManager field:

* Fixes Copy method in ClientWithFallback to properly include the providersHealthManager field
* Updates tests to verify nil handling rather than expecting panics

Closes #6462

### CODE REVIEW

File: healthmanager/providers_health_manager.go [hunk 1]
```diff
@@ -32,6 +32,12 @@ func NewProvidersHealthManager(chainID uint64) *ProvidersHealthManager {
 func (p *ProvidersHealthManager) Update(ctx context.Context, callStatuses []rpcstatus.RpcProviderCallStatus) {
```
Comment (saledjenic) [inline healthmanager/providers_health_manager.go]:
```go
func (p *ProvidersHealthManager) doUpdate(callStatuses []rpcstatus.RpcProviderCallStatus) (shouldEmit bool) {
	p.mu.Lock()
	defer p.mu.Unlock()

	// Update the aggregator with the new provider statuses
	for _, rpcCallStatus := range callStatuses {
		providerStatus := rpcstatus.NewRpcProviderStatus(rpcCallStatus)
		p.aggregator.Update(providerStatus)
	}

	newStatus := p.aggregator.GetAggregatedStatus()

	shouldEmit = p.lastStatus == nil || p.lastStatus.Status != newStatus.Status
	return
}

// Update processes a batch of provider call statuses, updates the aggregated status, and emits chain status changes if necessary.
func (p *ProvidersHealthManager) Update(ctx context.Context, callStatuses []rpcstatus.RpcProviderCallStatus) {
	if !p.doUpdate(callStatuses) {
		return
	}

	p.emitChainStatus(ctx)

	p.mu.Lock()
	defer p.mu.Unlock()
	p.lastStatus = &newStatus
}
```

**Review by saledjenic — APPROVED** [review]

File: healthmanager/providers_health_manager.go (hunk 1 above)
Comment (friofry) [reply healthmanager/providers_health_manager.go]: Nice refactoring.
The only one issue: the variable newStatus is only defined within the doUpdate method and goes out of scope when that method returns.
I've adjusted update method

**Review by igor-sirotin — APPROVED** [review]
