### PR TITLE
Fix setting of bootstrap nodes

### LINKED ISSUE #743: Drop boot prefix
Rename all names with `Boot` prefix like `BootClusterConfig` to `ClusterClonfig`.

### PR DESCRIPTION
**Pull request by themue**
Setting has been dropped falsely in #738. Added it again.

Also closes #743

### CODE REVIEW

File: geth/node/node.go [hunk 1]
```diff
@@ -117,6 +117,7 @@ func defaultEmbeddedNodeConfig(config *params.NodeConfig) *node.Config {
 
 	if config.BootClusterConfig.Enabled {
 		nc.P2P.StaticNodes = makeBootstrapNodes(config.BootClusterConfig.BootNodes)
+		nc.P2P.BootstrapNodes = makeBootstrapNodes(config.BootClusterConfig.BootNodes)
```
Comment (dshulyak) [inline geth/node/node.go]: ideally "true" bootnodes should not be added as static nodes, it won't crash a p2p server but it will make server periodically try to connect with bootnode as a regular peer and it won't be able to do so

in prev pr i suggested to load static peers into BootClusterConfig.StaticNodes, but it is fine to merge it as is

**Review by dshulyak — APPROVED** [review]

File: geth/node/node.go (hunk 1 above)
Comment (themue) [reply geth/node/node.go]: Yes, have seen, but they aren't so real static anymore, only in `p2p.Config` naming. We have two different meanings of *boot* in this context. 

I like your idea of separating it, have to find intelligent names.

Comment (dshulyak) [reply geth/node/node.go]: >  but they aren't so real static anymore, only in p2p.Config naming

maybe I misunderstood you but these nodes are called static even in p2p server code, not only config

Comment (themue) [reply geth/node/node.go]: Yes, I only mentioned config because we're assigning it here. But from our perspective the formerly static compiled nodes now can be configured during startup. But yes, adopting the `geth` notation makes sense and I'll change it to `StaticNodes` and `BootstrapNodes`.

Comment (dshulyak) [reply geth/node/node.go]: i meant that they are called static not because they are compiled or configured with config, but because added statically without using discovery

Comment (adambabik) [reply geth/node/node.go]: I suggest doing two additional things in this PR:
1. Change `BootClusterConfig` to `ClusterConfig` to avoid further confusion,
2. Define both `ClusterConfig.StaticNodes` and `ClusterConfig.BootNodes` and assign them accordingly to `P2P` object.

Comment (themue) [reply geth/node/node.go]: Yes, I checked older code and problem starts with filling the `BootNodes` from different sources (the former static file and potential arguments, the latter overwrite the static file). And use it in different places (if enabled then for `BootstrapNodes` and always for `StaticNodes`, here earlier via `addPeer()`, now directly). So a clean separation definitely will help and also `StaticNodes` have to be set even when `BootClusterConfig.Enabled` is false.

**Comment by themue** [comment]
@adambabik @dshulyak CI is pretty happy now. But to me there's one open question. Please take a look at `node.go` line 119.

File: geth/node/node.go [hunk 2]
```diff
@@ -115,8 +115,11 @@ func defaultEmbeddedNodeConfig(config *params.NodeConfig) *node.Config {
 		nc.HTTPPort = config.HTTPPort
 	}
 
-	if config.BootClusterConfig.Enabled {
-		nc.P2P.StaticNodes = makeBootstrapNodes(config.BootClusterConfig.BootNodes)
+	if config.ClusterConfig.Enabled {
+		// TODO(themue) Should static nodes always be set? Had been done via
```
Comment (dshulyak) [inline geth/node/node.go:119]: it is true by default and can be false only if node is standalone, right? so it is ok to leave it as it is
anyway i don't think that anyone uses standalone node

Comment (adambabik) [reply geth/node/node.go:119]: If standalone is used then `ClusterConfig.Enabled` should be `false`. This fragment looks good.

**Review by adambabik — APPROVED** [review]
LGTM
