### PR TITLE
fix_: profile name not displayed on the login page for synced device in the fallback flow

### LINKED ISSUE #21263: Profile name not displayed on the login page for synced device in falback flow
# Bug Report
**Follow up: #21090** 

### Reproduction
1. Device A1 syncs with Device A.
2. Complete the entire fallback flow, but do not confirm pairing on Device A (Device A use Wi-fi, device A1 use mob data).
3. Go to the profile settings on Device A1.
4. Log out of the profile.

#### Expected behavior: 
The profile on Device A1 shows 3 random names. The same name should appear on the login page.

#### Actual behavior:
The profile on Device A1 shows 3 random names. However, no name is displayed on the login page.
йййййй
ццццц

### Additional Information

- Status version: PR build for #21090 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21263

### Summary
This PR resolves the issue of missing profile names on the login page for synced devices using the fallback flow.

- Updated the test TestRestoreAccountAndLogin to ensure the account name is not empty.
- Modified prepareNodeAccount in geth_backend.go to assign the account name from settings if it’s initially empty.

status-mobile PR: https://github.com/status-im/status-mobile/pull/21321

status; ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]
LGTM

File: api/geth_backend.go [hunk 1]
```diff
@@ -1492,6 +1492,10 @@ func (b *GethStatusBackend) prepareNodeAccount(request *requests.CreateAccount,
 		return nil, errors.Wrap(err, "failed to prepare settings")
 	}
 
+	if response.account.Name == "" {
+		response.account.Name = response.settings.Name
```
Comment (ilmotta) [inline api/geth_backend.go:1496]: Just double-checking @Parveshdhull, but are you sure `Name` is the only fallback value we should use? I ask this because in `status-mobile` we had many bugs because of misunderstandings about which name to pick and their order.

In `status-mobile` I think we are prioritizing the `DisplayName` over `Name` if the value isn't blank https://github.com/status-im/status-mobile/blob/b11d3bed780cfb7f3dea8bd7f7bd1780d15200dc/src/status_im/contexts/profile/utils.cljs#L16.

Also here https://github.com/status-im/status-mobile/blob/b11d3bed780cfb7f3dea8bd7f7bd1780d15200dc/src/status_im/subs/contact/utils.cljs#L69

Comment (Parveshdhull) [reply api/geth_backend.go:1496]: Thank you @ilmotta for reviewing the PR. You are right DisplayName takes precedence over Name.

DisplayName is the value provided by the user while creating an account. While the name is just 3 words random name generated from the public key.

https://github.com/status-im/status-go/blob/d794e433476db879f34893a61254bd501abdabb2/api/defaults.go#L67

So in this PR, we are making sure if a user creates a new account with an empty displayName (in case of syncing fallback), at least he/she will have 3 random words as fallback (not as a higher precedence)

Comment (Parveshdhull) [reply api/geth_backend.go:1496]: btw, It will be replaced with DisplayName as soon as syncing complete

Comment (ilmotta) [reply api/geth_backend.go:1496]: Thank you for the explanation. Approving

**Review by ilmotta — APPROVED** [review]

File: api/backend_test.go [hunk 2]
```diff
@@ -1637,7 +1637,6 @@ func TestRestoreAccountAndLogin(t *testing.T) {
 		Mnemonic:    "test test test test test test test test test test test test",
 		FetchBackup: false,
 		CreateAccount: requests.CreateAccount{
-			DisplayName:        "Account1",
```
Comment (igor-sirotin) [inline api/backend_test.go]: Would be nice to keep a test with `DisplayName` as well.
Such case is possible when `FetchBackup` is false, meaning that the user is importing a new seed phrase, which was never a Status account. Then the user is setting the `DisplayName` right away.

**Review by igor-sirotin — APPROVED** [review]

File: api/backend_test.go (hunk 2 above)
Comment (Parveshdhull) [reply api/backend_test.go]: Thank you, created a separate test for testing the fix `TestRestoreAccountAndLoginWithoutDisplayName`

Comment (igor-sirotin) [reply api/backend_test.go]: Thank you!
