### PR TITLE
fix_: Add contact to removeTrustStatus response

### LINKED ISSUE #13619: ID verification cannot be removed
# Bug Report

## Description

After the user has ID verified a contact, this verification cannot be removed. The button is there, it just does not remove it.

## Steps to reproduce

1. Add a contact
2. ID verify that contact
3. Click on the profile of that contact
4. Click on "remove verification" (in three dots menu)
5. Confirm

#### Expected behavior
ID verification is removed
#### Actual behavior
ID verification is not removed
### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/14/
- Operating System: macOS

https://github.com/status-im/status-desktop/assets/155960867/cfab4679-9ae9-4450-a1d3-ee5bc5e9f27c

[app_20240219_103242.log](https://github.com/status-im/status-desktop/files/14329356/app_20240219_103242.log)

### PR DESCRIPTION
**Pull request by friofry**
`removeTrustStatus` resets trust status and verification. The function returns the updated contact.

<s>If a contact was untrusted and then became uknown - the verification is not changed</s>

Important changes:
- Moved logic from status-desktop "contacts/service.nim RemoveTrustStatus"

Closes [#13619](https://github.com/status-im/status-desktop/issues/13619)
Desktop PR: https://github.com/status-im/status-desktop/pull/14308

# future improvements
<s>
I suggest making a ticket for refactoring. The code of RemoveTrustStatus, DeclineContactVerificationRequest, VerifiedUntrustworthy, VerifiedTrusted contain code duplication and non-obvious logic. Ideally, the storage, logic and synchronization parts should be separated.</s>
Implemented in this PR

### CODE REVIEW

File: protocol/messenger_contact_verification.go [hunk 1]
```diff
@@ -723,19 +723,53 @@ func (m *Messenger) MarkAsUntrustworthy(ctx context.Context, contactID string) e
 	return m.SyncTrustedUser(ctx, contactID, verification.TrustStatusUNTRUSTWORTHY, m.dispatchMessage)
 }
 
-func (m *Messenger) RemoveTrustStatus(ctx context.Context, contactID string) error {
+func (m *Messenger) RemoveTrustStatus(ctx context.Context, contactID string) (*MessengerResponse, error) {
+	contact, ok := m.allContacts.Load(contactID)
+	if !ok {
+		return nil, errors.New("Contact not found")
+	}
+	currentTrustStatus := contact.TrustStatus
```
Comment (MishkaRogachev) [inline protocol/messenger_contact_verification.go]: it's a matter of taste, but I would do this:
`dropVerificaationStatus := contact.TrustStatus != verification.TrustStatusUNTRUSTWORTHY`

File: protocol/messenger_contact_verification.go [hunk 2]
```diff
@@ -723,19 +723,53 @@ func (m *Messenger) MarkAsUntrustworthy(ctx context.Context, contactID string) e
...
+	contact.TrustStatus = verification.TrustStatusUNKNOWN
+
+	// drop verification status
+	if currentTrustStatus != verification.TrustStatusUNTRUSTWORTHY {
+		contact.VerificationStatus = VerificationStatusUNVERIFIED
+		contact.LastUpdatedLocally = m.getTimesource().GetCurrentTime()
+	}
+
+	// Save the updated contact
+	err = m.persistence.SaveContact(contact, nil)
```
Comment (MishkaRogachev) [inline protocol/messenger_contact_verification.go]: i suggest to save & sync contact only if you update VerificationStatus and LastUpdatedLocally. And move `SetTrustStatus` and `SyncTrustedUser` to else

**Review by MishkaRogachev — COMMENTED** [review]
Looks nice! Can you please add a corresponding test to `MessengerVerificationRequests`?

**Comment by friofry** [comment]
@MishkaRogachev I'm thinking of doing a little refactoring. Because this code is used many times:

https://github.com/status-im/status-go/pull/5058/commits/dcba4be3eec8cdf6bc4230b97c0851ad18c1e2d3

**Comment by MishkaRogachev** [comment]
> dcba4be

Yeah, that make sense in case for all use cases we need to save and sync contact.

File: protocol/messenger_contact_verification_test.go [hunk 3]
```diff
@@ -494,6 +494,65 @@ func (s *MessengerVerificationRequests) TestUnthrustworthyVerificationRequests()
...
+	// Mark as trusted
+	resp, err = s.m.VerifiedTrusted(context.Background(), &requests.VerifiedTrusted{ID: types.FromHex(verificationRequestID)})
+	s.Require().NoError(err)
+
+	// WHEN
+	resp, err = s.m.RemoveTrustVerificationStatus(context.Background(), theirPk)
+	s.Require().NoError(err)
+
+	// THEN
+	trustStatus, err := s.m.GetTrustStatus(theirPk)
```
Comment (friofry) [inline protocol/messenger_contact_verification_test.go:546]: Not sure if I need to check the verification status on "their" side?

**Comment by friofry** [comment]
> Looks nice! Can you please add a corresponding test to `MessengerVerificationRequests`?

Done ✔️

File: protocol/messenger_contact_verification_test.go (hunk 3 above)
Comment (MishkaRogachev) [reply protocol/messenger_contact_verification_test.go:546]: No, it's local

**Review by MishkaRogachev — APPROVED** [review]
Looks good!

File: protocol/messenger_contact_verification.go (hunk 1 above)
Comment (friofry) [reply protocol/messenger_contact_verification.go]: I've separated the `RemoveTrustStatus` and `RemoveTrustVerificationStatus` calls so we don't have to check if we need to implicitly remove the "verification" status. 

Now "remove untrusted mark" in the UI calls `removeTrustStatus` and 
"remove ID verification" calls "removeTrustVerificationStatus".

**Review by jrainville — APPROVED** [review]
Looks good.

Great job job on your first Status-go PR and first test at the same time :clap:
