### PR TITLE
fix: lost wakuv2 nameserver with `CreateAccountAndLogin`

### LINKED ISSUE #18992: Contact requests are not delivered to receiver [BLOCKER]
**Steps:**

1. User A sends contact request to User B
2. See if User B has received CR

**Actual result:** CR has not been received. 

[UserA_cont_req_sender.zip](https://github.com/status-im/status-mobile/files/14401823/UserA_cont_req_sender.zip)
[UserB_cont_req_receiver.zip](https://github.com/status-im/status-mobile/files/14401824/UserB_cont_req_receiver.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by igor-sirotin**
I moved the `UpdateNodeConfigFleet` call to `login` API endpoint. 
This way it doesn't affect the `CreateAccountAndLogin` flow.

Also modified `TestLoginAccount` test to check that `nameserver` is not lost.

Fixes https://github.com/status-im/status-mobile/issues/18992

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]
Thank you @igor-sirotin and @smohamedjavid for looking into this issue and finding a fix. Changes look good to me.

Created related PR in mobile and started e2e tests to confirm the fix.
https://github.com/status-im/status-mobile/pull/19009 cc: @pavloburykh

File: api/backend_test.go [hunk 1]
```diff
@@ -833,15 +834,28 @@ func TestLoginAccount(t *testing.T) {
...
+		case <-c:
+			break
+		case <-time.After(5 * time.Second):
+			t.FailNow()
+		}
+	}
+
 	_, err := b.CreateAccountAndLogin(createAccountRequest)
 	require.NoError(t, err)
+	require.Equal(t, nameserver, b.config.WakuV2Config.Nameserver)
```
Comment (smohamedjavid) [inline api/backend_test.go:855]: 🙌

File: mobile/status.go [hunk 2]
```diff
@@ -231,7 +231,12 @@ func login(accountData, password, configJSON string) error {
 
 	api.RunAsync(func() error {
 		log.Debug("start a node with account", "key-uid", account.KeyUID)
-		err := statusBackend.StartNodeWithAccount(account, password, &conf)
+		err := statusBackend.UpdateNodeConfigFleet(&conf)
+		if err != nil {
+			return err
+		}
```
Comment (smohamedjavid) [inline mobile/status.go:237]: Mobile doesn't use this method `login`. Instead, it uses the `LoginAccount` method. 
The `LoginAccount` method already uses `UpdateNodeConfigFleet` to update the fleet.

**Review by smohamedjavid — APPROVED** [review]
Thank you for the quick fix @igor-sirotin. 🚀

**Comment by pavloburykh** [comment]
> Created related PR in mobile and started e2e tests to confirm the fix.
> [status-im/status-mobile#19009](https://github.com/status-im/status-mobile/pull/19009) cc: @pavloburykh

Thank you! @igor-sirotin please take a look at the issue here https://github.com/status-im/status-mobile/pull/19009#issuecomment-1966176347

File: mobile/status.go (hunk 2 above)
Comment (igor-sirotin) [reply mobile/status.go:237]: yep, we have an issue to switch desktop to new endpoints: https://github.com/status-im/status-desktop/issues/12977
