### PR TITLE
fix(AddTokenOwners): Move AddTokenOwners from MintTo

### LINKED ISSUE #10161: Track minting transaction
Token holders should not be added to database after airdrop.
First we need to track minting transaction and add to database when transaction is success.

### PR DESCRIPTION
**Pull request by endulab**
Issue #10161

The initial thought was to incorporate transaction system in collectibles service and track airdrop transaction
inside collectibles service. After some discussions it turned out that it is not possible with current design.
The tracking logic is tied to Nim side and we need to do this just like in case of other actions:
1. Send MinTo request to blockchain
2. Track transaction in Nim
3. If transaction is successful update database.

In this pr I moved database function from MinTo into a separated API call.

### CODE REVIEW

File: services/collectibles/api.go [hunk 1]
```diff
@@ -165,3 +165,15 @@ func (api *API) ContractOwner(ctx context.Context, chainID uint64, contractAddre
 	}
 	return owner.String(), nil
 }
+
+func (api *API) AddTokenOwners(ctx context.Context, chainID uint64, contractAddress string, walletAddresses []string, amount int) error {
+	if len(walletAddresses) == 0 {
+		return errors.New("wallet addresses list is empty")
+	}
+	if amount <= 0 {
+		return errors.New("amount is <= 0")
```
Comment (jrainville) [inline services/collectibles/api.go:187]: Since you use those error message twice, can you add them as constants at the top.

**Review by jrainville — APPROVED** [review]

**Review by mprakhov — APPROVED** [review]
LGTM

File: services/collectibles/api.go (hunk 1 above)
Comment (endulab) [reply services/collectibles/api.go:187]: Done

**Review by borismelnik — APPROVED** [review]
