### PR TITLE
Explicitly disable discovery

### LINKED ISSUE #895: Topic pool reads server.Discv5 when node is being stopped
https://travis-ci.org/status-im/status-go/jobs/373936566

```
INFO [05-03|09:55:50] Notification received                    package=status-go/geth/signal            event="{\"type\":\"node.stopped\",\"event\":null}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xba9d1a]
goroutine 688 [running]:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/discv5.(*Network).SearchTopic(0x0, 0x10bd15d, 0x7, 0x0, 0xc422fdb740, 0xc4211ca690)
	/home/travis/gopath/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/discv5/net.go:303 +0x3a
github.com/status-im/status-go/geth/peers.(*TopicPool).StartSearch.func1(0xc421300c80, 0xc4200f5e00, 0xc422fdb740, 0xc4211ca690)
	/home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:323 +0x65
created by github.com/status-im/status-go/geth/peers.(*TopicPool).StartSearch
	/home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:322 +0x332
FAIL	github.com/status-im/status-go/t/e2e/api	20.391s
```

<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/jobs/373936566">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by dshulyak**
Discovery will be disabled in following cases:
- if there are no bootnodes - v5 server will be disabled because there is no point in running it
- if user defined in config NoDiscovery=true this value will be preserved even if we have bootnodes

When statusd is used current behavior is that discovery is disabled by default.
I kept it in this change, but it would be better to change that.

Also closes: https://github.com/status-im/status-go/issues/895

### CODE REVIEW

File: cmd/statusd/main.go [hunk 1]
```diff
@@ -253,7 +253,7 @@ func makeNodeConfig() (*params.NodeConfig, error) {
 		nodeConfig.ClusterConfig.BootNodes = nil
 	}
 
-	nodeConfig.Discovery = *discovery
```
Comment (mandrigin) [inline cmd/statusd/main.go:256]: I'd keep `Discovery()` as a method, that inverts the `NoDiscovery` flag, so we don't have to have double inverse logic ("not no disovery") in many places.

**Review by themue — APPROVED** [review]
LGTM from implementation but agree to Igor. The negotiation feels somehow strange.

File: cmd/statusd/main.go (hunk 1 above)
Comment (dshulyak) [reply cmd/statusd/main.go:256]: isn't it actually 1 place?

Comment (mandrigin) [reply cmd/statusd/main.go:256]: ah, yeah, though it still looks weird :)
anyway, not critical at all

**Review by mandrigin — APPROVED** [review]

**Review by divan — APPROVED** [review]
LGTM
BTW, what's the use case for "no bootnodes"? We shall always try to guarantee that there are some bootnodes in the config, no?

**Review by divan — DISMISSED** [review]
It doesn't build, though. `Discovery` field is used in a few more places.
Here is an output from Travis, in case it'll speed up fix:
```
geth/node/status_node.go:113:5:warning: unused variable or constant invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (varcheck)
geth/node/status_node.go:227:6:warning: unused variable or constant invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (varcheck)
geth/node/status_node.go:113:5:warning: unused struct field invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (structcheck)
geth/node/status_node.go:227:6:warning: unused struct field invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (structcheck)
geth/node/status_node.go:113:5:warning: error return value not checked (invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery) (errcheck)
geth/node/status_node.go:227:6:warning: error return value not checked (invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery) (errcheck)
geth/node/status_node.go:113:5:warning: invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (interfacer)
geth/node/status_node.go:227:6:warning: invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (interfacer)
geth/node/status_node.go:113:5:warning: invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (megacheck)
geth/node/status_node.go:113:5:warning: invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (unconvert)
geth/node/status_node.go:227:6:warning: invalid operation: n.config (variable of type *github.com/status-im/status-go/geth/params.NodeConfig) has no field or method Discovery (unconvert)
```

**Review by adambabik — APPROVED** [review]

**Comment by dshulyak** [comment]
new race

```
WARNING: DATA RACE
Write at 0x00c4203cf3f8 by goroutine 171:
  github.com/status-im/status-go/geth/peers.(*TopicPool).StopSearch()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:420 +0x251
  github.com/status-im/status-go/geth/peers.(*PeerPool).stopDiscovery()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/peerpool.go:137 +0xaf
  github.com/status-im/status-go/geth/peers.(*PeerPool).handleServerPeers()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/peerpool.go:185 +0xac9
  github.com/status-im/status-go/geth/peers.(*PeerPool).Start.func1()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/peerpool.go:106 +0x5d
Previous read at 0x00c4203cf3f8 by goroutine 169:
  github.com/status-im/status-go/geth/peers.(*TopicPool).StartSearch.func1()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:323 +0x66
```

File: geth/peers/topicpool.go [hunk 2]
```diff
@@ -410,14 +410,16 @@ func (t *TopicPool) StopSearch() {
 		return
 	default:
 		log.Debug("stoping search", "topic", t.topic)
+		close(t.quit)
+		t.mu.Lock()
 		if t.fastModeTimeoutCancel != nil {
 			close(t.fastModeTimeoutCancel)
 			t.fastModeTimeoutCancel = nil
 		}
 		close(t.period)
```
Comment (adambabik) [inline geth/peers/topicpool.go]: Should we move this outside of the lock as well?

**Review by adambabik — APPROVED** [review]

**Comment by dshulyak** [comment]
one more 

```
WARNING: DATA RACE
Write at 0x00c42003a7e0 by goroutine 162:
  runtime.closechan()
      /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/chan.go:325 +0x0
  github.com/status-im/status-go/geth/peers.(*TopicPool).StopSearch()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:414 +0x1cb
  github.com/status-im/status-go/geth/peers.(*PeerPool).stopDiscovery()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/peerpool.go:137 +0xb3
  github.com/status-im/status-go/geth/peers.(*PeerPool).handleServerPeers()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/peerpool.go:185 +0xa16
  github.com/status-im/status-go/geth/peers.(*PeerPool).Start.func1()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/peerpool.go:106 +0x5d
Previous read at 0x00c42003a7e0 by goroutine 159:
  runtime.chansend()
      /home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/chan.go:140 +0x0
  github.com/status-im/status-go/geth/peers.(*TopicPool).setSyncMode()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:140 +0x8a
  github.com/status-im/status-go/geth/peers.(*TopicPool).limitFastMode.func1()
      /home/travis/gopath/src/github.com/status-im/status-go/geth/peers/topicpool.go:169 +0x190
```

https://travis-ci.org/status-im/status-go/jobs/377129205

**Comment by dshulyak** [comment]
@adambabik PTL i added 2 wait groups back , because of this https://github.com/status-im/status-go/pull/886#issuecomment-387947789 race

**Comment by adambabik** [comment]
@dshulyak thanks!

@divan all should be good now. Can you please review again?
