### PR TITLE
fix(manager): make both perms satisfied if viewAndPost is satisfied

### LINKED ISSUE #14209: "View and post" permission does not have priority on "view" permissions
# Bug Report

## Description

In the case where both "view and post" and "view" permissions are configured on a channel. If a member meets the requirements for "view and post" permissions but not "view" permissions then the user is shown the chat and is told they must hold tokens that they already have if they want to post.

## Steps to reproduce

1. Set up 2 permissions, "View and post" where USER 1 met the permission criteria and "View" where USER 1 not met the criteria
2. User open channel 

#### Expected behavior

User can view and post

#### Actual behavior

The user can't post

image
image

### Additional Information

- Status desktop version: 2.28.xx and master
- Operating System: macos

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/14209

The condition not right. Unless the requirements were different when it was implemented, it should be that when a view and post permission is respected, it will overwrite the read only permission.

### CODE REVIEW

**Comment by jrainville** [comment]
I ran my new test 1000+ times and it passed
```
jonathan@jonathan-ThinkPad-P15-Gen-2i:~/dev/status-desktop/vendor/status-go$ go test -tags gowaku_skip_migrations,gowaku_no_rln  ./protocol/communities/ -testify.m ^TestCheckChannelPermissions_ViewAndPostPermissionsCombination2$ -count 100 -failfast -timeout 1000s
ok  	github.com/status-im/status-go/protocol/communities	47.915s
jonathan@jonathan-ThinkPad-P15-Gen-2i:~/dev/status-desktop/vendor/status-go$ go test -tags gowaku_skip_migrations,gowaku_no_rln  ./protocol/communities/ -testify.m ^TestCheckChannelPermissions_ViewAndPostPermissionsCombination2$ -count 100 -failfast -timeout 1000s
ok  	github.com/status-im/status-go/protocol/communities	47.791s
jonathan@jonathan-ThinkPad-P15-Gen-2i:~/dev/status-desktop/vendor/status-go$ go test -tags gowaku_skip_migrations,gowaku_no_rln  ./protocol/communities/ -testify.m ^TestCheckChannelPermissions_ViewAndPostPermissionsCombination2$ -count 500 -failfast -timeout 1000s
ok  	github.com/status-im/status-go/protocol/communities	241.843s
jonathan@jonathan-ThinkPad-P15-Gen-2i:~/dev/status-desktop/vendor/status-go$ go test -tags gowaku_skip_migrations,gowaku_no_rln  ./protocol/communities/ -testify.m ^TestCheckChannelPermissions_ViewAndPostPermissionsCombination2$ -count 500 -failfast -timeout 1000s
ok  	github.com/status-im/status-go/protocol/communities	239.297s
jonathan@jonathan-ThinkPad-P15-Gen-2i:~/dev/status-desktop/vendor/status-go$ 
```

File: protocol/communities/manager.go [hunk 1]
```diff
@@ -2870,8 +2870,7 @@ func (m *Manager) checkChannelPermissions(viewOnlyPermissions []*CommunityTokenP
 	}
 	response.ViewOnlyPermissions.Permissions = viewOnlyPermissionsResponse.Permissions
 
-	if (hasViewOnlyPermissions && !viewOnlyPermissionsResponse.Satisfied) ||
-		(hasViewOnlyPermissions && !hasViewAndPostPermissions) {
+	if hasViewOnlyPermissions && !hasViewAndPostPermissions {
```
Comment (osmaczko) [inline protocol/communities/manager.go:2873]: I believe the whole function logic could be simplified to:
```golang
  response.ViewAndPostPermissions.Satisfied = hasViewAndPostPermissions && viewAndPostPermissionsResponse.Satisfied
  response.ViewOnlyPermissions.Satisfied = viewAndPostPermissionsResponse.Satisfied || (hasViewOnlyPermissions && viewOnlyPermissionsResponse.Satisfied)
```

Comment (jrainville) [reply protocol/communities/manager.go:2873]: I think `viewAndPostPermissionsResponse.Satisfied` is `true` if `hasViewAndPostPermissions` is `false`, you know what I mean? So we'd need a more extensive condition. 

There is surely a way to simplify, but I don't feel like messing with it :joy:

**Comment by jrainville** [comment]
@igor-sirotin @MishkaRogachev reminder to review

**Review by MishkaRogachev — APPROVED** [review]
Looks good

File: protocol/communities/manager.go (hunk 1 above)
Comment (igor-sirotin) [reply protocol/communities/manager.go:2873]: I agree that this function needs some love applied, it's quite easy to make a mistake in such logic operations.
But I understand your caution 😄

**Review by igor-sirotin — APPROVED** [review]
The fix LGTM.
But I agree with @osmaczko that the condition could be simplified. I'm afraid there might be more issues inside it right now. It's really impossible to check it with eye.

**Comment by jrainville** [comment]
> The fix LGTM. But I agree with @osmaczko that the condition could be simplified. I'm afraid there might be more issues inside it right now. It's really impossible to check it with eye.

Ok ok, I'll give it a try. I was a bit tired yesterday so I didn't want to give it a try. I still have a couple brain cells today, so I might be ok :joy:

**Comment by jrainville** [comment]
Nvm, I give up. I tried simplifying and thank god we have good tests, because I managed to break like 5 of them with all my different experiments.

The condition looks complex, because the requirements are super complex.

It's really not as simple as `hasViewAndPostPermissions`, then let's just use that. We need to check the ViewAndPostPermission, because it goes over it, but if that ViewAndPost is not satisfied, we still need to check the View permission. It's a mess, but that's because the requirements are not simple.
