### PR TITLE
fix(ImageUnfurler): set title for image links

### LINKED ISSUE #12479: [Link preview] Missing title in image link previews
# Bug Report

## Description
The file name should be presented as the title for image link previews. This is currently missing from the link preview model.

Screenshot 2023-10-19 at 13 13 41

## Steps to reproduce
1. Paste an image URL in the chat input (E.g https://png.pngtree.com/element_our/png/20180928/beautiful-hologram-water-color-frame-png_119551.jpg)
2. Allow the link preview to be loaded
3. Send the message

#### Expected behavior
When the link preview is loaded in the chat input, the file name is presented in the title
After sending the message a link preview is loaded in the message view and the file name is presented in the title
#### Actual behavior
When the link preview is loaded in the chat input, the preview title is empty
After sending the message a link preview is loaded in the message view. The preview title is empty

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/status-im/status-desktop/issues/12479

`ImageUnfurler` is now setting the `Title` field of the previews as the last part of the link.

Design: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-218121&mode=design&t=CE68IwnhoZ2StTc0-4

image

### CODE REVIEW

File: protocol/linkpreview_unfurler_image.go [hunk 1]
```diff
@@ -105,6 +106,7 @@ func (u *ImageUnfurler) Unfurl() (*common.LinkPreview, error) {
 		return preview, fmt.Errorf("could not build data URI url='%s': %w", u.url.String(), err)
 	}
 
+	preview.Title = path.Base(u.url.Path)
```
Comment (ilmotta) [inline protocol/linkpreview_unfurler_image.go:109]: @igor-sirotin, just a question, from the original issue, it says the file name should be used as the title, but here we're using the URL path. It's not the same, but I get that for many URLs the best we can do is get the path.

But taking a look a this example:

https://images.all-free-download.com/images/graphicwebp/gmorning_cat_1_554356.webp

The correct title would be `gmorning_cat_1_554356.webp`, not `images/graphicwebp/gmorning_cat_1_554356.webp` (I'm ignoring the text truncation part for this example.)

Comment (igor-sirotin) [reply protocol/linkpreview_unfurler_image.go:109]: Sure, that's why I take path.Base()
Tested with some long path links, it's working just as you mention it should 🙂

Comment (ilmotta) [reply protocol/linkpreview_unfurler_image.go:109]: Oh I totally missed the `Base` call 🦀 Thanks

**Review by ilmotta — APPROVED** [review]
