### PR TITLE
fix: don't limit peer exchange to dns-discovered peers

### LINKED ISSUE #6915: Expand the peer exchange loop to use more peers
# Description

Currently only DNS-discovered nodes are used for peer exchange:
https://github.com/status-im/status-go/blob/c575471b4c502f4e2d999cb3b3890e1004a1babb/messaging/waku/gowaku.go#L631-L633

Because of this, in test setups, light clients don't discover any other peers.

We should connect to other known peers that support peer exchange as well.

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-go/issues/6915

Attempted to implement a test here: https://github.com/status-im/status-go/pull/6943

### CODE REVIEW

File: messaging/waku/gowaku.go [hunk 1]
```diff
@@ -626,32 +626,15 @@ func (w *Waku) runPeerExchangeLoop() {
...
 			return
 		case <-ticker.C:
-			w.logger.Info("Running peer exchange loop")
-
-			// We select only the nodes discovered via DNS Discovery that support peer exchange
-			// We assume that those peers are running peer exchange according to infra config,
-			// If not, the peer selection process in go-waku will filter them out anyway
-			w.dnsAddressCacheLock.RLock()
-			var peers peer.IDSlice
-			for _, record := range w.dnsAddressCache {
```
Comment (chaitanyaprem) [inline messaging/waku/gowaku.go:636]: wondering if we can keep this logic of adding peers discovered via DNS to peerStore and connect to them. 
This would provide better/more peers to choose from.

Comment (igor-sirotin) [reply messaging/waku/gowaku.go:636]: @chaitanyaprem, wouldn't we have DNS-discovered peers already in the `peerStore`? Or we're not always connecting to them, only use for discovery?

So you want like no matter if we are connected to them or not, we should keep the peer exchange running with them?

Comment (chaitanyaprem) [reply messaging/waku/gowaku.go:636]: > @chaitanyaprem, wouldn't we have DNS-discovered peers already in the `peerStore`? Or we're not always connecting to them, only use for discovery?

Since they were being connected to here, was not sure if they are being added to peerStore somewhere else. If they are being added to peerStore then this can be removed. 



> So you want like no matter if we are connected to them or not, we should keep the peer exchange running with them?

This would be better imo as they would be bootnodes the chance of getting high quality peers is high.

**Review by chaitanyaprem — APPROVED** [review]
LGTM apart from the comment.

File: messaging/waku/gowaku.go (hunk 1 above)
Comment (igor-sirotin) [reply messaging/waku/gowaku.go:636]: ah, indeed. I was sure they we were connecting to them elsewhere, but couldn't find it now.
Thank you, @chaitanyaprem, I will make sure we still connect to them 👍

Comment (igor-sirotin) [reply messaging/waku/gowaku.go:636]: Apparently we do connect to the DNS-discovered nodes, here:
https://github.com/status-im/status-go/blob/cbbbec4b1c618137a75908b8323e5371e8a3ebd7/messaging/waku/gowaku.go#L536-L543 https://github.com/status-im/status-go/blob/cbbbec4b1c618137a75908b8323e5371e8a3ebd7/messaging/waku/gowaku.go#L563-L567

And we duplicate the `enrtree://` in the fleet configuration, for both static connection and Discv5 connection:
https://github.com/status-im/status-go/blob/f176cbac86034fbe5eadf1e77c4483640d1e20f2/params/cluster.go#L79-L85

So. All should be good. We have the fleet `enrtree://` and always connect to all retrieved nodes. So they will not only appear in `dnsAddressCache`, but also in the peer cache itself. So we will always run peer exchange with them.

**Review by osmaczko — APPROVED** [review]
