### PR TITLE
[CHERRY-PICK] fix: handle bridge message edits

### LINKED ISSUE #14044: Bridged message edits in Status do not work
# Bug Report

## Description

With the Bridge, message edits get sent from Status to Discord and vice versa.

When an edit is done on Status, the result on Discord is ok. Example:
image

However, when an edit is made on Discord, the result on Status is just the same message being repeated with the edit. Example:
image

## Steps to reproduce

1. Send a message on Discord on a bridged channel
2. Edit that message
3. The message is there twice in Status now

#### Expected behavior

The message gets edited in Status

#### Actual behavior

The edited message is added as a "normal message"

### Additional Information

- Status desktop version: 2.27

### PR DESCRIPTION
**Pull request by endulab**
[Cherry-picked](https://github.com/status-im/status-go/pull/4983)

[Issue](https://github.com/status-im/status-desktop/issues/14044)

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

File: protocol/message_persistence.go [hunk 1]
```diff
@@ -1551,6 +1551,18 @@ func (db sqlitePersistence) SaveMessages(messages []*common.Message) (err error)
 		}
 
 		if msg.ContentType == protobuf.ChatMessage_BRIDGE_MESSAGE {
+			// check updates first
+			var hasMessage bool
+			hasMessage, err = db.bridgeMessageExists(tx, msg.GetBridgeMessage().MessageID)
+			if err != nil {
+				return
```
Comment (kounkou) [inline protocol/message_persistence.go:1558]: How about we add error log, to be able to instrument code in the future ?

```go
...
log.Errorf("Failed to check if bridge message exists: %v", err)
...
```

File: protocol/message_persistence.go [hunk 2]
```diff
@@ -1551,6 +1551,18 @@ func (db sqlitePersistence) SaveMessages(messages []*common.Message) (err error)
...
+			}
+			if hasMessage {
+				// bridge message exists, this is edit
+				err = db.updateBridgeMessageContent(tx, msg.GetBridgeMessage().MessageID, msg.GetBridgeMessage().Content)
```
Comment (kounkou) [inline protocol/message_persistence.go:1562]: Should we handle this err ?

File: protocol/message_persistence.go [hunk 3]
```diff
@@ -2967,9 +2979,26 @@ func (db sqlitePersistence) findStatusMessageIdsReplies(tx *sql.Tx, bridgeMessag
 	return statusMessageIDs, nil
 }
 
-// Finds status messages id which are replies for bridgeMessageID
-func (db sqlitePersistence) findStatusMessageIdsRepliedTo(tx *sql.Tx, parentMessageID string) (string, error) {
-	rows, err := tx.Query(`SELECT user_messages_id FROM bridge_messages WHERE message_id = ?`, parentMessageID)
+func (db sqlitePersistence) FindStatusMessageIdForBridgeMessageId(messageID string) (string, error) {
```
Comment (kounkou) [inline protocol/message_persistence.go]: Similar comment to above, wouldn't it be better to add some error log. I believe this can help us instrument the code in the future or just help with understanding what's going on in case there are errors. What do you think?

**Review by kounkou — APPROVED** [review]
I posted some comments, but I am not blocking on this as this is a cherry pick

File: protocol/message_persistence.go (hunk 1 above)
Comment (endulab) [reply protocol/message_persistence.go:1558]: Do not worry. This function returns (err error). It means that if we just do "return", the err value will be returned. The error is handled in the caller.

File: protocol/message_persistence.go (hunk 2 above)
Comment (endulab) [reply protocol/message_persistence.go:1562]: ditto

File: protocol/message_persistence.go (hunk 3 above)
Comment (endulab) [reply protocol/message_persistence.go]: ditto
