### PR TITLE
set $GIT_COMMIT for codeclimate uploads

### LINKED ISSUE #5294: Test coverage results are sometimes not delivered to CodeClimate
# Problem

```shell
[2024-06-04T13:47:50.220Z] Error: response from https://api.codeclimate.com/v1/test_reports.
[2024-06-04T13:47:50.220Z] HTTP 422: is invalid
[2024-06-04T13:47:50.220Z] Usage:
[2024-06-04T13:47:50.220Z]   cc-test-reporter after-build [flags]
[2024-06-04T13:47:50.220Z] 
[2024-06-04T13:47:50.220Z] Flags:
[2024-06-04T13:47:50.220Z]   -s, --batch-size int               batch size for source files (default 500)
[2024-06-04T13:47:50.220Z]   -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
[2024-06-04T13:47:50.220Z]   -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov, dotcover]
[2024-06-04T13:47:50.220Z]       --exit-code int                exit code of the test run
[2024-06-04T13:47:50.220Z]   -r, --id string                    reporter identifier (default "****")
[2024-06-04T13:47:50.220Z]       --insecure                     send coverage insecurely (without HTTPS)
[2024-06-04T13:47:50.220Z]   -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/jenkins/workspace/status-go_prs_tests_PR-5256")
[2024-06-04T13:47:50.220Z] 
[2024-06-04T13:47:50.220Z] Global Flags:
[2024-06-04T13:47:50.220Z]   -d, --debug   run in debug mode
[2024-06-04T13:47:50.220Z] 
```

### PR DESCRIPTION
**Pull request by siddarthkay**
When Jenkins creates a build, it can sometimes run the build on a detached HEAD, causing the commit SHA to be different from the SHA of your branch. This will cause issues when reporting test coverage to Code Climate.

Setting `GIT_COMMIT` fixes code climate upload errors.

ref -> https://docs.codeclimate.com/docs/jenkins#jenkins-ci-builds

Closes #5294

### CODE REVIEW

**Comment by siddarthkay** [comment]
`Test report uploaded successfully to Code Climate`

**Review by igor-sirotin — APPROVED** [review]
wow, thank you!
I guess it was difficult to catch with the _sometimes_ in ` it can sometimes run the build on a detached HEAD` 😄

File: _assets/scripts/run_unit_tests.sh [hunk 1]
```diff
@@ -128,7 +128,9 @@ grep -h -v "^mode:" ./**/*.coverage.out >> c.out
 rm -rf ./**/*.coverage.out
 
 if [[ $UNIT_TEST_REPORT_CODECLIMATE == 'true' ]]; then
-	cc-test-reporter after-build --prefix=github.com/status-im/status-go
+  # https://docs.codeclimate.com/docs/jenkins#jenkins-ci-builds
+  GIT_COMMIT=$(git log | grep -m1 -oE '[^ ]+$')
```
Comment (jakubgs) [inline _assets/scripts/run_unit_tests.sh:132]: A comment should include the info itself and not just link, since links can be dead in the future.

>When Jenkins creates a build, it can sometimes run the build on a detached HEAD, causing the commit SHA to be different from the SHA of your branch.

I wonder why our builds would get into this detached head state.
