### PR TITLE
fix(share_urls)_: fix profile URLs containing no data for new accounts

### LINKED ISSUE #18416: Share Profile links contain wrong characters
# Bug Report

## Description

Found by Volo:

> just tried the share profile link for one of my test accounts (see the screenshot to the left), but it doesn't work and gives me this error page (see the screenshot to the right)
My share profile link: https://status.app/u/Ow==#zQ3sheDEbLB7nPEfjko6Z3jq4iZJJ61ovD4WGawS4wrTXsvPS

I asked for me details:

> 1. I'm on this version (2.34.3)
> 2. Just created a brand new Status profile (created it after updating to this latest version - see the screenshot), which gives me this profile share link: https://status.app/u/Ow==#zQ3sheDEbLB7nPEfjko6Z3jq4iZJJ61ovD4WGawS4wrTXsvPS
> 2.1. if it is needed, I can give you my credentials to this empty profile, ping me in DMs
> 3. Just tired to open the share profile link for my work Status App profile (created it back in the day), and all is good: https://status.app/u/CwWACgkKB3ZvbG9faGsD#zQ3shZDfFH8QoUSzTprjc3aG3VGtTPAKp1MKBdhu3frsssjNU
> 4. Just tired to open the share profile link for my personal Status App profile (I restored it recently but way prior to updating to this latest version), and it gives me the same issue with the share profile link as # 2 above

## Steps to reproduce

0. Possibly go on a brand new account
1. Go to your own profile popup
2. Click Share
3. Copy the link

#### Expected behavior

The link should **not** contains `Ow==`

#### Actual behavior

The link contains those bad characters

### Additional Information

- Status desktop version: 2.34.3
- Operating System: Windows

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/18416

The problem is that new accounts now don't have any Display names, so it encodes an empty protobuf and adds that to the URL. 

First, it's useless, it contains nothing. Also, it makes the website unable to decode it. So we just skip the encoded data if there is nothing to decode. The result is a basic URL with just the compressed key.

It still won't find the user on the Website since there is literally no data associated with the user, but at least it's gonna be possible to share it with someone

[fix-share-url.webm](https://github.com/user-attachments/assets/07c7f916-d9dc-4d52-8a91-fe2fdf2572b0)

### CODE REVIEW

File: protocol/messenger_share_urls.go [hunk 1]
```diff
@@ -446,28 +446,31 @@ func (m *Messenger) prepareEncodedUserData(contact *Contact) (string, string, er
...
+			return "", "", err
+		}
 
-	encodedData, err := encodeDataURL(urlData)
-	if err != nil {
-		return "", "", err
+		encodedData, err = encodeDataURL(urlData)
+		if err != nil {
+			return "", "", err
+		}
```
Comment (igor-sirotin) [inline protocol/messenger_share_urls.go]: This can be simplified by just checking the `urlData == ""` here.

```suggestion
	userProto := &protobuf.User{
		DisplayName: contact.DisplayName,
		Description: contact.Bio,
	}

	userData, err := proto.Marshal(userProto)
	if err != nil {
		return "", "", err
	}

	urlDataProto := &protobuf.URLData{
		Content: userData,
	}

	urlData, err := proto.Marshal(urlDataProto)
	if err != nil {
		return "", "", err
	}
	
	if urlData == "" {
	    return "", "", nil
	}

	encodedData, err := encodeDataURL(urlData)
	if err != nil {
		return "", "", err
	}
```

File: protocol/messenger_share_urls.go [hunk 2]
```diff
@@ -446,28 +446,31 @@ func (m *Messenger) prepareEncodedUserData(contact *Contact) (string, string, er
...
-	}
+		urlData, err := proto.Marshal(urlDataProto)
+		if err != nil {
+			return "", "", err
+		}
 
-	encodedData, err := encodeDataURL(urlData)
-	if err != nil {
-		return "", "", err
+		encodedData, err = encodeDataURL(urlData)
```
Comment (igor-sirotin) [inline protocol/messenger_share_urls.go]: To me it doesn't look that we're actually doing something wrong.

1. We get an empty `urlData`, which is ok. 
2. Then when we compress it with `brotli`, we get a single byte `0x3B` (`;`) output
3. Which seem to be valid when compressing an empty array with `brotli`
4. Then we base64-encode it and get `Ow==`

Am I getting it wrong?

cc @jrainville @felicio

Comment (felicio) [reply protocol/messenger_share_urls.go]: Why would you even encode in that case? Also, didn't at least the display name used to be a required field? Did that change recently 🤔?

Comment (igor-sirotin) [reply protocol/messenger_share_urls.go]: > Also, didn't at least the display name used to be a required field? Did that change recently 🤔?

Yup, that changed around February I think. 
There was a decision to make the onboarding as short as possible, so the we only ask to set the display name when the user opens Messenger (the default screen being Wallet).

> Why would you even encode in that case?

Well I guess it's something that we should agree upon.
Both solution will work, but it has to be the same on both platforms.

1. I agree that a format with empty user data makes sense
    e.g. https://status.app/u/#zQ3shRxpB6WqtVBtrDskM3hYZbYVSH19VQ8GfZEAJtj4s2dfQ

2. But personally I'd prefer solution consistency here.
    I.e. no special cases. Even if the user data is empty, still do the compression and encoding.
    That little `Ow==` doesn't really hurt IMO
    e.g. https://status.app/u/Ow==#zQ3sheDEbLB7nPEfjko6Z3jq4iZJJ61ovD4WGawS4wrTXsvPS
    
What do yo think?

cc @felicio @jrainville

Comment (jrainville) [reply protocol/messenger_share_urls.go]: I don't have a strong opinion.

I think it does look cleaner without the `0w==`, but like I said and you noted, it does still work in our case. Only the website would need to be updated.

Let me know what is simpler and better.

Comment (felicio) [reply protocol/messenger_share_urls.go]: I'm for not computing if there's no reason to 🙂.

Comment (igor-sirotin) [reply protocol/messenger_share_urls.go]: Up to you guys

**Comment by jrainville** [comment]
Since I have the fix already ready, let's do the fix here instead of the Website. I cleaned up the code. You can re-review @igor-sirotin @felicio

**Comment by jrainville** [comment]
Oops, one sec, I need to fix some old tests

**Review by igor-sirotin — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]
