### PR TITLE
fix_: cancel ongoing requests when closing the ClientWithFallback

### LINKED ISSUE #6462: panic in `healthmanager.Aggregator.Update`
Sentry Issue: [STATUS-GO-V](https://sentry.infra.status.im/organizations/sentry/issues/161/?referrer=github_integration)

```
github.com/status-im/status-go/common/utils.go in LogOnPanic at line 104
github.com/status-im/status-go/healthmanager/aggregator/aggregator.go in (*Aggregator).Update at line 54
github.com/status-im/status-go/healthmanager/providers_health_manager.go in (*ProvidersHealthManager).Update at line 38
github.com/status-im/status-go/rpc/chain/client.go in (*ClientWithFallback).makeCall at line 249
github.com/status-im/status-go/rpc/chain/client.go in (*ClientWithFallback).CallContract at line 627
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go in (*BoundContract).Call at line 189
github.com/status-im/status-go/contracts/community-tokens/ownertoken/OwnerToken.go in (*OwnerTokenCaller).SignerPublicKey at line 551
github.com/status-im/status-go/services/communitytokens/service.go in (*Service).GetSignerPubKey at line 367
github.com/status-im/status-go/services/communitytokens/service.go in (*Service).SafeGetSignerPubKey at line 382
github.com/status-im/status-go/protocol/communities/manager.go in (*Manager).validateCommunity at line 706
github.com/status-im/status-go/protocol/communities/manager.go in (*Manager).runOwnerVerificationLoop.func1 at line 669
```

### LINKED ISSUE #6525: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
Sentry Issue: [STATUS-GO-W](https://sentry.infra.status.im/organizations/sentry/issues/163/?referrer=github_integration)

```
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/stacktrace.go", line 28, in NewStacktrace
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/interfaces.go", line 393, in (*Event).SetException
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/client.go", line 547, in (*Client).EventFromException
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/client.go", line 492, in (*Client).RecoverWithContext
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/client.go", line 462, in (*Client).Recover
...
(13 additional frame(s) were not displayed)
```

### LINKED ISSUE #6576: [sentry] panic: healthmanager
Sentry Issue: [STATUS-GO-X](https://sentry.infra.status.im/organizations/sentry/issues/165/?referrer=github_integration)

```
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/stacktrace.go", line 28, in NewStacktrace
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/interfaces.go", line 393, in (*Event).SetException
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/client.go", line 547, in (*Client).EventFromException
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/client.go", line 492, in (*Client).RecoverWithContext
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/client.go", line 462, in (*Client).Recover
  File "github.com/status-im/status-go/vendor/github.com/getsentry/sentry-go/hub.go", line 331, in (*Hub).Recover
  File "github.com/status-im/status-go/internal/sentry/sentry.go", line 41, in RecoverError
  File "github.com/status-im/status-go/common/utils.go", line 104, in LogOnPanic
  File "github.com/status-im/status-go/healthmanager/aggregator/aggregator.go", line 54, in (*Aggregator).Update
  File "github.com/status-im/status-go/healthmanager/providers_health_manager.go", line 38, in (*ProvidersHealthManager).Update
  File "github.com/status-im/status-go/rpc/chain/client.go", line 249, in (*ClientWithFallback).makeCall
  File "github.com/status-im/status-go/rpc/chain/client.go", line 458, in (*ClientWithFallback).CodeAt
  File "github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go", line 195, in (*BoundContract).Call
  File "github.com/status-im/status-go/contracts/community-tokens/ownertoken/OwnerToken.go", line 551, in (*OwnerTokenCaller).SignerPublicKey
  File "github.com/status-im/status-go/services/communitytokens/service.go", line 367, in (*Service).GetSignerPubKey
  File "github.com/status-im/status-go/services/communitytokens/service.go", line 382, in (*Service).SafeGetSignerPubKey
  File "github.com/status-im/status-go/protocol/communities/manager.go", line 706, in (*Manager).validateCommunity
  File "github.com/status-im/status-go/protocol/communities/manager.go", line 669, in (*Manager).runOwnerVerificationLoop.func1
```

### PR DESCRIPTION
**Pull request by friofry**
* reproduce the issue when Client is closed, but requests are still going through
* fix the issue 

The code uses three mechanisms to manage client closure:

* Atomic flag: The `closed` provides immediate rejection of new requests once the client is marked as closed. It ensures that `Close()` is called only once
* Signal channel (`done`): When Close() is called, it closes the done channel which signals all ongoing operations to stop gracefully. This context cancellation approach ensures operations that are already in progress terminate properly.
* Wait group (`wg`): The wait group tracks all active operations, allowing `Close()` to wait for them to complete before finalizing the shutdown process.

Closes #6525
Closes https://github.com/status-im/status-go/issues/6576
Closes https://github.com/status-im/status-go/issues/6462

### CODE REVIEW

File: circuitbreaker/circuit_breaker_test.go [hunk 1]
```diff
@@ -647,3 +647,18 @@ func TestCircuitBreaker_ErrorLogging(t *testing.T) {
...
+	// This should panic with nil pointer dereference
+	defer func() {
+		if r := recover(); r == nil {
+			t.Error("Expected panic but got none")
+		}
+	}()
+
+	// Attempt to call addCallStatus on nil pointer, which should cause the panic
+	result.addCallStatus("test-circuit", nil, time.Now())
+}
```
Comment (igor-sirotin) [inline circuitbreaker/circuit_breaker_test.go]: I feel that this test is kinda obvious 🤔 
It's basically testing that `(nil)->foo()` will panic. Of course it will! 😄

File: rpc/chain/client.go [hunk 2]
```diff
@@ -188,6 +202,24 @@ func (c *ClientWithFallback) IsConnected() bool {
 }
 
 func (c *ClientWithFallback) makeCall(ctx context.Context, f MakeCallFunctor) (interface{}, error) {
+	if c.closed.Load() {
+		return nil, errors.New("client is closed")
+	}
+
+	// Create a context that will be cancelled when either the parent context is done or the client is closed
+	ctx, cancel := context.WithCancel(ctx)
```
Comment (igor-sirotin) [inline rpc/chain/client.go:229]: Instead of creating a `done` channel, we should save this `cancel` method to `ClientWithFallback`. And call it in the `Stop` method.

Example here: https://www.notion.so/Code-smell-2-Pass-context-to-functions-cd49904001ca4152be006124e64f5c61?pvs=4#1cb8f96fb65c80b28720dc44a213522a

**Review by igor-sirotin — COMMENTED** [review]
I see many tests, noice!

File: rpc/chain/client.go [hunk 3]
```diff
@@ -80,6 +81,9 @@ type ClientWithFallback struct {
 
 	tag      string // tag for the limiter
 	groupTag string // tag for the limiter group
+
+	done   chan struct{} // channel to signal client closure
```
Comment (dlipicar) [inline rpc/chain/client.go]: hmm I get the feeling `done` and `closed` are doing here what an actual ctx should be doing. If we don't want to manage 2 separate contexts (one global for the whole client, one which comes with the request), there's stuff like this https://github.com/teivah/onecontext that will encapsulate it.

File: circuitbreaker/circuit_breaker_test.go (hunk 1 above)
Comment (friofry) [reply circuitbreaker/circuit_breaker_test.go]: Fixed!
I was trying to get the exact same stack trace as in Sentry and forgot to clean up this test 😓

File: rpc/chain/client.go (hunk 2 above)
Comment (friofry) [reply rpc/chain/client.go:229]: I like this approach and prefer to store `cancel` functions in other types. And I understand that storing a context in a struct breaks the top-down cancel approach.

But here I was not sure how to manage/merge cancel functions for multiple calls. So storing a chan seems like a simpler solution. And it's not an antipattern.

File: rpc/chain/client.go (hunk 3 above)
Comment (friofry) [reply rpc/chain/client.go]: I'm not sure how to use `ctx, cancel := onecontext.Merge(ctx1, ctx2)` in makeCall without having a parent context that was used in the `Start` method of `rpc/client.go`.

OR we can have an extra internal lifetime context to handle spawned gorutines cancellation. But then we need to add this edge case to the codesmells#2

File: rpc/chain/client.go (hunk 2 above)
Comment (igor-sirotin) [reply rpc/chain/client.go:229]: Well... technically `done chan` will not solve it, because a channel has only one receiver 🤷 
So only one goroutine will be stopped

Comment (igor-sirotin) [reply rpc/chain/client.go:229]: Thinking about this... perhaps adding a `WaitGroup` to `makeCall` would be the right solution here. After cancelling all contexts, we should wait for all calls to finish and only then destroy the `ClientWithFallback`.

Comment (friofry) [reply rpc/chain/client.go:229]: > Thinking about this... perhaps adding a `WaitGroup` to `makeCall` would be the right solution here. After cancelling all contexts, we should wait for all calls to finish and only then destroy the `ClientWithFallback`.

Thank you, fixed!

> Well... technically `done chan` will not solve it, because a channel has only one receiver 🤷 So only one goroutine will be stopped

Here is an example with cancel()+chan approach for multiple parallel requests: https://go.dev/play/p/wZqHB0pasYr

**Review by igor-sirotin — APPROVED** [review]
Thanks!

**Review by dlipicar — APPROVED** [review]
Looks good, just privately discussing whether we need to support calling `Start` after calling `Stop`.
