### PR TITLE
fix(manager_archive)_: fix crash caused by nil filter

### LINKED ISSUE #18087: App crashes on startup when Archive Protocol and CHS are enabled
```
* thread #31, name = 'nim_status_clie', stop reason = signal SIGSEGV: invalid address (fault address: 0x40)
  * frame #0: 0x00007ffff1836e5d libstatus.so.0`github.com/status-im/status-go/protocol.(*Messenger).InitHistoryArchiveTasks at messenger_communities.go:3879
    frame #1: 0x00007ffff17e49b7 libstatus.so.0`github.com/status-im/status-go/protocol.(*Messenger).Start.func1 at messenger.go:839
    frame #2: 0x00007fffefd9b701 libstatus.so.0`runtime.goexit.abi0 at asm_amd64.s:169
```

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/18087

### CODE REVIEW

File: protocol/communities/manager_archive.go [hunk 1]
```diff
@@ -234,7 +234,10 @@ func (m *ArchiveManager) GetCommunityChatsFilters(communityID types.HexBytes) (m
 
 	filters := messagingtypes.ChatFilters{}
 	for _, cid := range chatIDs {
-		filters = append(filters, m.messaging.ChatFilterByChatID(cid))
+		filter := m.messaging.ChatFilterByChatID(cid)
+		if filter != nil {
```
Comment (osmaczko) [inline protocol/communities/manager_archive.go:238]: I am wondering whether this is caused by `messaging` facade or it was there before as well. @jrainville would you be able to check?

Comment (jrainville) [reply protocol/communities/manager_archive.go:238]: I tried reproducing the issue before and after your commits and I can't reproduce either way.

I guess my other account had something specific outside of the archive? Sadly, I can't use that same account because of the migrations.

I checked the code changes again and in theory your changes shouldn't have caused it, as you use the same code, just through an adapter.

It also made me realize that maybe this `filter != nil` check should maybe applied to more places?

Comment (jrainville) [reply protocol/communities/manager_archive.go:238]: Also, we should probably cherry-pick this fix to release once merged to avoid crashes

**Review by igor-sirotin — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]

**Comment by jrainville** [comment]
@igor-sirotin @osmaczko please re-review. I updated the PR to guard every place that we use `ChatFilterByChatID`. Better safe than sorry

**Review by igor-sirotin — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]
