### PR TITLE
fix_: retryDnsDiscoveryWithBackoff nil pointer dereference

### LINKED ISSUE #6366: Waku v2 Context Management Vulnerability: Potential Panic Issues Due to Improper Context Handling
```
"error": "runtime error: invalid memory address or nil pointer dereference", "stacktrace": "github.com/status-im/status-go/common.LogOnPanic
\t/go/src/github.com/status-im/status-go/common/utils.go:102
runtime.gopanic
\t/opt/homebrew/Cellar/go@1.22/1.22.8/libexec/src/runtime/panic.go:770
runtime.panicmem
\t/opt/homebrew/Cellar/go@1.22/1.22.8/libexec/src/runtime/panic.go:261
runtime.sigpanic
\t/opt/homebrew/Cellar/go@1.22/1.22.8/libexec/src/runtime/signal_unix.go:881
github.com/status-im/status-go/wakuv2.(*Waku).retryDnsDiscoveryWithBackoff
\t/go/src/github.com/status-im/status-go/wakuv2/waku.go:513
github.com/status-im/status-go/wakuv2.(*Waku).getDiscV5BootstrapNodes.func2.1
\t/go/src/github.com/status-im/status-go/wakuv2waku.go:423"
```

When I tried to run `SyncDeviceSuite`, I found this error. Proberbly relate to `waku.Stop` when logout

### PR DESCRIPTION
**Pull request by qfrank**
This issue is a bit hidden and might impact logout XP, it depends on `dnsDiscover` return err, sometimes the same `addr` `enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.prod.status.nodes.status.im`  works fine, sometimes it returns DNSError i/o timeout. So the addr is not that stable which also caused another test issue before like `test timed out after 5m0s`

Reproduce steps:
- update code to make [dnsDiscover](https://github.com/status-im/status-go/blob/1e1df751c12a91177a88d6f963cc2f9e03af0380/wakuv2waku.go#L422) return err to invoke [retryDnsDiscoveryWithBackoff](https://github.com/status-im/status-go/blob/1e1df751c12a91177a88d6f963cc2f9e03af0380/wakuv2/waku.go#L425)  
- make [dnsDiscover](https://github.com/status-im/status-go/blob/1e1df751c12a91177a88d6f963cc2f9e03af0380/wakuv2/waku.go#L500) return err so that the `for` loop won't break
- add a line `time.Sleep(3*time.Seconds)` before [NewTimer](https://github.com/status-im/status-go/blob/1e1df751c12a91177a88d6f963cc2f9e03af0380/wakuv2/waku.go#L516)
- run test that will invoke `logout` e.g. `TestPairDeclineContactRequest` multi times

Closes #6366

### CODE REVIEW

File: wakuv2/waku.go [hunk 1]
```diff
@@ -514,8 +514,13 @@ func (w *Waku) retryDnsDiscoveryWithBackoff(ctx context.Context, addr string, su
...
 
 		t := time.NewTimer(backoff)
+		c := w.ctx
+		// c might be nil when w.Stop is invoked while this goroutine is running
+		if c == nil {
+			return
+		}
 		select {
-		case <-w.ctx.Done():
+		case <-c.Done():
```
Comment (igor-sirotin) [inline wakuv2/waku.go]: So there still might be a race condition, it's just less probable. The thread could be switched after the `c == nil` check, but before you call `<-c.Done()`. 

I guess it would still work even in this case, because you actually copy the `w.ctx`.
But it's quite a nasty fix I think.

I think we should just add `w.wg.Add(1)` and `w.wg.Done()` to the goroutine here:
https://github.com/status-im/status-go/blob/a4ca18a14f5628f542a70213cfe33baece12ffa2/wakuv2/waku.go#L423-L426

Then `Waku.Stop()` will wait till all goroutines are finihsed:
https://github.com/status-im/status-go/blob/a4ca18a14f5628f542a70213cfe33baece12ffa2/wakuv2/waku.go#L1457

Comment (qfrank) [reply wakuv2/waku.go]: > The thread could be switched after the c == nil check, but before you call <-c.Done().

are you sure? my test result doesn't support your opinion~ 
`c` hold `w.ctx` and combine nil check would make sure we won't get nil access. before the fix, we were trying to access `ctx` via `w.ctx` which would have the chance to get nil. if `c` is nil which means w.Stop get invoked. we can return directly.

> I think we should just add w.wg.Add(1) and w.wg.Done() to the goroutine

yeah, that was my first thought before, but I don't like `wg`, it makes hard to catch the concurrent bug @igor-sirotin

Comment (qfrank) [reply wakuv2/waku.go]:
```golang
package wakuv2

import (
	"context"
	"sync"
	"testing"
	"time"
)

func TestContextCancellationAndNilProtection(t *testing.T) {
	// Create a struct similar to Waku
	type testStruct struct {
		ctx    context.Context
		cancel context.CancelFunc
		wg     sync.WaitGroup
		// Channel to track goroutine behavior
		events chan string
	}

	// Create a new instance with a valid context
	ctx, cancel := context.WithCancel(context.Background())
	s := &testStruct{
		ctx:    ctx,
		cancel: cancel,
		wg:     sync.WaitGroup{},
		events: make(chan string, 10), // Buffered to prevent blocking
	}

	// Start a goroutine that simulates retryDnsDiscoveryWithBackoff
	s.wg.Add(1)
	go func() {
		defer s.wg.Done()
		defer func() {
			if r := recover(); r != nil {
				s.events <- "PANIC: " + r.(error).Error()
			}
		}()

		s.events <- "Goroutine: Started"

		// Simulate some work with backoff
		for i := 0; i < 3; i++ {
			// The protection pattern from retryDnsDiscoveryWithBackoff
			c := s.ctx
			if c == nil {
				s.events <- "Goroutine: Context is nil, exiting safely"
				return
			}

			timer := time.NewTimer(10 * time.Second)

			// This select will exit when context is cancelled
			select {
			case <-c.Done():
				timer.Stop()
				s.events <- "Goroutine: Context cancelled, exiting"
				return
			case <-timer.C:
				s.events <- "Goroutine: Continuing work iteration"
			}
		}

		s.events <- "Goroutine: Completed normally"
	}()

	// Simulate Stop() function behavior
	t.Log("Main: Calling cancel()")
	s.cancel()

	t.Log("Main: Setting ctx and cancel to nil")
	s.ctx = nil
	s.cancel = nil

	t.Log("Main: Waiting for goroutines to complete")
	s.wg.Wait()

	// Close the events channel to read all events
	close(s.events)

	// Output all events
	for event := range s.events {
		t.Log(event)
	}

	// This is a successful test if we reach here without panics
	t.Log("Test completed successfully")
}
```

run `TestContextCancellationAndNilProtection` 100 times, you could see some output like `Goroutine: Context cancelled, exiting` and `Goroutine: Context is nil, exiting safely` , but all the test should get passed. @igor-sirotin

Comment (igor-sirotin) [reply wakuv2/waku.go]: @qfrank in your example this is wrong:
```go
	t.Log("Main: Setting ctx and cancel to nil")
	s.ctx = nil
	s.cancel = nil

	t.Log("Main: Waiting for goroutines to complete")
	s.wg.Wait()
```

We should first `wg.Wait()` and only then `s.ctx = nil`.
This is exactly how we do in `Stop()`:
https://github.com/status-im/status-go/blob/a4ca18a14f5628f542a70213cfe33baece12ffa2/wakuv2/waku.go#L1457-L1460

Comment (igor-sirotin) [reply wakuv2/waku.go]: > are you sure? my test result doesn't support your opinion~

As I said, it would still work even in this case, because you actually copy the `w.ctx` 🙂 

> I don't like `wg`, it makes it hard to catch the concurrent bug

This is the way we do now. There're many goroutines started by `Waku`, and this is the way we ensure all of them are finished before deleting the context and the object.

I don't like it either, this is not the way it should be done.
The core issue here is that `context` must never be stored in a structure. It should only be passed to functions.
We have a guideline about this: [Code smell #2: Pass context to functions](https://www.notion.so/Code-smell-2-Pass-context-to-functions-cd49904001ca4152be006124e64f5c61?pvs=4), but it's not simple to apply to existing code.

Comment (qfrank) [reply wakuv2/waku.go]: > in your example this is wrong:

I did it intentionally, otherwise we won't see "Context is nil, exiting safely"

Thank you for the guideline link. I wanted make it as a quick fix in a short term, it seems make not much sense to follow the guideline given the history code. I have mentioned a refactor to `waku.go`, but got no response from status-go-guild on [discord](https://discord.com/channels/1210237582470807632/1341014758505058325/1344989207692705834). May I ask it here again? WDYT? :) @igor-sirotin

Comment (igor-sirotin) [reply wakuv2/waku.go]: > but got no response from status-go-guild on discord

Pardon, busy times lately. 
Sure any refactoring is supported! 👍 Feel free to take anything, just coordinate your actions with guild members and @plopezlpz before starting 🙂 

> I did it intentionally, otherwise we won't see "Context is nil, exiting safely"

Not sure what you mean then. I thought you're showing this code as an example that this won't work.

What I'm saying here, that instead of applying a workaround that you're making in this PR, we should just use the `waku.wg` here, same as it is done for all other goroutines in this module.

Comment (qfrank) [reply wakuv2/waku.go]: > Not sure what you mean then. I thought you're showing this code as an example that this won't work.

Just wanted to show you the previous fix(copy the w.ctx) will work too.

I changed to use `wg` now if you prefer.

**Review by plopezlpz — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]

File: wakuv2/waku.go (hunk 1 above)
Comment (igor-sirotin) [reply wakuv2/waku.go]: Thanks! 
Sure, the copy was working, I admitted that in the very beginning 🙂
