### PR TITLE
fix encoding of status.app links

### LINKED ISSUE #3713: Compressed url data does not match one from status-web
From https://github.com/status-im/status-go/pull/3665#issuecomment-1618247968

# Problem

URL generated by [status-web](https://github.com/status-im/status-web/blob/main/packages/status-js/src/utils/create-url.test.ts#L41) does not get parsed by status-go implementation. 

Error seems to be inside decodeDataURL, tests fails with err : `brotli: CL_SPACE`

### PR DESCRIPTION
**Pull request by felicio**
> note: this is just a draft for others who worked on go implemtation to take over, feel free to push commits to it if the settings allow otherwise please let me know

- [ ] fix go implementation
- [ ] use same test data as js implementation
- [ ] have tests displaying/asserting full urls (snapshots) too

---

fixes https://github.com/status-im/status-go/pull/3665
relates https://github.com/status-im/status-web/issues/459
relates https://github.com/vacp2p/rfc/pull/602
relates https://github.com/vacp2p/rfc/pull/600
closes https://github.com/status-im/status-go/issues/3713

### CODE REVIEW

**Comment by ghost** [comment]
Hey @felicio, and thank you so much for making your first pull request in status-go! :heart: Please help us make your experience better by filling out this brief questionnaire https://goo.gl/forms/uWqNcVpVz7OIopXg2

File: protocol/messenger_share_urls.go [hunk 1]
```diff
@@ -177,8 +177,14 @@ func (m *Messenger) parseCommunityURLWithData(data string, chatKey string) (*URL
...
 
+	var urlDataProto protobuf.URLData
+	err = proto.Unmarshal(communityData, &urlDataProto)
+	if err != nil {
+		return nil, err
+	}
+
 	var communityProto protobuf.Community
-	err = proto.Unmarshal(communityData, &communityProto)
+	err = proto.Unmarshal(urlDataProto.Content, &communityProto)
```
Comment (felicio) [inline protocol/messenger_share_urls.go]: @borismelnik @MishkaRogachev @jrainville this is to address https://github.com/status-im/status-go/issues/3713. 

Also, I left a note in the description of this PR. Please, could you have someone to take over?

image

Comment (felicio) [reply protocol/messenger_share_urls.go]: Btw, the `protobuf.URLData` wrapper may be redundant. The spec went trough several changes, and if I remember I had it there when I planned for it to be extensible for fields like timestamp for when the url has been encoded or whether it caries content for community, channel or user.

Let me know if you'd prefer dropping it, so we can coordinate the change across the board.

Comment (felicio) [reply protocol/messenger_share_urls.go]: Just to make sure, I opened this thread on decoding but encoding should be changed accordingly too 🙂.

File: protocol/messenger_share_urls_test.go [hunk 2]
```diff
@@ -201,10 +201,16 @@ func (s *MessengerShareUrlsSuite) TestShareCommunityURLWithData() {
...
-	s.Require().NoError(err)
-
-	url := fmt.Sprintf("%s/c/%s#%s", baseShareURL, communityData, signature)
+	// communityData, signature, err := s.m.prepareEncodedCommunityData(community)
+	// s.Require().NoError(err)
+
+	// https://status.app/c/GzAAAETnNgpsRpPBwMzNmQiokxNsTUoRiCDpdc4UDkxk1F7pOu65DV_H8-xat9EQ9g==#zQ3shr9nw5uqkXwZkFXBhSnsqifnj2QKXy4BgbdXrE1RhCSAV
+	// url := fmt.Sprintf("%s/c/%s#%s", baseShareURL, communityData, signature)
+	// note see https://github.com/status-im/status-web/pull/461/files#diff-378ed45ccbd1b990783b9cc2f2ee73430328530f17339176b4fa658f2b6eda08 for source
+	url := "https://status.app/c/iyKACkQKB0Rvb2RsZXMSJ0NvbG9yaW5nIHRoZSB3b3JsZCB3aXRoIGpveSDigKIg4bSXIOKAohiYohsiByMxMzFEMkYqAwEhMwM=#zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11"
```
Comment (MishkaRogachev) [inline protocol/messenger_share_urls_test.go:201]: I suggest to put parsing of ready urls into separate test cases

File: protocol/protobuf/url_data.proto [hunk 3]
```diff
@@ -30,10 +30,3 @@ message URLData {
  // Community, Channel, or User
  bytes content = 1;
```
Comment (MishkaRogachev) [inline protocol/protobuf/url_data.proto:31]: Another suggestion is to avoid second parsing [here](https://github.com/status-im/status-go/pull/3855/files#diff-5ec47bfa4a368489277346631ec15cec1e6460766c38267f77e6db8971a3ba0fR187):
```
message URLData {
optional Community community = 1;
optional Channel channel = 2;
optional User = 3;
```

File: protocol/messenger_share_urls.go (hunk 1 above)
Comment (MishkaRogachev) [reply protocol/messenger_share_urls.go]: Imho, it's better to have only one `unmarshal', but I don't insist on it

**Review by MishkaRogachev — COMMENTED** [review]
Should I wait until this PR is ready, or create another one for the main status-go repo?

File: protocol/messenger_share_urls.go (hunk 1 above)
Comment (felicio) [reply protocol/messenger_share_urls.go]: > Should I wait until this PR is ready, or create another one for the main status-go repo?

@MishkaRogachev this is main status-go repo, isn't?

Also, I left this in the PR's description.

> note: this is just a draft for others who worked on go implemtation to take over, feel free to push commits to it if the settings allow otherwise please let me know

I see you're assigned now, so do as you see fit 🙂, however I think it'd be easiest for you to just push new commits here. Settings should allow it.

image

I just wanted to help you out finding the issue, unblock you and get you started.

File: protocol/messenger_share_urls_test.go (hunk 2 above)
Comment (felicio) [reply protocol/messenger_share_urls_test.go:201]: this change in this file is just in a tmp commit to demo the fix

Comment (felicio) [reply protocol/messenger_share_urls_test.go:201]: ditto https://github.com/status-im/status-go/pull/3855#discussion_r1285708046

File: protocol/messenger_share_urls.go (hunk 1 above)
Comment (MishkaRogachev) [reply protocol/messenger_share_urls.go]: I was a little confused because it's a fork but not a branch. Sure, i will continue this PR here, however i need test data for other url types. Should i take it from [here](https://github.com/status-im/status-web/blob/main/packages/status-js/src/utils/create-url.test.ts)?

Comment (felicio) [reply protocol/messenger_share_urls.go]: From https://github.com/status-im/status-web/pull/461/files#diff-378ed45ccbd1b990783b9cc2f2ee73430328530f17339176b4fa658f2b6eda08 as noted in https://github.com/status-im/status-go/pull/3855/files#diff-cf4c349e70071e2f4c728c2927290dd28ac2ecc338b115fc0997599b6254bed6,

```
// note see https://github.com/status-im/status-web/pull/461/files#diff-378ed45ccbd1b990783b9cc2f2ee73430328530f17339176b4fa658f2b6eda08 for source
url := "https://status.app/c/iyKACkQKB0Rvb2RsZXMSJ0NvbG9yaW5nIHRoZSB3b3JsZCB3aXRoIGpveSDigKIg4bSXIOKAohiYohsiByMxMzFEMkYqAwEhMwM=#zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11"
```

and since it wasn't merged yet.

Comment (felicio) [reply protocol/messenger_share_urls.go]: Just noting that https://github.com/status-im/status-web/pull/461/files#diff-378ed45ccbd1b990783b9cc2f2ee73430328530f17339176b4fa658f2b6eda08 hash been merged so the "test data" is our `main` too for reference.

Comment (MishkaRogachev) [reply protocol/messenger_share_urls.go]: Thanks for pointing that out, i'm will update the PR soon

**Comment by MishkaRogachev** [comment]
@felicio Everything seems to be working. I added the use of urls from your PR to the tests. I'll open the PR in the main repo to get a review

**Comment by felicio** [comment]
> I'll open the PR in the main repo to get a review

@MishkaRogachev this is a main repo, just have this reviewed and merge it.

**Review by jrainville — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]
LGTM 👍
