### PR TITLE
fix(search)_: search now works with Discord import and bridged messages

### LINKED ISSUE #8721: App search doesn't take 3rd party messages into account
Imported discord messages are currently not searched/nonored when using the app's search.

This is because discord message payloads are stored in a separate table.
We need to adjust our search APIs to account for that.

----

#### Steps

1. Import discord history
2. click on search
3. select "anywhere"
4. type part of a message that exists in the imported history

result: no message is found that belongs to the imported history
expected: matching messages from the imported history should appear in the search results

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/8721

Adds the right condition and a test

Ran the test 1000 times:
```
go test -test.count 1000 -run BridgeMessageSuite/TestSearchForDiscordMessages -failfast -timeout 3000s -tags gowaku_skip_migrations,gowaku_no_r
ln
PASS
ok      github.com/status-im/status-go/protocol 299.099s
```

### CODE REVIEW

File: protocol/message_persistence.go [hunk 1]
```diff
@@ -1015,7 +1018,10 @@ func (db sqlitePersistence) AllMessageByChatIDWhichMatchTerm(chatID string, sear
 	query := db.buildMessagesQueryWithAdditionalFields(cursorField, where)
 	rows, err := db.db.Query(
 		query,
-		chatID, searchTerm,
+		chatID,
+		searchTerm,
+		searchTerm,
+		searchTerm,
```
Comment (jrainville) [inline protocol/message_persistence.go:1024]: Please let me know if there is a cleaner way to do this.

File: protocol/message_persistence.go [hunk 2]
```diff
@@ -1072,6 +1078,8 @@ func (db sqlitePersistence) AllMessagesFromChatsAndCommunitiesWhichMatchTerm(com
 	parameters = append(parameters, chatIds...)
 	parameters = append(parameters, communityIds...)
 	parameters = append(parameters, searchTerm)
+	parameters = append(parameters, searchTerm)
+	parameters = append(parameters, searchTerm)
```
Comment (jrainville) [inline protocol/message_persistence.go:1082]: Same here

**Review by endulab — APPROVED** [review]

File: protocol/message_persistence.go (hunk 1 above)
Comment (ilmotta) [reply protocol/message_persistence.go:1024]: The cleaner way shooting at the moon :first_quarter_moon_with_face: would be to build composable queries as data structures with some degree of type-safety, or something like https://github.com/go-jet/jet in Go (not ORM 😄)

**Review by ilmotta — APPROVED** [review]
