### PR TITLE
fix(wallet)_: fix circuit breaker to use health checks for fallback

### LINKED ISSUE #5388: No fault tolerance for fallback providers due to misuse of hystrix
# Problem

hystrix library is used as a fault tolerance solution for blockchain and market providers, but its `Go()` methods `fallback` parameter is misused.

Example in our code:
```
unc (pm *Manager) makeCall(main func() (any, error), fallback func() (any, error)) (any, error) {
	resultChan := make(chan any, 1)
	errChan := hystrix.Go("marketClient", func() error {
		res, err := main() // this function is called mainly
		if err != nil {
			return err
		}
		pm.setIsConnected(true)
		resultChan <- res
		return nil
	}, func(err error) error { // This function is called in case of health issues with main function, but there is no health monitoring for it in hystrix
		if pm.fallback == nil {
			return err
		}

		res, err := fallback()
		if err != nil {
			pm.setIsConnected(false) // In case of single failure of fallback function, we set connection state to false
			return err
		}
		pm.setIsConnected(true)
		resultChan <- res
		return nil
	})
	select {
	case result := <-resultChan:
		return result, nil
	case err := <-errChan:

		return nil, err
	}
}
```
# Implementation

We already have a `circuit_breaker.go` that allows arbitrary fallbacks number. We should improve it to use health monitoring of a fallback function as well and use it in places where it is not used (rpc/chain/client.go, market/market.go). That will reduce annoying "provider up/down" banner switching and increase reliability and fault tolerance of fallback provider.

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
Add tests, fix tests failing under stress due to name clashes
Use CircuitBreaker for blockchain RPC calls.

Changes in CircuitBreaker:
- was no circuit for fallback (worked as dummy fallback with no health checks)
- now a separate circuit for fallback

Changed circuits in Collectibles manager:
- was circuit per chain id
- now circuit per (provider + chain id).

Closes #5388

### CODE REVIEW

File: rpc/chain/client.go [hunk 1]
```diff
@@ -253,319 +242,257 @@ func (c *ClientWithFallback) makeCall(ctx context.Context, main func() ([]any, e
...
-					return err
 				}
 
-				res, err = fallback()
-				if err == nil {
-					resultChan <- CommandResult{res: res}
-					return nil
-				}
+				// Should we handle it differently? Do we allow trying the next provider?
+				// if isVMError(err) {
```
Comment (IvanBelyakoff) [inline rpc/chain/client.go]: Do we need to handle it differently? Why did not we allow to try next provider?

File: circuitbreaker/circuit_breaker.go [hunk 2]
```diff
@@ -54,82 +56,81 @@ type CircuitBreaker struct {
...
-				return result
-			}
+		// Accumulate errors
+		if result.err != nil {
+			result.err = fmt.Errorf("%w, %s.error: %w", result.err, circuitName, err)
+		} else {
+			result.err = fmt.Errorf("%s.error: %w", circuitName, err)
 		}
+		result.res = nil
+		// Lets abuse every provider with the same amount of MaxConcurrentRequests,
```
Comment (IvanBelyakoff) [inline circuitbreaker/circuit_breaker.go:128]: Are you OK with this?

File: rpc/chain/client.go [hunk 3]
```diff
@@ -129,70 +138,50 @@ var propagateErrors = []error{
...
-func NewSimpleClient(mainLimiter *RPCRpsLimiter, main *rpc.Client, chainID uint64) *ClientWithFallback {
-	circuitBreakerCmdName := fmt.Sprintf("ethClient_%d", chainID)
-	hystrix.ConfigureCommand(circuitBreakerCmdName, hystrix.CommandConfig{
+func NewSimpleClient(ethClient EthClient, chainID uint64) *ClientWithFallback {
+	cbConfig := circuitbreaker.Config{
+		CircuitName:           fmt.Sprintf("ethClient_%d", chainID),
 		Timeout:               10000,
 		MaxConcurrentRequests: 100,
-		SleepWindow:           300000,
+		SleepWindow:           30000,
```
Comment (IvanBelyakoff) [inline rpc/chain/client.go]: 5 minutes too long? Should we retry to open circuit in 30 seconds?

File: rpc/chain/client.go [hunk 4]
```diff
@@ -129,70 +138,50 @@ var propagateErrors = []error{
...
 }
 
-func NewClient(mainLimiter *RPCRpsLimiter, main *rpc.Client, fallbackLimiter *RPCRpsLimiter, fallback *rpc.Client, chainID uint64) *ClientWithFallback {
-	circuitBreakerCmdName := fmt.Sprintf("ethClient_%d", chainID)
-	hystrix.ConfigureCommand(circuitBreakerCmdName, hystrix.CommandConfig{
-		Timeout:               20000,
+func NewClient(ethClients []*EthClient, chainID uint64) *ClientWithFallback {
+	cbConfig := circuitbreaker.Config{
+		CircuitName:           fmt.Sprintf("ethClient_%d", chainID),
+		Timeout:               10000,
```
Comment (IvanBelyakoff) [inline rpc/chain/client.go]: What calls can take that long? `getLogs` ? calls to contracts to fetch balances?

For such commands we can use a separate circuit with its own config, benefits:
- we get most failures with `getLogs` command. If we have a separate circuit for it, it wont affect the main circuit health for the rest commands
- we can have a lesser timeout for the rest command so if main provider does not respond, we will switch faster to the fallback

WDYT?

And I suggest to remove toggling connection state for provider due to `getLogs` failure, as it normally just harms leading to provider Up/down banner, which is often misleading (the rest of commands - non-archival requests can likely succeed if we have not reached some other limit)

**Review by IvanBelyakoff — COMMENTED** [review]
Guys I need your feedback on some points I mentioned inline

File: rpc/client.go [hunk 5]
```diff
@@ -109,7 +110,11 @@ func NewClient(client *gethrpc.Client, upstreamChainID uint64, upstream params.U
 		if err != nil {
 			return nil, fmt.Errorf("get RPC limiter: %s", err)
 		}
-		c.upstream = chain.NewSimpleClient(limiter, upstreamClient, upstreamChainID)
+		hostPortUpstream, err := extractHostAndPortFromURL(c.upstreamURL)
```
Comment (alaibe) [inline rpc/client.go:116]: pretty sure upstream is now fully deprecated

File: rpc/chain/client.go (hunk 1 above)
Comment (alaibe) [reply rpc/chain/client.go]: That one is quite import to to keep, we have difficult time to understand the real reason of the error,
in those cases you can retry with any provider, the same error will happens

File: rpc/chain/client.go (hunk 4 above)
Comment (alaibe) [reply rpc/chain/client.go]: Mobile connection?

File: circuitbreaker/circuit_breaker.go (hunk 2 above)
Comment (alaibe) [reply circuitbreaker/circuit_breaker.go:128]: Can u explain more?

File: circuitbreaker/circuit_breaker.go [hunk 6]
```diff
@@ -54,82 +56,81 @@ type CircuitBreaker struct {
 }
 
 func NewCircuitBreaker(config Config) *CircuitBreaker {
+	if config.CircuitName == "" {
+		return nil
```
Comment (saledjenic) [inline circuitbreaker/circuit_breaker.go]: Could we return `error` in this case (cause there is no place where we check if the created instance is nil or not)?

File: circuitbreaker/circuit_breaker.go [hunk 7]
```diff
@@ -54,82 +56,81 @@ type CircuitBreaker struct {
...
+			break
+		}
 
-			// In case of max concurrency, we should delay the execution and stop iterating over fallbacks
-			// No error unwrapping here, so use strings.Contains
-			if strings.Contains(err.Error(), hystrix.ErrMaxConcurrency.Error()) {
-				return result
-			}
+		// Accumulate errors
+		if result.err != nil {
```
Comment (saledjenic) [inline circuitbreaker/circuit_breaker.go:123]: This won't be `true` ever, look at the condition in the line `110`.

File: circuitbreaker/circuit_breaker.go [hunk 8]
```diff
@@ -54,82 +56,81 @@ type CircuitBreaker struct {
...
+			result.err = fmt.Errorf("%w, %s.error: %w", result.err, circuitName, err)
+		} else {
+			result.err = fmt.Errorf("%s.error: %w", circuitName, err)
 		}
+		result.res = nil
```
Comment (saledjenic) [inline circuitbreaker/circuit_breaker.go]: Don't we need to add this line as well `result.err = nil` otherwise we're referring to the error from the previous functor not the last one?

File: services/wallet/collectibles/manager.go [hunk 9]
```diff
@@ -1163,3 +1157,9 @@ func createStatusNotifier(statuses *sync.Map, feed *event.Feed) *connection.Stat
 		feed,
 	)
 }
+
+// Different providers have API keys per chain or per testnet/mainnet.
+// Proper implementation should respect that. For now, the safest solution is to use the provider ID and chain ID as the key.
+func getCircuitName(provider thirdparty.CollectibleProvider, chainID walletCommon.ChainID) string {
+	return provider.ID() + chainID.String()
```
Comment (saledjenic) [inline services/wallet/collectibles/manager.go:1163]: Should we add any delimiter in between, maybe better?
`return fmt.Sprintf("%s-%s", return provider.ID(), chainID.String())`

File: rpc/client.go (hunk 5 above)
Comment (IvanBelyakoff) [reply rpc/client.go:116]: Ok, will remove it. Do we start removing it everywhere whenever we touch the code step by step?

File: circuitbreaker/circuit_breaker.go (hunk 6 above)
Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go]: I gave it a second thought and I will remove CircuitName from config completely. It should be passed with every Functor only, as this satisfies most cases and is less error prone. Thanx for the heads up!

File: circuitbreaker/circuit_breaker.go (hunk 2 above)
Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go:128]: we set MaxConcurrentRequests for CircuitBreaker config. But we have multiple circuits for one command - one circuit for main provider, one for each fallback. This MaxConcurrentRequests is our limitation per circuit. So once we reach it for the main provider we could stop and return or we could forward the rest requests to the next provider.
I will leave it like this for now (works as kind of load balancing). We can change it if that causes any issues

File: services/wallet/collectibles/manager.go (hunk 9 above)
Comment (IvanBelyakoff) [reply services/wallet/collectibles/manager.go:1163]: I can do that. It does not matter much as this is not for human eyes, just a proper ID

File: rpc/chain/client.go (hunk 4 above)
Comment (IvanBelyakoff) [reply rpc/chain/client.go]: But for the rest? disabling connection state switch for getLogs command? A separate circuit for getLogs command? Are you ok with this?

File: rpc/client.go (hunk 5 above)
Comment (alaibe) [reply rpc/client.go:116]: better step by step and confirm with @J-Son89

File: circuitbreaker/circuit_breaker.go (hunk 7 above)
Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go:123]: we have a loop here. when first function fails, we return err from it, which is set to result.err at line 124. Then during next iteration if the function fails, result.err is not nil. I know it works, as it is covered with tests.

File: circuitbreaker/circuit_breaker.go (hunk 8 above)
Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go]: Not sure what you mean, In case for any of the functors err is not nil, result.res is set there and we break before we reach here. So, I think this line is just useless here actually. Thanx, will remove it.

File: services/wallet/collectibles/manager.go (hunk 9 above)
Comment (saledjenic) [reply services/wallet/collectibles/manager.go:1163]: I agree, just thought about it, if I need to print it somewhere, easier for eyes, not a big deal.

Comment (IvanBelyakoff) [reply services/wallet/collectibles/manager.go:1163]: I gave it a second thought and since string concatenations normally a way faster than Sprintf and we use it quite often, and given that this is not for human eyes, I think current implementation is OK

File: circuitbreaker/circuit_breaker.go (hunk 7 above)
Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: What I want to say, you have this code:
```Go
		err := hystrix.DoC(ctx, circuitName, func(ctx context.Context) error {
			res, err := f.exec()
			// Write to result only if success
			if err == nil {
				result = CommandResult{res: res, err: err}
			}
			return err
		}, nil)
```
This means you set `err` of `CommandResult` only when the error is `nil`, which is useless, cause it's nil by default.

Then in the line `124` you have this check `if result.err != nil {` which results in `false`.

Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: Also in the next iteration, you're not dealing with an error from that iteration, but with an error from the previous iteration cause you don't have `result.err = nil` in line `129`, which means if you have many commands you will always have in `result.err` an error from the previous iteration.

File: circuitbreaker/circuit_breaker.go (hunk 8 above)
Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go]: It depends how you implement body in `err := hystrix.DoC(ctx, circuitName, func(ctx context.Context) error {.....`

File: circuitbreaker/circuit_breaker.go (hunk 7 above)
Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: To me, something like this, has the most sense:
```Go
		err := hystrix.DoC(ctx, circuitName, func(ctx context.Context) error {
			res, err := f.exec()
			result = CommandResult{res: res}
			return err
		}, nil)

		if err == nil {
			break
		}
		result.err = fmt.Errorf("%s.error: %w", circuitName, err)
```

Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go:123]: if `err == nil` here:
```
			if err == nil {
				result = CommandResult{res: res, err: err}
			}
```
we break at line 110 and never get to line 124.

But if `err != nil` there, then it is returned. if it is the first function in the list, then we get to line 115, if not (means that first failed and already set result.err to err, and the second fails as well, we get to 113.

Again, this is tested in tests, line 70-72 that all errors are accumulatd:
```
	assert.True(t, errors.Is(result.Error(), hystrix.ErrTimeout))
	assert.True(t, errors.Is(result.Error(), errThirdProvFailed))
	assert.True(t, errors.Is(result.Error(), errThirdProvFailed))
```

Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: Again, it works because of this part, but entire implementation is a bit messy
```Go
		if result.err != nil {
			result.err = fmt.Errorf("%w, %s.error: %w", result.err, circuitName, err)
		} else {
			result.err = fmt.Errorf("%s.error: %w", circuitName, err)
		}
```

Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: For example this is simplified:
```Go
func (cb *CircuitBreaker) Execute(cmd Command) CommandResult {
	var result CommandResult
	ctx := cmd.ctx
	if ctx == nil {
		ctx = context.Background()
	}

	for i := 0; i < len(cmd.functors); i += 1 {
		f := cmd.functors[i]

		circuitName := f.circuitName
		if circuitName == "" {
			circuitName = cb.config.CircuitName
		}
		if hystrix.GetCircuitSettings()[circuitName] == nil {
			hystrix.ConfigureCommand(circuitName, hystrix.CommandConfig{
				Timeout:                cb.config.Timeout,
				MaxConcurrentRequests:  cb.config.MaxConcurrentRequests,
				RequestVolumeThreshold: cb.config.RequestVolumeThreshold,
				SleepWindow:            cb.config.SleepWindow,
				ErrorPercentThreshold:  cb.config.ErrorPercentThreshold,
			})
		}

		err := hystrix.DoC(ctx, circuitName, func(ctx context.Context) error {
			res, err := f.exec()
			result.res = res
			return err
		}, nil)

		if err == nil {
			result.err = nil
			break
		}
		result.err = fmt.Errorf("%w, %s.error: %w", result.err, circuitName, err)
	}

	return result
}
```

Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: Even I am not sure if we want this at all `result.err = fmt.Errorf("%w, %s.error: %w", result.err, circuitName, err)`, it's enough to be just `result.err = err`

Cause in that case we could remove this block entirely:
```
		if err == nil {
			result.err = nil
			break
		}
		result.err = fmt.Errorf("%w, %s.error: %w", result.err, circuitName, err)
```

and have only:
```
result.err = hystrix.DoC(....)
if result.err == nil {
  break
}
```

Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go:123]: Sale, you can run the tests with your implementation and they will fail. Because of one reason - it does not accumulate errors, as I said before. you return only one error. For us it is very important to know why each provider failed when the command failed. This is important to resolve bugs where we face RPC errors from providers. Previously it worked fine, because hystrix accumulated the errors, now since the implementation changed, we dont rely on hystrix "fallback" to accumulate errors, we do it ourselves.

Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: That's not true.
Try to use this https://github.com/status-im/status-go/pull/5457#discussion_r1663925537 and you will see.

Comment (saledjenic) [reply circuitbreaker/circuit_breaker.go:123]: The changes I posted above accumulate errors.
Which test is failing?

Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go:123]: > That's not true. Try to use this [#5457 (comment)](https://github.com/status-im/status-go/pull/5457#discussion_r1663925537) and you will see.

I did, copied, pasted, run, it failed. Now I see you fixed it (because I have the old version in my code). Now it passes.
But the whole story is about instead of:
```
...
if err == nil {
  result = CommandResult{res: res, err: err}
}
...
if err == nil {
    break
}
if result.err != nil {
 	result.err = fmt.Errorf("%w, %s.error: %w", result.err, f.circuitName, err)
} else {
 	result.err = fmt.Errorf("%s.error: %w", f.circuitName, err)
}

```
We have:
```
...
result.res = res
...
if err == nil {
	result.err = nil
	break
}

result.err = fmt.Errorf("%w, %s.error: %w", result.err, f.circuitName, err)
```

I dont think it was worth the time you  and me wasted

Comment (IvanBelyakoff) [reply circuitbreaker/circuit_breaker.go:123]: And btw, if we use only one line, it give the following log in some cases, which just does not look good.
circuit_breaker_test.go:218: %!w(<nil>), CommandCancel_9314320001.error: provider 1 failed

File: rpc/client.go (hunk 5 above)
Comment (IvanBelyakoff) [reply rpc/client.go:116]: Created an issue for this https://github.com/status-im/status-go/issues/5476

**Review by alaibe — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Comment by IvanBelyakoff** [comment]
Code coverage issues:
- changes in chain.Client now make use of a well tested circuit breaker, no changes in logic
- chain.Client itself serves like a wrapper around calls to providers, so it just forwards calls to providers and sets state to connected/disconnected. Covering it with tests is pretty useless for us.
- some tests were not counted because no changes in the tested code
- in fact we have a better coverage now than before this PR, so the number is not really correct

Please force-merge, @cammellos

**Comment by igor-sirotin** [comment]
I'm ok on force-merging
