### PR TITLE
Modify function in contact.go to return contact image if available

### LINKED ISSUE #12331: User profile picture is not shown in PNs
# Bug Report

## Problem 
As a user,  I want to see user picture of my contacts in push notifications.
Currently default icon is shown even if user profile picture is displayed in app.

#### Expected behavior
PN with user profile picture

#### Actual behavior
PN with default user profile icon

### Reproduction

1) User A: open status, add User B to contacts
2) User B: set profile picture
3) User B: send message to User A

### Additional Information

- Status version: 1.15
- Operating System: Android (no preview for messages on IOS at all)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes https://github.com/status-im/status-react/issues/12331

### CODE REVIEW

**Review by rasom — APPROVED** [review]

File: protocol/contact.go [hunk 1]
```diff
@@ -39,6 +44,20 @@ func (c *Contact) CanonicalName() string {
...
+		}
+	}
+
+	if thumbImage, ok := c.Images[thumbnailImageType]; ok {
+		imageBase64, err := thumbImage.GetDataURI()
+		if err == nil {
+			return imageBase64
+		}
+	}
+
```
Comment (Samyoul) [inline protocol/contact.go]: FYI this const already exists.

`"github.com/status-im/status-go/images"`

```suggestion
	if largeImage, ok := c.Images[images.LargeDimName]; ok {
		imageBase64, err := largeImage.GetDataURI()
		if err == nil {
			return imageBase64
		}
	}

	if thumbImage, ok := c.Images[images.SmallDimName]; ok {
		imageBase64, err := thumbImage.GetDataURI()
		if err == nil {
			return imageBase64
		}
	}

```
