### PR TITLE
fix map iteration order

### LINKED ISSUE #2990: Map iteration order
# Problem
After submitted my draft [PR](https://github.com/status-im/status-go/pull/2989#issuecomment-1331855903) , i got error `jenkins/prs/tests — This commit cannot be built` , [error detail is here](https://ci.status.im/blue/rest/organizations/jenkins/pipelines/status-go/pipelines/prs/pipelines/tests/branches/PR-2989/runs/1/nodes/75/steps/82/log/?start=0)

the test `TestLatestMessageByChatID`  fails only some times not every time, the cause is map iteration in function `getMessagesAndCursorsFromScanRows`(protocol/message_persistence.go:2400), we can't rely on iterating over a map in a specific order, the iteration order of maps is also unstable, meaning that it won't necessarily be the same every time you run the program(maps are really messy!) , although we called `SortByClock` in `getMessagesAndCursorsFromScanRows`, what if message.Clock have the same value?

### PR DESCRIPTION
**Pull request by qfrank**
2 solutions to fix #2990  
the first one showed as what this PR does.
the second one: modify test function `TestLatestMessageByChatID`, make sure message.Clock have the right value,
but i prefer the first one :) as we won't fall into the trap easily when writing test code 🤔

Closes #2990

### CODE REVIEW

File: protocol/message_persistence.go [hunk 1]
```diff
@@ -2420,15 +2419,16 @@ func getMessagesAndCursorsFromScanRows(db sqlitePersistence, rows *sql.Rows) ([]
...
 			msg.Payload = getUpdatedChatMessagePayload(discordMessage, message.GetDiscordMessage())
 			messageIdx[message.ID] = msg
 		}
 	}
 
 	var messages common.Messages
-	for _, message := range messageIdx {
-		messages = append(messages, message)
+	for _, messageID := range messageIDs {
+		messages = append(messages, messageIdx[messageID])
```
Comment (0x-r4bbit) [inline protocol/message_persistence.go]: Can you do the same for `getPinnedMessagesAndCursorsFromScanRows` please?

Comment (0x-r4bbit) [reply protocol/message_persistence.go]: And also `getMessagesFromScanRows`

**Review by 0x-r4bbit — CHANGES_REQUESTED** [review]

File: protocol/message_persistence.go (hunk 1 above)
Comment (qfrank) [reply protocol/message_persistence.go]: Sounds good! This will make my PR colorful 😉

File: protocol/message_persistence.go [hunk 2]
```diff
@@ -2420,15 +2419,16 @@ func getMessagesAndCursorsFromScanRows(db sqlitePersistence, rows *sql.Rows) ([]
 		if msg, ok := messageIdx[message.ID]; !ok {
 			messageIdx[message.ID] = &message
 			cursors = append(cursors, cursor)
+			messageIDs = append(messageIDs, message.ID)
```
Comment (Samyoul) [inline protocol/message_persistence.go]: Could we append `message` directly to `var messages common.Messages`? That way the conversion loop is no longer required

Comment (Samyoul) [reply protocol/message_persistence.go]: Something like below:

```go
	var cursors []string
	var messages common.Messages

	messageIdx := make(map[string]*common.Message, 0)

	for rows.Next() {
		// There's a possibility of multiple rows per message if the
		// message has a discordMessage and the discordMessage has multiple
		// attachments
		//
		// Hence, we make sure we're aggregating all attachments on a single
		// common.Message
		var (
			message common.Message
			cursor  string
		)
		if err := db.tableUserMessagesScanAllFields(rows, &message, &cursor); err != nil {
			return nil, nil, err
		}
		if msg, ok := messageIdx[message.ID]; !ok {
			messageIdx[message.ID] = &message
			cursors = append(cursors, cursor)
			message = append(messages, message)
		} else if discordMessage := msg.GetDiscordMessage(); discordMessage != nil {
			msg.Payload = getUpdatedChatMessagePayload(discordMessage, message.GetDiscordMessage())
			messageIdx[message.ID] = msg
		}
	}
	SortByClock(messages)

	return messages, cursors, nil

```

Comment (0x-r4bbit) [reply protocol/message_persistence.go]: I think we can if the update to `messageIdx[message.ID]` in the `else if` case will also update the same item in `messages` (via reference)

File: protocol/message_persistence.go (hunk 1 above)
Comment (qfrank) [reply protocol/message_persistence.go]: also getMessagesAndCursorsFromScanRows? found by searching SortByClock

File: protocol/message_persistence.go [hunk 3]
```diff
@@ -2382,16 +2383,13 @@ func getMessagesFromScanRows(db sqlitePersistence, rows *sql.Rows, withCursor bo
 
 		if msg, ok := messageIdx[message.ID]; !ok {
 			messageIdx[message.ID] = &message
+			messages = append(messages, &message)
 		} else if discordMessage := msg.GetDiscordMessage(); discordMessage != nil {
 			msg.Payload = getUpdatedChatMessagePayload(discordMessage, message.GetDiscordMessage())
 			messageIdx[message.ID] = msg
```
Comment (Samyoul) [inline protocol/message_persistence.go]: The current implementation doesn't update a `message` in `messages`. It overwrites the pointer in `messageIdx[message.ID]`. But what we need to do is update the value of the pointer and not the pointer itself.

I believe the below code would fix that problem

```suggestion
			*messageIdx[message.ID] = *msg
```

Comment (qfrank) [reply protocol/message_persistence.go]: emm.. I think current implementation will update a message in messages? also i think we don't even need the line?
```
messageIdx[message.ID] = msg
```

Comment (0x-r4bbit) [reply protocol/message_persistence.go]: We need that line because otherwise we'll never update the message's payload in case there's multiple rows for that message. That's what I tried pointing out here: https://github.com/status-im/status-go/pull/2991#discussion_r1036038644


Let's play this through and imagine there's 2 rows for this message, so we'll pass through this snippet here twice:
```golang
		if msg, ok := messageIdx[message.ID]; !ok {
			messageIdx[message.ID] = &message
			messages = append(messages, &message)
		} else if discordMessage := msg.GetDiscordMessage(); discordMessage != nil {
			msg.Payload = getUpdatedChatMessagePayload(discordMessage, message.GetDiscordMessage())
			messageIdx[message.ID] = msg
	        }
```

1. In the first round, `messageIdx[message.iD]` doesn't exist, so we end up in that first `if` block and store the message in the map (we store it there, so we can quickly access it in the second row, to update its payload). We then add our `message` to the list of messages to be returned.
2. In the second round, the message now does exists in `messageIdx` so we endup in the `else if` block. We extract the message paylaod from the second row and update the `msg` in our `messageIdx` such that it includes that payload.(This is the part we can not leave out, otherwise we'll return incomplete message data. It's crucial that the `msg` that lives in `messages` gets that same update.

As per @Samyoul 's comment, if we do

```golang
messageIdx[message.ID] = msg
```

In we'll overwrite the pointer in `messagesIdx` for `msg`, which is the same that lives in `messages`!
We want instead update the **value** of the pointer hence:

```golang
messageIdx[message.ID] = *msg
```

This will ensure the message in `messages` will receive that update of the second round.

Hope this makes sense..

Comment (Samyoul) [reply protocol/message_persistence.go]: > emm.. I think current implementation will update a message in messages? also i think we don't even need the line?

@qfrank, I apologise I see that you are correct. `msg` is already a pointer to the active `common.Messenger`

**Sample Code**

```go
type discordMsg struct {
	Data []byte
}
type msge struct {
	ID         string
	Payload    []byte
	DiscordMsg *discordMsg
}

func (m *msge) GetDiscordMessage() *discordMsg {
	return m.DiscordMsg
}

func getUpdatedChatMessagePayload(original, attachment *discordMsg) []byte {
	original.Data = append(original.Data, attachment.Data...)
	return original.Data
}

func Test(t *testing.T) {
	var messages []*msge
	messageIdx := make(map[string]*msge, 0)

	data := []msge{
		{ID: "123"},
		{ID: "234"},
		{ID: "345"},
		{ID: "456", DiscordMsg: &discordMsg{Data: []byte{0xff, 0xfe, 0xfd}}},
		{ID: "456", DiscordMsg: &discordMsg{Data: []byte{0xfc, 0xfb, 0xfa}}},
		{ID: "456", DiscordMsg: &discordMsg{Data: []byte{0xf9, 0xf8, 0xf7}}},
	}

	for i := range data {
		if msg, ok := messageIdx[data[i].ID]; !ok {
			messageIdx[data[i].ID] = &data[i]
			messages = append(messages, &data[i])
		} else if discordMessage := msg.GetDiscordMessage(); discordMessage != nil {
			msg.Payload = getUpdatedChatMessagePayload(discordMessage, data[i].GetDiscordMessage())
		}
	}

	spew.Dump(messageIdx, messages)
}
```

Output
```
(map[string]*server.msge) (len=4) {
 (string) (len=3) "345": (*server.msge)(0xc0005202a0)({
  ID: (string) (len=3) "345",
  Payload: ([]uint8) <nil>,
  DiscordMsg: (*server.discordMsg)(<nil>)
 }),
 (string) (len=3) "456": (*server.msge)(0xc0005202d0)({
  ID: (string) (len=3) "456",
  Payload: ([]uint8) (len=9 cap=16) {
   00000000  ff fe fd fc fb fa f9 f8  f7                       |.........|
  },
  DiscordMsg: (*server.discordMsg)(0xc00050ef18)({
   Data: ([]uint8) (len=9 cap=16) {
    00000000  ff fe fd fc fb fa f9 f8  f7                       |.........|
   }
  })
 }),
 (string) (len=3) "123": (*server.msge)(0xc000520240)({
  ID: (string) (len=3) "123",
  Payload: ([]uint8) <nil>,
  DiscordMsg: (*server.discordMsg)(<nil>)
 }),
 (string) (len=3) "234": (*server.msge)(0xc000520270)({
  ID: (string) (len=3) "234",
  Payload: ([]uint8) <nil>,
  DiscordMsg: (*server.discordMsg)(<nil>)
 })
}
([]*server.msge) (len=4 cap=4) {
 (*server.msge)(0xc000520240)({
  ID: (string) (len=3) "123",
  Payload: ([]uint8) <nil>,
  DiscordMsg: (*server.discordMsg)(<nil>)
 }),
 (*server.msge)(0xc000520270)({
  ID: (string) (len=3) "234",
  Payload: ([]uint8) <nil>,
  DiscordMsg: (*server.discordMsg)(<nil>)
 }),
 (*server.msge)(0xc0005202a0)({
  ID: (string) (len=3) "345",
  Payload: ([]uint8) <nil>,
  DiscordMsg: (*server.discordMsg)(<nil>)
 }),
 (*server.msge)(0xc0005202d0)({
  ID: (string) (len=3) "456",
  Payload: ([]uint8) (len=9 cap=16) {
   00000000  ff fe fd fc fb fa f9 f8  f7                       |.........|
  },
  DiscordMsg: (*server.discordMsg)(0xc00050ef18)({
   Data: ([]uint8) (len=9 cap=16) {
    00000000  ff fe fd fc fb fa f9 f8  f7                       |.........|
   }
  })
 })
}
```

**Review by Samyoul — APPROVED** [review]
Really nice change

**Review by 0x-r4bbit — APPROVED** [review]

File: protocol/message_persistence.go (hunk 3 above)
Comment (0x-r4bbit) [reply protocol/message_persistence.go]: Sorry for the late update here. Yes @qfrank and I have discussed this offline as well.
Thanks @Samyoul for the detailed reproducible!
