### PR TITLE
fix(wallet)_: fixed crash when bridging and chain id not set

### LINKED ISSUE #14438: Crash on bridging Theter
### Description

1. open app
2. try to bridge Tether

Result: app crashes on fetching fees

https://github.com/status-im/status-desktop/assets/82375995/57a203a2-1bc7-4519-9fdc-7459455c9b0b

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
Fixed:

- BonderFee was nil => crash
- ChainID was not set => bridge failed

Closes [14438](https://github.com/status-im/status-desktop/issues/14438)

### CODE REVIEW

**Review by Khushboo-dev-cpp — APPROVED** [review]

File: services/wallet/bridge/bridge.go [hunk 1]
```diff
@@ -109,5 +109,5 @@ type Bridge interface {
 	Send(sendArgs *TransactionBridge, verifiedAccount *account.SelectedExtKey) (types.Hash, error)
 	GetContractAddress(network *params.Network, token *token.Token) *common.Address
 	BuildTransaction(sendArgs *TransactionBridge) (*ethTypes.Transaction, error)
-	BuildTx(network *params.Network, fromAddress common.Address, toAddress common.Address, token *token.Token, amountIn *big.Int) (*ethTypes.Transaction, error)
+	BuildTx(fromNetwork, toNetwork *params.Network, fromAddress common.Address, toAddress common.Address, token *token.Token, amountIn *big.Int, bonderFee *big.Int) (*ethTypes.Transaction, error)
```
Comment (Cuteivist) [inline services/wallet/bridge/bridge.go:112]: It should be _ either names. Personally I prefer _ for unused

**Review by Cuteivist — APPROVED** [review]

File: services/wallet/bridge/bridge.go (hunk 1 above)
Comment (IvanBelyakoff) [reply services/wallet/bridge/bridge.go:112]: Will do that for the implementation of th einterface where those are unused
