### PR TITLE
fix_: Add pending tx for collectibles

### LINKED ISSUE #14450: No activity entry for sent ERC1155 token until refreshed
# Bug Report

## Description

After token is sent, an activity entry for it `Sending` or `Sent` should be visible on Activity tab
## Steps to reproduce

- Send ERC1155 token
- Go to activity tab - no activity entry
- click on some other account on the left panel, click back -> activities - `Sending` entry is there

## User impact
Users not sure if they sent the NFT token or not, they might want to duplicate the transaction. **ERC20 tokens activities are fine**

### Additional Information

- Status desktop version: (8be1453fd01e7897618c6ac814e2a4ecffce44e5)
- Operating System: MacOS 14.1.1

### LINKED ISSUE #15433: Bridge pending transactions are not created
# Bug Report

## Description

Pending transactions for Hop and Celar are not handled. That could create some UI issues.

NOTE that Bridge can only be done on Mainnet. Fix should implement unit testing to cover this scenario.

## Steps to reproduce

* Send Bridge

#### Expected behavior

* Activity list is updated with pending tx
* Pending txis  replaced after tx changes status

#### Actual behavior

* Activity list isn't updated with pending tx
* Pending tx isn't replaced after tx changes status

### Additional Information

- Status desktop version: master

### PR DESCRIPTION
**Pull request by Cuteivist**
Fixes https://github.com/status-im/status-desktop/issues/14450
Fixes https://github.com/status-im/status-desktop/issues/15433

Created pending transaction when sending erc721, erc1155, bridge Celar and Hop

https://github.com/status-im/status-go/assets/11396062/7aed122c-2c59-4e1d-95e6-703b7df7e4b8

### CODE REVIEW

**Comment by IvanBelyakoff** [comment]
@Cuteivist Great job for spotting this! I just think that it is also broken for hop and celer bridges at least as I dont see them using `transactor.sendTransaction` which stores the pending tx in database, or storing it explicitly like you did.

**Review by dlipicar — APPROVED** [review]

File: services/wallet/router/pathprocessor/processor_erc721.go [hunk 1]
```diff
@@ -148,13 +148,17 @@ func (s *ERC721Processor) sendOrBuild(sendArgs *MultipathProcessorTxArgs, signer
...
-
-	tx, err = contract.SafeTransferFrom(txOpts, common.Address(sendArgs.ERC721TransferTx.From),
+	from := common.Address(sendArgs.ERC721TransferTx.From)
+	tx, err = contract.SafeTransferFrom(txOpts, from,
 		sendArgs.ERC721TransferTx.Recipient,
 		sendArgs.ERC721TransferTx.TokenID.ToInt())
 	if err != nil {
 		return tx, statusErrors.CreateErrorResponseFromError(err)
 	}
+	err = s.transactor.StoreAndTrackPendingTx(from, sendArgs.ERC721TransferTx.Symbol, sendArgs.ChainID, sendArgs.ERC721TransferTx.MultiTransactionID, tx)
```
Comment (saledjenic) [inline services/wallet/router/pathprocessor/processor_erc721.go:158]: Could we add the same for hop and celar?

**Review by saledjenic — APPROVED** [review]

File: services/wallet/router/pathprocessor/processor_erc721.go (hunk 1 above)
Comment (Cuteivist) [reply services/wallet/router/pathprocessor/processor_erc721.go:158]: @saledjenic  I added new task for that https://github.com/status-im/status-desktop/issues/15433

It's a little more complicated there additionally we should add Unit test for it, because it cannot be tested manually.
