### PR TITLE
fix default range value for shhext_requestMessages

### LINKED ISSUE #933: Wrong default for upper bound value in RequestHistoricMessages call
If `status-react` calls `shhext_requestMessages` setting the `From` field without setting the `To` one, the query on `leveldb` is performed with the wrong range.

If both `From` and `To` are empty, the range is created in the right way (`24_hours_ago..now`).

If only the `To` is missing, the range is: `0..now`

## Implementation

Set the value of `To` to `time.Now()` by default even if `From` is specified.

### PR DESCRIPTION
**Pull request by gravityblast**
This PR set the default value of `From` and `To` in the  `shhext_requestMessages` call in case only one of the 2 is set.

Closes #933

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
Looks good!

File: services/shhext/api.go [hunk 1]
```diff
@@ -54,10 +54,13 @@ type MessagesRequest struct {
...
 func (r *MessagesRequest) setDefaults(now time.Time) {
 	// set From and To defaults
-	if r.From == 0 && r.To == 0 {
-		r.From = uint32(now.UTC().Add(-24 * time.Hour).Unix())
+	if r.To == 0 {
 		r.To = uint32(now.UTC().Unix())
 	}
+
+	if r.From == 0 {
+		r.From = r.To - 86400 // -24 hours
```
Comment (dshulyak) [inline services/shhext/api.go]: it might be a valid request to receive **all** history for a chat where you just joined

File: services/shhext/api_test.go [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+			&MessagesRequest{From: uint32(1), To: now},
+		},
+		{
+			&MessagesRequest{From: 0, To: yesterday},
+			&MessagesRequest{From: daysAgo(tnow, 2), To: yesterday},
+		},
+	}
+
+	for _, s := range scenarios {
+		require.NotEqual(t, s.expected, s.given)
```
Comment (dshulyak) [inline services/shhext/api_test.go]: use t.Run?

File: services/shhext/api_test.go [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+			&MessagesRequest{From: 1, To: 0},
+			&MessagesRequest{From: uint32(1), To: now},
+		},
+		{
+			&MessagesRequest{From: 0, To: yesterday},
+			&MessagesRequest{From: daysAgo(tnow, 2), To: yesterday},
+		},
+	}
+
+	for _, s := range scenarios {
```
Comment (dshulyak) [inline services/shhext/api_test.go]: use t.Run for each scenario?

File: services/shhext/api.go (hunk 1 above)
Comment (gravityblast) [reply services/shhext/api.go]: @dshulyak you are right, the problem is that I can't understand if `0` is the zero value of that field or manually set to zero. Maybe the client can ask from `1`, or any date far in the past. would it make sense?

Comment (adambabik) [reply services/shhext/api.go]: What's gonna happen if `From` is set to `0`? `To` should not be `0` ever.

File: services/shhext/api_test.go [hunk 4]
```diff
@@ -0,0 +1,42 @@
+package shhext
+
+import (
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestMessagesRequest_setDefaults(t *testing.T) {
```
Comment (adambabik) [inline services/shhext/api_test.go:11]: There is already a similar test called `TestRequestMessagesDefaults`. I think it can be removed and we can keep this one.

**Comment by gravityblast** [comment]
@dshulyak updated to use `t.Run`

**Review by adambabik — CHANGES_REQUESTED** [review]

File: services/shhext/api.go (hunk 1 above)
Comment (gravityblast) [reply services/shhext/api.go]: >What's gonna happen if From is set to 0? To should not be 0 ever.

@adambabik if `From` is set to `0`, it's calculated to 24 hours before `To`.
If `From` is `0`, then it's set to `time.Now()`

The problem is that if  only the `To` is specified, and it's 1, then `From` can't be `1 - 24.hours`

File: services/shhext/api_test.go (hunk 4 above)
Comment (gravityblast) [reply services/shhext/api_test.go:11]: > What's gonna happen if From is set to 0? To should not be 0 ever.
`To` is never `0`. If it's `!= 0` in the previous `if` is fine, otherwise is set to `0`.
```
if r.To == 0 {
	r.To = uint32(now.UTC().Unix())
}
```

If `From` is 0, then it's `To - 24 hours`. If the result is less then `0` then it should just be `0`. But this last part needs to be fixed

Comment (adambabik) [reply services/shhext/api_test.go:11]: Ok, that sounds good. In theory, we could allow `From` to be `0` as we will allow it to be `1` but this approach should work better as we don't unnecessary process all requests if someone sends a request without `To` and `From` which is likely.

**Comment by gravityblast** [comment]
@adambabik last commit should check the last case

**Review by adambabik — APPROVED** [review]
LGTM

One more concern, what's gonna happen if `From` is greater than `To` but both are not zeros? Won't MailServer panic? Is it validated later?

**Comment by gravityblast** [comment]
@adambabik it looks like it's still a valid range, like it's doing now with range `From..0`, which is the opposite. 
After merging I can investigate and open an issue if it's needed

**Comment by adambabik** [comment]
@pilu Oh, you may be right. Interesting if LevelDB supports iterating in both directions. I agree we can handle this in another PR.

**Comment by adambabik** [comment]
@pilu we can take care of this when working on this issue https://github.com/status-im/status-go/issues/937.
