### PR TITLE
fix(wallet)_: Handle balance fetching errors & fallback to cached values

### LINKED ISSUE #15767: [Wallet]: `Retry now` button causes immediate balance change
# Bug Report

## Description

As presented in the video, `Retry now` causes immediate change to `0` of balance of some accounts (but not all in the presented case).

[Screencast from 24.07.2024 13:09:02.webm](https://github.com/user-attachments/assets/2c0802b4-908f-4065-8507-8fcbf7cd71cd)

## Steps to reproduce
Reproduction requires problems which `POKT & Infura` connectivity, what happens relatively often. Probably it's enough to have several accounts with some funds then and do the same what's in the video - pressing the button on the banner.

#### Expected behavior
- The last known balance is cached and displayed until updated value arrive

#### Actual behavior
- Retrying affects presented total balance, confusing end-user

### LINKED ISSUE #15823: [Wallet] Balaces for DAI and SNT disappeard
# Bug Report

## Description

I played a bit with Send dialog. At some point I noticed that balances for SNT and DAI disappeard. I only saw balances for ETH and ARB. I should have 14 SNTs. Balances for ETH and ARB were ok.

image

In the wallet the same:

image

I am attaching some errors from logs:

image

I tried to restart wallet by setting testnet and mainnet again. Then I saw "Pokt and Infura down for Arbitrum". I pressed "retry now" a few times and balances showed up. But the red banner was still there.

## Steps to reproduce

Hard to say. I opened Send dialog a few times, pasted address, chose tokens to send. I did it a few times.
Probably some downloading balances problem?

### Additional Information

- Status desktop version: master - 7d0e77d86ff4230f653721087a25e1722efee591
- Operating System: mac

### PR DESCRIPTION
**Pull request by belalshehab**
- Return errors from fetchBalancesForChain and GetBalancesAtByChain instead of silently ignoring them.
 - Use cached balances if fetching new data fails, preventing empty wallets and ensuring data consistency.
 - Fixed unit tests that was expecting GetBalancesAtByChain to always return nil error

Closes [#15767](https://github.com/status-im/status-desktop/issues/15767)

Fixes https://github.com/status-im/status-desktop/issues/15823

### CODE REVIEW

File: services/wallet/reader.go [hunk 1]
```diff
@@ -264,7 +264,10 @@ func (r *Reader) invalidateBalanceCache() {
 func (r *Reader) FetchOrGetCachedWalletBalances(ctx context.Context, clients map[uint64]chain.ClientInterface, addresses []common.Address) (map[common.Address][]token.StorageToken, error) {
 	needFetch := !r.isBalanceCacheValid(addresses) || r.isBalanceUpdateNeededAnyway(clients, addresses)
 	if needFetch {
-		return r.FetchBalances(ctx, clients, addresses)
```
Comment (saledjenic) [inline services/wallet/reader.go:267]: @belalshehab I am not really sure how does this line differ from what you added in those 3 lines below? Isn't the effect the same?

File: services/wallet/token/balancefetcher/balance_fetcher.go [hunk 2]
```diff
@@ -82,7 +82,7 @@ func (bf *DefaultBalanceFetcher) fetchBalancesForChain(parent context.Context, c
 		group.Add(func(parent context.Context) error {
 			balances, err := bf.FetchChainBalances(parent, accounts, ethScanContract, atBlock)
 			if err != nil {
-				return nil
+				return err
```
Comment (saledjenic) [inline services/wallet/token/balancefetcher/balance_fetcher.go:85]: I am not sure what was an idea here and in the lines below, guess @IvanBelyakoff can say more? By my opinion returning err in those cases look ok.

File: services/wallet/reader.go (hunk 1 above)
Comment (belalshehab) [reply services/wallet/reader.go:267]: here I want to only return fetched balances if no error, otherwise `return r.GetCachedBalances(clients, addresses)` is executed

File: services/wallet/token/balancefetcher/balance_fetcher.go (hunk 2 above)
Comment (belalshehab) [reply services/wallet/token/balancefetcher/balance_fetcher.go:85]: I hope it is okay because without returning the error the client side doesn't have any idea if this data is valid or not, which is not.

File: services/wallet/reader.go (hunk 1 above)
Comment (saledjenic) [reply services/wallet/reader.go:267]: As long as you get an error from `FetchBalances` `fetchedBalances` will be `nil`, when an error is `nil`, `fetchedBalances` will be set. That's why I said the end effect is the same. So feel free to ever this change.

Comment (belalshehab) [reply services/wallet/reader.go:267]: but if I do `return r.FetchBalances(ctx, clients, addresses)` then I will not get the cachedBalances in case of error
the client will get error when fetching data, but last known data will not be shown

Comment (saledjenic) [reply services/wallet/reader.go:267]: I am not sure how?
Could you tell me what's exactly the difference between:
`return r.FetchBalances(ctx, clients, addresses)`
and
```
fetchedBalances, err := r.FetchBalances(ctx, clients, addresses)
if err == nil {
	return fetchedBalances, nil
}
```

Comment (saledjenic) [reply services/wallet/reader.go:267]: Ohhh sorry, I missed that, I see the point now.

**Review by saledjenic — APPROVED** [review]

**Review by Cuteivist — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Comment by Cuteivist** [comment]
Added https://github.com/status-im/status-desktop/issues/15823 as a fix target too, because most likely it fixes it.
