### PR TITLE
fix(community)_: fix pure readonly channels not respecting the right roles

### LINKED ISSUE #15547: [ChatInput]: not disabled with closed channels
# Bug Report

image

"announcements" channel is read-only, yet I can type something here

I'm even able to send it (status changes to "Sent"); although I have no idea whether it gets thru

image

### Additional Information

- Status desktop version: master
- Operating System: linux

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/15547

The problem was that we used `channelEncrypted` to know if we should use all the community members or the given members by the control node.
However, pure read-only channel (for example announcements) are permissions, but not encrypted, since everyone still has access to read them.

The solution is to add `channelHasPermissions` and use that one instead in the hydrate and dehydrate functions.

I also added a test to validate the behaviour. It seems like we never tested pure read-only channels before.

image

### CODE REVIEW

File: protocol/communities_messenger_token_permissions_test.go [hunk 1]
```diff
@@ -1038,6 +1038,76 @@ func (s *MessengerCommunitiesTokenPermissionsSuite) TestViewChannelPermissions()
...
+	msg := &common.Message{
+		ChatMessage: &protobuf.ChatMessage{
+			ChatId:      chat.CommunityChatID(),
+			ContentType: protobuf.ChatMessage_TEXT_PLAIN,
+			Text:        "I can't post on read-only channel",
+		},
+	}
+
+	_, err = s.bob.SendChatMessage(context.Background(), msg)
+	s.Require().Error(err)
```
Comment (osmaczko) [inline protocol/communities_messenger_token_permissions_test.go:1108]: Would it be possible to check exact error here?

**Review by osmaczko — APPROVED** [review]
Good catch, thanks!

**Comment by jrainville** [comment]
FYI, I ran the test a 1000 times:
```
go test -test.count 1000 -run MessengerCommunitiesTokenPermissionsSuite/TestAnnouncementsChannelPermissions -failfast -timeout 3000s -tags gowaku_skip_migrations,gowaku_no_rln
PASS
ok  	github.com/status-im/status-go/protocol	1332.294s
```

File: protocol/communities_messenger_token_permissions_test.go (hunk 1 above)
Comment (jrainville) [reply protocol/communities_messenger_token_permissions_test.go:1108]: That was a good tip, turns out I was passing the wrong chatID, so the error was `unknown chat` :see_no_evil: 

I'm fixing it and making it test the error

Comment (jrainville) [reply protocol/communities_messenger_token_permissions_test.go:1108]: Fixed

**Review by kounkou — APPROVED** [review]
LGTM
