### PR TITLE
fix: "from" block fixed on first activity fetching

### LINKED ISSUE #7036: bug: login crash on fetching activities
## Description

One of my accounts crashes on login during activities fetching

### PR DESCRIPTION
**Pull request by vkjr**
## Description

When activity fetched first time there was a problem with `gethrpc.EarliestBlockNumber`value. It shouldn't have been used "as is" in alchemy request.

In this fix it replaced with "0" block.

Closes #7036

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

File: services/wallet/activityfetcher/manager.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ func (m *Manager) FetchActivity(ctx context.Context, chainID uint64, account get
 	parameters.ToBlock = &toBlock
 
 	if lastFetchedBlock == nil {
-		fromBlock := gethrpc.EarliestBlockNumber
+		fromBlock := gethrpc.BlockNumber(0)
```
Comment (dlipicar) [inline services/wallet/activityfetcher/manager.go:66]: image

image

Comment (dlipicar) [reply services/wallet/activityfetcher/manager.go:66]: I get a strong feeling this wasn't really the cause of the bug

Comment (vkjr) [reply services/wallet/activityfetcher/manager.go:66]: @dlipicar, Hmm..
Screenshot 2025-11-03 at 11 26 48

https://github.com/status-im/status-go/blob/d0824256ccc9758184db9fb74e26715b5ed29984/vendor/github.com/ethereum/go-ethereum/rpc/types.go#L66

Comment (dlipicar) [reply services/wallet/activityfetcher/manager.go:66]: fucking hell... Yeah I was looking at an older version of go-ethereum. We need to check usage of that constant in other places!

**Review by dlipicar — APPROVED** [review]

**Comment by vkjr** [comment]
@dlipicar, since my bigger PR delayed due to Sale's request, I'd like to merge this one to at least avoid empty activity list. Can we merge it with this codecov/patch complain?

**Comment by dlipicar** [comment]
> @dlipicar, since my bigger PR delayed due to Sale's request, I'd like to merge this one to at least avoid empty activity list. Can we merge it with this codecov/patch complain?

Yeah just ask Anthony to force merge, we need to figure out a way to test this with functional tests

**Comment by vkjr** [comment]
@alaibe, would you mind to force-merge this one? 🙏
