### PR TITLE
fix(health-manager)_: handle nil wrapped in an error type

### LINKED ISSUE #6457: Panic in HealthManager
# Panic in HealthManager when handling RPC errors

## Description
The HealthManager component is experiencing panics when handling RPC errors, specifically in cases where a nil RPC error is wrapped in a url.Error. This occurs when attempting to call methods on a nil interface that implements rpc.Error.

## Current Behavior
When a nil RPC error pointer is wrapped in a url.Error and passed through error handling functions:
1. `errors.As()` successfully matches the nil pointer as an implementation of rpc.Error
2. Subsequent attempts to call methods (like ErrorCode()) on this nil interface cause a panic

## Root Cause
The issue stems from insufficient nil checking in error handling functions. While `errors.As()` can successfully match a nil pointer of the correct type, attempting to use the interface leads to a panic.

## Steps to Reproduce
```go
type mockRPCError struct {
	code    int
	message string
}

func (e *mockRPCError) Error() string {
	return e.message
}

func (e *mockRPCError) ErrorCode() int {
	return e.code
}

var nilRPCErr *mockRPCError = nil
urlErr := &url.Error{
    Op:  "Post",
    URL: "http://localhost:8545",
    Err: nilRPCErr,
}
wrappedErr := fmt.Errorf("outer error: %w", urlErr)
// Calling IsMethodNotFoundError(wrappedErr) causes a panic
```

## Impact
This issue affects the stability of the node as the HealthManager component may panic when encountering certain RPC errors, particularly during contract calls.

## Related Components
- HealthManager
- RPC error handling
- Contract calls

### PR DESCRIPTION
**Pull request by friofry**
- Add safeRPCError function to safely handle nil RPC errors
- Add tests

fixes: https://sentry.infra.status.im/organizations/sentry/issues/160/ 

Closes #6457

### CODE REVIEW

File: healthmanager/provider_errors/rpc_provider_errors.go [hunk 1]
```diff
@@ -20,31 +21,56 @@ const (
...
 
+// safeRPCError safely extracts an RPC error and its error code.
+// Returns nil, 0, false if:
+// - err is nil
+// - err is not an RPC error
+// - err is a nil RPC error pointer
+func safeRPCError(err error) (rpc.Error, int, bool) {
+	if err == nil {
+		return nil, 0, false
+	}
```
Comment (igor-sirotin) [inline healthmanager/provider_errors/rpc_provider_errors.go]: This explicit check is redundant, it's done inside `errors.As`

File: healthmanager/provider_errors/rpc_provider_errors_test.go [hunk 2]
```diff
@@ -49,3 +51,126 @@ func TestIsRpsLimitError(t *testing.T) {
...
+					}()
+					tf.fn(tt.err)
+				}()
+			}
+
+			// Test the return value of determineRpcErrorType
+			errType := determineRpcErrorType(tt.err)
+			if errType != tt.wantType {
+				t.Errorf("determineRpcErrorType() = %v, want %v", errType, tt.wantType)
+			}
```
Comment (igor-sirotin) [inline healthmanager/provider_errors/rpc_provider_errors_test.go]: not a big deal, but all these conditions can be simplified by using `require` package:
```suggestion
			require.Equal(t, errType, tt.wantType)
```

File: healthmanager/provider_errors/rpc_provider_errors_test.go [hunk 3]
```diff
@@ -49,3 +51,126 @@ func TestIsRpsLimitError(t *testing.T) {
...
+
+			// Additional checks for specific functions
+			if tt.err != nil {
+				// Check IsRPCError behavior
+				_, ok := IsRPCError(tt.err)
+				if tt.wantType == RpcErrorTypeRPCOther && !ok {
+					t.Error("IsRPCError() returned false for RPC error")
+				} else if tt.wantType == RpcErrorTypeNone && ok {
+					t.Error("IsRPCError() returned true for non-RPC error")
+				}
```
Comment (igor-sirotin) [inline healthmanager/provider_errors/rpc_provider_errors_test.go]: same here and below
```suggestion
				switch tt.wantType {
				case RpcErrorTypeRPCOther:
				    require.Falsef(ok, "IsRPCError() returned false for RPC error")
				case RpcErrorTypeNone:
				    require.Truef(ok,  "IsRPCError() returned true for non-RPC error")
				}
```

**Review by igor-sirotin — APPROVED** [review]

File: healthmanager/provider_errors/rpc_provider_errors.go (hunk 1 above)
Comment (friofry) [reply healthmanager/provider_errors/rpc_provider_errors.go]: Fixed

File: healthmanager/provider_errors/rpc_provider_errors_test.go (hunk 2 above)
Comment (friofry) [reply healthmanager/provider_errors/rpc_provider_errors_test.go]: fixed!

**Review by saledjenic — APPROVED** [review]

**Review by dlipicar — APPROVED** [review]
