### PR TITLE
fix(backup): skip CR for removed contacts and send partial result in case of error

### LINKED ISSUE #19557: some bugs after import through backup
# Bug Report

## Description

1. ~~communities that i own dont have members, channels or any chats anymore. this is after importing my main 86.eth profile through seedphrase and then importing my backup data through the backup file.~~
edit: seems to have resolved itself after restart

Image

2. it seems like none of my contacts stayed as contacts. all the chats and contents are still there but all of them now have a 'send contact request' at the bottom. i guess from the long list of contact requests im prompted to accept and the many i see that are going out that status is trying to rebuild the contact list? also annoying that it doesnt recognize their last set displaynames if they havent been online in the last 30 days, i have a whole bunch of old convos with three letter names now (and the chats arent ordered by recent date).

Image

3. another bug, or at least desired feature: none of my spectated communities came along. i did notice that for those i spectated in the past and now navigated back to if i still had the link i did manage to see all the old chat history, so history for spectated communities works. but for some i dont have the communitiy link anymore. wouldve been nice if the import process simply got back all the spectated ones, shouldnt be too hard since i apparently already am storing all their message histories, right?

edit: 3 moved to new issue here: https://github.com/status-im/status-app/issues/19584

## Steps to reproduce

1. have existing status profile with owned communities, spectated communities, contacts, dms etc
2. back it up locally
3. restore that same profile from seed
4. import backup into that restored profile

### Additional Information

- Status desktop version: 2.36
- Operating System: ubuntu 22.04

### PR DESCRIPTION
**Pull request by jrainville**
Cherry-pick of https://github.com/status-im/status-go/pull/7203

Fixes https://github.com/status-im/status-app/issues/19557

There were two issues:
1. We tried to generate a Contact request for removed contacts, so that obviously failed for no reason, stopping the saving of contacts
2. More importantly, if there were errors, we didn't call the save and signals, even if 99% of the data was working. So we send the error at the very end instead

### CODE REVIEW

**Review by igor-sirotin — APPROVED** [review]

File: protocol/messenger_handler.go [hunk 1]
```diff
@@ -525,47 +525,50 @@ func (m *Messenger) HandleSyncInstallationContactV2(ctx context.Context, state *
...
 
-			err := m.syncContactRequestForInstallationContact(contact, state, chat, true)
+			err := m.syncContactRequestForInstallationContact(contact, state, chat, contact.ContactRequestLocalState == contacts.ContactRequestStateSent)
 			if err != nil {
 				return err
 			}
-		}
+		} else if message.Added || message.HasAddedUs {
+			// NOTE(cammellos): this is for handling backward compatibility, old clients
+			// won't propagate ContactRequestRemoteClock or ContactRequestLocalClock
```
Comment (jrainville) [inline protocol/messenger_handler.go]: This is the part that is getting flagged as not covered by codecov. What do you guys think of just getting rid of that backwards compatibility section. The commit that introduced it is 3 years old. I think it's deprecated enough.

The commit: https://github.com/status-im/status-go/commit/cefa0089dcf24e2f91ebc133ec4994c1f2e128ce#diff-59d196f7f72de56c64ba2c559fcbb51762c418a22d2b83c59662b772a09b3c0a

**Review by osmaczko — APPROVED** [review]
