### PR TITLE
Recover from panics which can get sent from goleveldb due to bad arguments. Closes #1059

### LINKED ISSUE #1059: Account for panics in goleveldb
We use https://github.com/syndtr/goleveldb for persistence in Mailserver, and this library is written a way that uses panics heavily (`grep -r "panic("  . | wc -l` yields `63`).

This may cause Mailserver to crash when one of the requests ended up with panic inside goleveldb library.

The easy (and correct) workaround for this is to catch the panics in our code whenever we use leveldb.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/syndtr/goleveldb">syndtr/goleveldb</a></strong></div><div>goleveldb - LevelDB key/value database in Go.</div></blockquote>

### PR DESCRIPTION
**Pull request by pedropombeiro**
This PR adds recovery logic around calls to goleveldb in mailserver.go so that the mailserver doesn't crash when a request with bad arguments is handled. Normally the arguments are validated beforehand, but should any unforeseen situation happen, this will log the condition and keep the server running.

Given that we've added validation to the `from` and `to` arguments recently, and that reproducing the panic is not possible with a pre-existing DB state, I didn't add tests for this.

Closes #1059

### CODE REVIEW

File: mailserver/mailserver.go [hunk 1]
```diff
@@ -164,6 +164,16 @@ func (s *WMailServer) Archive(env *whisper.Envelope) {
 		log.Error(fmt.Sprintf("rlp.EncodeToBytes failed: %s", err))
 		archivedErrorsCounter.Inc(1)
 	} else {
+		// Recover from possible goleveldb panics
+		defer func() {
+			if r := recover(); r != nil {
+				if errString, ok := r.(string); ok {
+					err := fmt.Errorf("recovered from panic in Archive: %v", errString)
+					log.Error(err.Error())
```
Comment (divan) [inline mailserver/mailserver.go]: `log.Error()` takes `string` as an argument, so no need to create error interface here.

File: mailserver/mailserver.go [hunk 2]
```diff
@@ -189,6 +199,16 @@ func (s *WMailServer) DeliverMail(peer *whisper.Peer, request *whisper.Envelope)
 	}
 
 	if ok, lower, upper, bloom := s.validateRequest(peer.ID(), request); ok {
+		// Recover from possible goleveldb panics
+		defer func() {
```
Comment (divan) [inline mailserver/mailserver.go]: the deferred function will be defined in the scope of the function, and not of the `if` scope, so maybe it's better to move defer statement to the top of function to avoid possible confusion?

File: mailserver/mailserver.go [hunk 3]
```diff
@@ -296,7 +316,7 @@ func (s *WMailServer) validateRequest(peerID []byte, request *whisper.Envelope)
 
 	if upper < lower {
 		log.Error(fmt.Sprintf("Query range is invalid: from > to (%d > %d)", lower, upper))
-		return false, 0, 0, nil
+		//return false, 0, 0, nil
```
Comment (divan) [inline mailserver/mailserver.go]: Even if we are catching the panic, I think it's worth to stop processing request here, as this is clearly an incorrect request and proper fix would be to communicate this to the caller somehow.

**Review by divan — CHANGES_REQUESTED** [review]

File: mailserver/mailserver.go (hunk 2 above)
Comment (pedropombeiro) [reply mailserver/mailserver.go]: The reason I put it there is that we only run that logic if we actually hit the DB, but I can move it to the top level scope.

File: mailserver/mailserver.go (hunk 3 above)
Comment (pedropombeiro) [reply mailserver/mailserver.go]: Oops, that was part of testing, and not supposed to be committed. Thanks for catching that!

**Review by divan — APPROVED** [review]
LGTM
@jakubgs can you check if those error lines (`log.Error(fmt.Sprint(...))`) are good for being used in Kibana?

File: mailserver/mailserver.go [hunk 4]
```diff
@@ -188,6 +197,15 @@ func (s *WMailServer) DeliverMail(peer *whisper.Peer, request *whisper.Envelope)
...
 	}
 
+	// Recover from possible goleveldb panics
+	defer func() {
+		if r := recover(); r != nil {
+			if errString, ok := r.(string); ok {
+				log.Error(fmt.Sprintf("recovered from panic in DeliverMail: %s", errString))
+			}
+		}
+	}()
```
Comment (gravityblast) [inline mailserver/mailserver.go]: I thought this part should have been in `processRequest` but I think it makes sense have it here so that `sendHistoricMessageResponse` is not called if `processRequest` panics.

**Review by gravityblast — APPROVED** [review]

File: mailserver/mailserver.go [hunk 5]
```diff
@@ -158,6 +158,15 @@ func (s *WMailServer) Close() {
 
 // Archive a whisper envelope.
 func (s *WMailServer) Archive(env *whisper.Envelope) {
+	// Recover from possible goleveldb panics
+	defer func() {
```
Comment (adriacidre) [inline mailserver/mailserver.go]: You could try to have this logic on a shared function so we can use it like:
```
func (s *WMailServer) Archive(env *whisper.Envelope) {
    defer recoverLevelDBPanics()
```

File: mailserver/mailserver.go [hunk 6]
```diff
@@ -156,8 +156,19 @@ func (s *WMailServer) Close() {
 	}
 }
 
+func recoverLevelDBPanics(calleMethodName string) {
+	// Recover from possible goleveldb panics
```
Comment (adriacidre) [inline mailserver/mailserver.go:160]: What about this comment as function comment instead?

**Review by adriacidre — APPROVED** [review]
LGTM!
