### PR TITLE
fix: merge balance history using block time

### LINKED ISSUE #9205: Merge balance using the shortest time distance
Address https://github.com/status-im/status-go/blob/da73e8161273fafe248c539d2f6b332c872cde87/services/wallet/history/service.go#L210

### PR DESCRIPTION
**Pull request by stefandunca**
### Implements [9205](https://github.com/status-im/status-desktop/issues/9205)
    
This change improves on the [previous implementation](https://github.com/status-im/status-go/pull/3071), which used the block number, that doesn't work (that means merging incompatible blockchains, regarding block pacing, e.g. L1 vs L2)

#### Problem description

Users can visualize the balance history graph for all the selected chains for a specific address and token currency; see [`wallet.history.Service.GetBalanceHistory`](https://github.com/status-im/status-go/blob/a2ff03c79ec4b874c53eabb768e1a4908d522a5d/services/wallet/history/service.go#L200)

That means we fetch from the DB [balance entries](https://github.com/status-im/status-go/blob/a2ff03c79ec4b874c53eabb768e1a4908d522a5d/services/wallet/history/balance.go#L89) for multiple chains. Some tokens (chain native, `ERC20`) have the same blocks hence the same timestamp for each entry and could be merged by block number (the previous implementation).

However, the same tokens on incompatible chains (L1 vs L2) have different block numbers; hence the entries will be on different block numbers having different states).

#### Solution

We merge the entries for each chain that fit in the same [time slice](https://github.com/status-im/status-go/blob/a2ff03c79ec4b874c53eabb768e1a4908d522a5d/services/wallet/history/balance.go#L66) and output one entry with the slice's last timestamp.

Closes: [#9205](https://github.com/status-im/status-desktop/issues/9205)

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

File: services/wallet/history/service.go [hunk 1]
```diff
@@ -48,6 +49,8 @@ type Service struct {
 	visibleTokenSymbolsMutex sync.Mutex // Protects access to visibleSymbols
 }
 
+type chainIdentity uint64
```
Comment (stefandunca) [inline services/wallet/history/service.go:52]: For clarity not to mix `ChainID` with something else

File: services/wallet/history/service.go [hunk 2]
```diff
@@ -198,80 +201,178 @@ func (src *tokenChainClientSource) BalanceAt(ctx context.Context, account common
...
 		pos[k] = 0
 	}
 
 	res := make([]*DataPoint, 0)
-	done := false
-	for !done {
-		var minNo *big.Int
-		var timestamp uint64
-		// Take the smallest block number
+	strideStart := findFirstStrideWindow(data, stride)
```
Comment (stefandunca) [inline services/wallet/history/service.go:232]: The time interval for the entire data set is split into fixed time intervals based on the "stride" created by block numbers that we use in balance fetching.

File: services/wallet/history/service_test.go [hunk 3]
```diff
@@ -34,10 +35,15 @@ func prepareTestData(data []TestDataPoint) map[uint64][]*DataPoint {
 	return res
 }
 
+// getBlockNumbers returns -1 if block number is nil
```
Comment (stefandunca) [inline services/wallet/history/service_test.go:38]: For simplicity, the `*big.Int` in test data is represented by `int64` so we use `-1` to mark `nil` entries which happen now for the data points that don't have the same `BlockID` for an entry.

File: services/wallet/history/service_test.go [hunk 4]
```diff
@@ -116,15 +124,16 @@ func TestServiceGetBalanceHistoryAllMatch(t *testing.T) {
...
 	})
 
-	res, err := mergeDataPoints(testData)
+	res, err := mergeDataPoints(testData, strideDuration)
 	require.NoError(t, err)
 	require.Equal(t, 4, len(res))
 	require.Equal(t, []int64{105, 115, 125, 135}, getBlockNumbers(res))
 	require.Equal(t, []int64{3, 3 * 2, 3 * 3, 3 * 4}, getValues(res))
-	require.Equal(t, []int64{105, 115, 125, 135}, getTimestamps(res))
+	require.Equal(t, []int64{115, 125, 135, 145}, getTimestamps(res))
```
Comment (stefandunca) [inline services/wallet/history/service_test.go:132]: Now merged points have the timestamp at the end of the merge window

**Review by saledjenic — APPROVED** [review]

**Review by alaibe — APPROVED** [review]
