### PR TITLE
Fix: Don't create extra mutual state messages when accepting the CR again

### LINKED ISSUE #13019: New issues with contact requests
# Bug Report
Screenshot 2023-12-15 at 14 00 12

image

## Description

I've recently noticed 2 new contact request issues, both reproduced with moderate frequency:

1) The receiver doesn't get the contact request , it looks like it gets lost in the network. But normal messages don't get lost, at least that often.
2) The sending party sometimes receives an additional message that the contact request is accepted, although the sending party does not perform any additional manipulations. May be related to https://github.com/status-im/status-go/issues/3803

## Steps to reproduce

1. Create a new account
2. Send a contact request to a user
3. Goto 1 until one of the problems is reproduced.

#### Expected behavior

1. Receiver gets a contact request
2. Sender sees 3 messages:

Screenshot 2023-12-15 at 14 09 41

#### Actual behavior

Sometimes happens (1) or (2) problem

### PR DESCRIPTION
**Pull request by MishkaRogachev**
For https://github.com/status-im/status-desktop/pull/13060

Important changes:
- [x] `handleAcceptContactRequestMessage` func does not create extra system messages, when it's accepted again.

Close https://github.com/status-im/status-desktop/issues/13019

### CODE REVIEW

File: protocol/messenger_contact_requests_test.go [hunk 1]
```diff
@@ -539,7 +565,69 @@ func (s *MessengerContactRequestSuite) TestAliceTriesToSpamBobWithContactRequest
...
+	s.Require().NoError(err)
+
+	// Check we don't have extra messages on Alice's side
+	resp, err := WaitOnMessengerResponse(alice,
+		func(r *MessengerResponse) bool {
+			return len(r.ActivityCenterNotifications()) == 1 && len(r.Messages()) == 1
+		},
+		"contact request acceptance not received",
+	)
+	s.logResponse(resp, "acceptContactRequest")
```
Comment (cammellos) [inline protocol/messenger_contact_requests_test.go]: debug?

**Review by cammellos — APPROVED** [review]

File: protocol/messenger_contact_requests_test.go [hunk 2]
```diff
@@ -1472,7 +1560,7 @@ func (s *MessengerContactRequestSuite) blockContactAndSync(alice1 *Messenger, al
 	s.Require().Equal(ContactRequestStateReceived, respContact.ContactRequestRemoteState)
 
 	// Check chats list
-	//s.Require().Len(alice2.Chats(), 1) // FIXME: Uncomment after https://github.com/status-im/status-go/issues/3800
+	s.Require().Len(alice2.Chats(), 2)
```
Comment (MishkaRogachev) [inline protocol/messenger_contact_requests_test.go]: @igor-sirotin, maybe it's time to remove https://github.com/status-im/status-go/blob/develop/protocol/messenger_contacts.go#L414-L415 ?

**Comment by MishkaRogachev** [comment]
@igor-sirotin unfortunately this fix does not relate to https://github.com/status-im/status-go/issues/3803 and https://github.com/status-im/status-go/issues/3801 issues. It's a problem on the syncing side, as you mentioned [here](https://github.com/status-im/status-go/issues/3803#issuecomment-1654588500) should be resolved with having only one source of truth. And imo it's a bad time to refactor this part now

File: protocol/messenger_contact_requests_test.go (hunk 2 above)
Comment (igor-sirotin) [reply protocol/messenger_contact_requests_test.go]: I think not yet. Maybe in a year or smth 😄

Comment (igor-sirotin) [reply protocol/messenger_contact_requests_test.go]: But it's better to use `AddChatsCount` in such cases.

https://github.com/status-im/status-go/blob/d535cd95f885a30387e0333f71c9a1081fc72a3a/deprecation/protocol.go#L8-L17

**Review by igor-sirotin — APPROVED** [review]
