### PR TITLE
fix(bridge)_: fix bridge replies not working when they come from Discord

### LINKED ISSUE #16323: Bridge replies don't show as replies from Status to Discord
# Bug Report

## Description

When you do a reply on Status, the message on Discord doesn't show as a reply, just like a normal message.

When sending a reply from Discord however, it works fine.

## Steps to reproduce

1. Send a message on a bidged channel
2. Reply to that message in Status

#### Expected behavior

The message shows a a reply on both platforms

#### Actual behavior

The message shows as a reply only on Status. It shows as a normal message on Discord

### Additional Information

- Status desktop version: 2.30.1
- Operating System: Ubuntu 22

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/16323

The problem was that the code expected to receive the Discord message ID, but the bridge is smart enough to return the Status message ID already, so there is no need to try and convert it.

There were also a couple issues in the bridge code itself.

Bridge PR: https://github.com/status-im/matterbridge/pull/18

### CODE REVIEW

File: protocol/message_persistence.go [hunk 1]
```diff
@@ -3075,15 +3075,7 @@ func (db sqlitePersistence) findAndUpdateReplies(tx *sql.Tx, bridgeMessageID str
 }
 
 func (db sqlitePersistence) findAndUpdateRepliedTo(tx *sql.Tx, discordParentMessageID string, statusMessageID string) error {
-	// Finds status messages id which are replies for bridgeMessageID
-	repliedMessageID, err := db.findStatusMessageIDForBridgeMessageID(tx, discordParentMessageID)
```
Comment (siddarthkay) [inline protocol/message_persistence.go:3079]: nice! we could also nuke this function definition then `findStatusMessageIDForBridgeMessageID `

**Review by siddarthkay — APPROVED** [review]

**Comment by igor-sirotin** [comment]
@jrainville a bunch of tests are failing, including `TestBridgeMessageReplies` 🤔 
image

image

I think it's only `TestBridgeMessageReplies` and the others are just flaky.

**Review by igor-sirotin — APPROVED** [review]
Nice and clean, just fix the `TestBridgeMessageReplies`

**Review by osmaczko — APPROVED** [review]

**Comment by jrainville** [comment]
@igor-sirotin @osmaczko re-asking review because I removed even more code when I fixed the test.

I also tested again with the real app to make sure my assumptions were all right and it still all works. Proof:
image

Also, I tested closing the app and sending a lot of messages and replies, so that it would fetch out of order to confirm that it still managed to populate the replies even out of order and it worked:
image

For example, the `4 4` message came in, but not the `4` message, so at first it shower "unknown original message, please fetch", I did fetch more and `4` appeared and it populated the reply correctly :+1:

File: protocol/persistence_test.go [hunk 2]
```diff
@@ -1995,18 +1995,18 @@ func TestBridgeMessageReplies(t *testing.T) {
 	err = insertMinimalBridgeMessage(p, "444", "4", "3")
 	require.NoError(t, err)
 
-	// status message "222" should have reply_to = "111"
+	// status message "222" should have reply_to =" 1" because it's a discord message to another discord message
```
Comment (igor-sirotin) [inline protocol/persistence_test.go]: These message ids are so unobvious, impossible to read the test really 😵‍💫

**Review by igor-sirotin — APPROVED** [review]
