### PR TITLE
fix(communities/manager): make historyArchiveTasks a SyncMap

### LINKED ISSUE #3447: Possible crash on log out because of History archive concurrent map writes
While testing https://github.com/status-im/status-go/pull/3445, I found that when logging out, it actually crashed.

The important logs are below:

```
INF 2023-05-02 10:16:39.860-04:00 logging out...                             topics="app-controller" tid=112852 file=app_controller.nim:278
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 5606 [running]:
github.com/status-im/status-go/protocol/communities.(*Manager).StartHistoryArchiveTasksInterval(0x1c005f9cea0, 0x1c0008a2fe0, 0x4154206568742061?)
	/home/jonathan/dev/status-desktop/vendor/status-go/protocol/communities/manager.go:2475 +0xab9
created by github.com/status-im/status-go/protocol.(*Messenger).InitHistoryArchiveTasks
	/home/jonathan/dev/status-desktop/vendor/status-go/protocol/messenger_communities.go:2195 +0x15f6
```

It seems like the same solution done here https://github.com/status-im/status-go/pull/3445 for the `periodicMemberPermissionsTasks` needs to be done for the `historyArchiveTasks` as well

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #3447

Same thing as https://github.com/status-im/status-go/pull/3445 but for `historyArchiveTasks`

### CODE REVIEW

File: protocol/communities/manager_test.go [hunk 1]
```diff
@@ -201,7 +201,14 @@ func (s *ManagerSuite) TestStartHistoryArchiveTasksInterval() {
...
 	time.Sleep(5 * time.Second)
-	s.Require().Len(s.manager.historyArchiveTasks, 1)
+
+	// sync.Map doesn't have a Len function, so we need to count manually
+	count := 0
+	s.manager.historyArchiveTasks.Range(func(_, _ interface{}) bool {
+		count++
+		return true
+	})
+	s.Require().Equal(count, 1)
```
Comment (osmaczko) [inline protocol/communities/manager_test.go]: It seems that introducing a helper function here could help us reduce code duplication

**Review by osmaczko — APPROVED** [review]
