### PR TITLE
fix: better `IsStatusSharedURL`

### LINKED ISSUE #4275: StatusUnfurler treats https://status.app/ as Status link
# Problem

This happens because of this function implementation:
https://github.com/status-im/status-go/blob/b65eda3f42c86428566e32e8536fb59842378497/protocol/messenger_share_urls.go#L514-L516

# Implementation

`IsStatusSharedURL` should be smarted and at least check for `/u`, `/c` or `/cc` path.

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/status-im/status-go/issues/4275

Now `IsStatusSharedURL` method check for URL to begin with one of the options:
- `https://status.app/u#`
- `https://status.app/u/`
- `https://status.app/c#`
- `https://status.app/c/`
- `https://status.app/cc/`

So link preveiw is generated properly for https://status.app:
image

### CODE REVIEW

File: protocol/messenger_share_urls.go [hunk 1]
```diff
@@ -511,13 +523,17 @@ func (m *Messenger) parseUserURLWithData(data string, chatKey string) (*URLDataR
...
+		strings.HasPrefix(url, sharedURLUserPrefixWithData) ||
+		strings.HasPrefix(url, sharedURLCommunityPrefix) ||
+		strings.HasPrefix(url, sharedURLCommunityPrefixWithData) ||
+		strings.HasPrefix(url, sharedURLChannelPrefixWithData)
 }
 
 func (m *Messenger) ParseSharedURL(url string) (*URLDataResponse, error) {
-	if !m.IsStatusSharedURL(url) {
-		return nil, fmt.Errorf("url should start with '%s'", baseShareURL)
+	if !IsStatusSharedURL(url) {
```
Comment (MishkaRogachev) [inline protocol/messenger_share_urls.go]: it would be a little more obvious to my taste if you combine here checking and parsing urls, something like this:
```
	if chatKey := chatKeyFromUrl(url); isStatusCommunityUrl(url) {
		return m.parseCommunityURLWithChatKey(chatKey)
	}
    ...
```

Comment (igor-sirotin) [reply protocol/messenger_share_urls.go]: nice idea!
refactored the function, looks better to me now 👍

File: protocol/messenger_share_urls.go [hunk 2]
```diff
@@ -511,51 +525,68 @@ func (m *Messenger) parseUserURLWithData(data string, chatKey string) (*URLDataR
...
+		chatKey := strings.TrimPrefix(url, sharedURLUserPrefix)
+		if strings.HasPrefix(chatKey, "zQ3sh") {
+			return m.parseUserURLWithChatKey(chatKey)
+		}
+		return m.parseUserURLWithENS(chatKey)
 	}
 
-	if strings.HasPrefix(urlContents[0], "c/") {
-		return m.parseCommunityURLWithData(strings.TrimPrefix(urlContents[0], "c/"), urlContents[1])
+	if strings.HasPrefix(url, sharedURLUserPrefixWithData) {
```
Comment (MishkaRogachev) [inline protocol/messenger_share_urls.go:555]: yeah, that's much better!

**Review by MishkaRogachev — APPROVED** [review]
Great!
