### PR TITLE
silence `make lint-gas` warnings

### LINKED ISSUE #543: make lint-gas fails with recent gometalinter change
# Problem

I recently set up a new go development environment, and I get several warnings from the `make lint-gas` step:

```
lint-gas
cmd/statusd/main.go:131::warning: Errors unhandled.,LOW,HIGH (gas)
cmd/statusd/main.go:132::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/types.go:339::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/types.go:340::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/types.go:361::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/types.go:362::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/utils.go:72::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/utils.go:136::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/utils.go:137::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/utils.go:145::warning: Errors unhandled.,LOW,HIGH (gas)
geth/common/utils.go:147::warning: Errors unhandled.,LOW,HIGH (gas)
geth/jail/console/console.go:21::warning: Errors unhandled.,LOW,HIGH (gas)
geth/jail/internal/timers/timers.go:27::warning: Errors unhandled.,LOW,HIGH (gas)
geth/jail/internal/timers/timers.go:85::warning: Errors unhandled.,LOW,HIGH (gas)
geth/log/log.go:94::warning: Errors unhandled.,LOW,HIGH (gas)
geth/params/config.go:168::warning: Errors unhandled.,LOW,HIGH (gas)
geth/params/config.go:180::warning: Errors unhandled.,LOW,HIGH (gas)
geth/params/config.go:204::warning: Errors unhandled.,LOW,HIGH (gas)
make: *** [lint-gas] Error 1
```

@divan [suggested](https://status-im.slack.com/archives/G2B3U1AKE/p1511980987000592?thread_ts=1511974141.000865&cid=G2B3U1AKE) that [a recent change to gometalinter](https://github.com/alecthomas/gometalinter/commit/3e602d9013785a8e54137caf409564a966586b85) is at fault.

# Implementation

For each unhandled error, either the code should be changed to handle it, or else `// nolint: gas` should be added to that line.  Each unhandled error should be examined independently to determine which approach (handle or ignore) is appropriate.

### PR DESCRIPTION
**Pull request by feuGeneA**
Potentially fixes #543.  Current changes simply tell `lint-gas` to ignore each of these unhandled errors.  (See #543 for the specific warnings.)  Each of these changes needs scrutiny to determine whether an ignore is appropriate, or whether we really should be handling that error.

### CODE REVIEW

**Comment by adambabik** [comment]
1. Why some of the problems related to errors are not reported by `errcheck` but are reported by `gas`? It looks like these two tools use different rules related to the same thing.
2. `Gas is still in alpha and accepting feedback from early adopters. We do not consider it production ready at this time.` -- not sure if we should actually use then.

**Comment by mandrigin** [comment]
We found it very useful even in its alpha stage. It is the only linter I know which detects security-related issues, like weak randoms, weak hashes and certificates checks.

**Comment by divan** [comment]
I usually run linters manually from time to time, and while using linters in CI totally make sense, I'm worried a bit of increasing costs of silencing linters via `nolint` comments. This is a technical debt of fighting high positive rate of linters, right?

For example, the code `l.Ready(t) // nolint: errcheck, gas` is silencing error checking linter, but imagine that the semantics of `Ready()` method is changed and it doesn't return error anymore. Who and how would ever remember to cleanup that `nolint` comment?

Or this piece of code - `fmt.Fprintf(os.Stderr, usage) // nolint: gas` - is totally fine. Cases, where stderr `fd` is unavailable, are extremely unlikely and `Fprintf` is used without error checking every time and that's fine.

So I would prefer to keep the amount of `nolint` comments at the minimal level and run linters from time to time manually. For the CI probably it makes sense to run only _important_ linters or static analysis checks with the minimal false positive rate. For the rest, the manual run should do the trick.

**Comment by mandrigin** [comment]
@divan We quite successfully use the opposite strategy at Opera, run as many linters on CI as possible.
To avoid `// nolint`, we used programmatic wrappers. Either `must.Do(...)` function that panics if err != nil, or `ignoreErr(...)`. With these wrappers, it is impossible to miss if the signature has changed.

One more alternative is an assertion functions, that panic only in debug mode.

**Comment by dnephin** [comment]
> Why some of the problems related to errors are not reported by `errcheck` but are reported by `gas`?

`errcheck` considers an assignment to blank as a "handled error" (https://github.com/kisielk/errcheck#use), which explains why some of these are not reported by `errcheck`. 

The other cases are `fmt` which are ignored by default by `errcheck`: https://github.com/kisielk/errcheck/blob/master/main.go#L143-L145

> but imagine that the semantics of` Ready()` method is changed and it doesn't return error anymore. Who and how would ever remember to cleanup that nolint comment?

That is exactly why `WarnUnmatchedDirective` (`--warn-unmatched-nolint`) was added to `gometalinter` (alecthomas/gometalinter#368). When enabled it will inform you that there are unused `// nolint` that can be removed (however note there are still some issues to work out with build tags and unconvert  alecthomas/gometalinter#422).

> So I would prefer to keep the amount of nolint comments at the minimal level 

There are other options for keeping `nolint` to a minimum (in addition to the suggestion by @mandrigin):
* the `gas` linter takes a config, which lets you disable some checks with `--exclude` (or a `--conf`). You can customize the command run by `gometalinter` by using a `gometalinter.json`:

```json
{
  "Linters": {
    "gas": {"Command": "gas --exclude ..."}
  }
} 
```
* `gometalinter` allows you to exclude/ignore errors that match a pattern (`--exclude` or `Exclude` in the config)

>  run as many linters on CI as possible.

+1. This is the strategy I use on any projects I contribute to as well. I would rather that contributors fix linter errors in the PR, instead of always fixing issues after the PR merges. I have found that most linters require very few `// nolint`, however I have never had great results from `gas`.

**Comment by divan** [comment]
> run as many linters on CI as possible.

That's interesting, but I guess what makes a difference is how do you treat linters output, right? Did your CI fail when some linter prints warning message?

`go lint`, for example, explicitly warns in their [README](https://github.com/golang/lint) to not try to make all programs completely "lint-free". I mean warning from most linters are not errors.

I believe the key here is to maintain a balance between the usefulness of linter and the costs of using/supporting it. Trying to make program completely "lint-free" is like trying to reach 100% test coverage — it may become a target by itself, at which point it becomes a bad measure ([Goodhart's law](https://en.wikipedia.org/wiki/Goodhart%27s_law)).

> That is exactly why WarnUnmatchedDirective (--warn-unmatched-nolint) was added to gometalinter

Nice, thanks! Didn't know that.

**Comment by mandrigin** [comment]
Yes, our CI fails on every linter issue. The issues we disagree with are blocked with `gometalinter`s `--exclude` parameter. 

That’s how we initially got into `gometalinter`, to silence warnings from linters that don’t have any config themselves.

**Comment by mandrigin** [comment]
> I believe the key here is to maintain a balance between the usefulness of linter and the costs of using/supporting it. Trying to make program completely "lint-free" is like trying to reach 100% test coverage — it may become a target by itself, at which point it becomes a bad measure (Goodhart's law).

I 💯%  agree with that, it shouldn't be a goal by itself.

I haven't really noticed any drop in the team productivity after we introduced all the linters in ours CI. 

Sure, when introducing them, it took a few days to fix the warnings and to ignore something unreasonable. Since then, I haven't seen much of the false positives. I was actually quite happy with how reasonable the static analyzers are in golang.

**Comment by adambabik** [comment]
Great discussion! To sum up, I got an impression that we agree that this PR is a good approach, especially, that there are not that many changes, but maybe we should spend some time later and tweak linters configuration.

> go lint, for example, explicitly warns in their README to not try to make all programs completely "lint-free". I mean warning from most linters are not errors.

In gometalinter, it's possible to change severity from warning to error and e.g. display only errors. We can move `gas` to warning and the rest to error but I am afraid no one will look at warnings actually.

I checked out all gometalinter options and I think we can create a follow-up issue which:
1. Move configuration to a json file from our huge `lint.mk` file,
2. Start using `--warn-unmatched-nolint`.

File: cmd/statusd/main.go [hunk 1]
```diff
@@ -157,6 +157,7 @@ Examples:
   statusd -cli          # enable connection by statusd-cli on default port
 
 Options:
-`)
+`
+	fmt.Fprintf(os.Stderr, usage) // nolint: gas
```
Comment (adambabik) [inline cmd/statusd/main.go:161]: I wonder why do we print usage to stderr?

**Review by adambabik — APPROVED** [review]

File: cmd/statusd/main.go (hunk 1 above)
Comment (divan) [reply cmd/statusd/main.go:161]: @adambabik I think it's a common UNIX practice and helpful when you pipe commands through the chain of pipes: if the program is used incorrectly, the user will see the error instead of "usage" text piped into the next command.
Not our case, of course, but I believe that's the reason for using stderr for usage output.

Comment (adambabik) [reply cmd/statusd/main.go:161]: It makes perfect sense 👍  Hopefully, we also return a non-zero exit code.

**Review by mandrigin — APPROVED** [review]
