### PR TITLE
fix(messenger_handler): ignore messages from dismissed contacts

### LINKED ISSUE #18674: Closed 1-1 chats sometimes reappear after a restart
# Bug Report

## Description

Before (removed all unwanted chats):

Image

After a couple restarts (I hadn't noticed them initially, since they are lower now):

Image

Elon Mush for example I had deleted and it is back

## Steps to reproduce

0. have a lot of 1-1 chats
1. close a couple of them
2. Restart the app (one or more times)

#### Expected behavior

1-1 chats stay closes (deleted)

#### Actual behavior

1-1 chats come back to haunt you

### Additional Information

- Status desktop version: 2.35.0 RC4 (but it's been there for a while)
- Operating System: Ubuntu 22

### PR DESCRIPTION
**Pull request by jrainville**
Part of https://github.com/status-im/status-desktop/issues/18674

We still had edge cases where we accepted messages/requests from dismissed contacts.

The principle was ok, because it makes sense to receive messages from non-contacts, because we need to receive contact requests, but when the contact is dismissed, we shouldn't accept anymore messages from them, since we do not want those requests (there was a way to send more than one request).

I'm not sure if it fixes the issue mentioned above, because I don't exactly know the reproduction steps. It's possible that the problem were the waku backups, but those don't exist anymore.
I'll try this PR over next days to see if it happens again

### CODE REVIEW

File: protocol/messenger_handler.go [hunk 1]
```diff
@@ -526,6 +526,11 @@ func (m *Messenger) HandleSyncInstallationContactV2(state *ReceivedMessageState,
 		}
 	}
 
+	if contact.Dismissed() {
+		// We dismissed this contact request locally, no need to proceed
+		return nil
+	}
+
```
Comment (igor-sirotin) [inline protocol/messenger_handler.go]: Hmm not sure about this part. What if we un-dismissed it on the other device?

File: protocol/messenger_handler.go [hunk 2]
```diff
@@ -2932,6 +2947,8 @@ func (m *Messenger) isMessageAllowedFrom(publicKey string, chat *Chat) (bool, er
 		return false, err
 	}
 
+	contact, contactOk := m.allContacts.Load(publicKey)
```
Comment (igor-sirotin) [inline protocol/messenger_handler.go]: Why move this?

File: protocol/messenger_handler.go (hunk 1 above)
Comment (jrainville) [reply protocol/messenger_handler.go]: Good point, I'll test it and double-check the code

File: protocol/messenger_handler.go (hunk 2 above)
Comment (jrainville) [reply protocol/messenger_handler.go]: Leftover. I had added a condition using `contact`  here, but it was no longer needed. I'll remove

File: protocol/messenger_handler.go (hunk 1 above)
Comment (jrainville) [reply protocol/messenger_handler.go]: Turns out it was a leftover from my exploration and not needed. The actual fix is in the `handleChatMessage` function. 

I updated the tests and added a new one to validate the behaviour. 

You can review again @igor-sirotin

File: protocol/messenger_handler.go [hunk 3]
```diff
@@ -1044,6 +1044,13 @@ func (m *Messenger) handleRetractContactRequest(state *ReceivedMessageState, con
 		return nil
 	}
 
+	m.allContacts.Store(contact.ID, contact)
+
+	if contact.Dismissed() {
+		// We dismissed this contact request locally already, no need to proceed
+		return nil
+	}
```
Comment (igor-sirotin) [inline protocol/messenger_handler.go:1052]: Hmmmm, looking at `ContactRequestRetracted` implementation, which is called right above:
https://github.com/status-im/status-go/blob/2c48ce7ecf182770b36a28bf1b3e96ee8feb2097/protocol/contacts/contact.go#L305-L323

We already check the dismissed state there, maybe we should modify `ContactRequestRetracted` instead?

File: protocol/messenger_handler.go [hunk 4]
```diff
@@ -2199,6 +2204,11 @@ func (m *Messenger) handleChatMessage(state *ReceivedMessageState, forceSeen boo
 
 	contact := state.CurrentMessageState.Contact
 
+	if chat.ChatType == ChatTypeOneToOne && contact.Dismissed() {
+		m.logger.Info("ignoring one on one messages dismissed contacts")
+		return nil
+	}
+
```
Comment (igor-sirotin) [inline protocol/messenger_handler.go:2198]: There is a `isMessageAllowedFrom` here:
https://github.com/status-im/status-go/blob/5825d1cba51ab86397c50928832c467db2438512/protocol/messenger_handler.go#L1128-L1134

Looks to me like `Dismissed` check should be part of it.

And there, looks like we should "deactive" the chat when dismissing the contact, then this function will work properly, without any custom checks for `contact.Dismissed()`:
https://github.com/status-im/status-go/blob/5825d1cba51ab86397c50928832c467db2438512/protocol/messenger_handler.go#L2951-L2958

**Review by igor-sirotin — COMMENTED** [review]
Thanks, makes more sense now. But I'm still not sure of the implementation, please check my comments.

And thanks for the test, it should work no matter of the fix implementation.

File: protocol/messenger_handler.go (hunk 4 above)
Comment (jrainville) [reply protocol/messenger_handler.go:2198]: I did try to modify the `isMessageAllowedFrom` function and it had a bad side-effect. IIRC, it made it impossible to receive some other messages from them. I can try again to remember what was the issue, but what it made me realize is that function is badly named

Comment (igor-sirotin) [reply protocol/messenger_handler.go:2198]: Yeah modifying `isMessageAllowedFrom` is not needed I hope.
What I'm saying is that maybe we should set `chat.Active = false` when dismissing the contact 🤔

Comment (jrainville) [reply protocol/messenger_handler.go:2198]: > What I'm saying is that maybe we should set chat.Active = false when dismissing the contact 🤔

Yeah I guess it makes sense. Let's try

Comment (jrainville) [reply protocol/messenger_handler.go:2198]: I tried and it didn't work. The test fails so I guess it doesn't bock the messages correctly.

@igor-sirotin I still addressed your other comment and improved the test even more

**Review by igor-sirotin — APPROVED** [review]

**Comment by jrainville** [comment]
@osmaczko firnedly reminder to review

**Review by osmaczko — APPROVED** [review]
