### PR TITLE
fix(communities)_: Receiving mention notifications (@everyone) from spectated communities 

### LINKED ISSUE #14798: [Community] Receiving mention notifications (@everyone) from spectated communities
### Description

When spectating a community the `@everyone` mention will trigger a mention notification

Screenshot 2024-05-15 at 23 36 18

Steps to reproduce:
1. Import an open community with request to join active
2. Add a `@everyone` mention in the community from a member account

Expected behaviour:
The `@everyone` mention doesn't trigger a mention notification if the user is not a member

Actual behaviour:
The `@everyone` mention triggers a mention notification

### PR DESCRIPTION
**Pull request by friofry**
## Changes 
1. Moved existing logic about whether we need to show community chat notifications to the `showMentionOrReplyActivityCenterNotification` method.
2. Added an explicit check if the community is not joined. And not show notification in that case

## Demo:

https://github.com/status-im/status-go/assets/1083341/6245a742-be86-4f36-81cd-004aeabfdc77

Closes [#14798](https://github.com/status-im/status-desktop/issues/14798)

### CODE REVIEW

**Comment by friofry** [comment]
The PR has been updated:
1. Fixed conversion of communityId to bytes: `[]byte(communityID)` -> `types.DecodeHex(chat.CommunityID)`.
2. Fix checking membership before accepting join request (if there is no join request, joinedClock is 0)
```
if joinedClock == 0 || message.Clock < joinedClock 
```
3. Minor: fetch only the clock(8 bytes) from `communities_requests_to_join` (could be useful when fetching history, as it's checked for every message)

File: protocol/communities/manager.go [hunk 1]
```diff
@@ -3466,17 +3466,20 @@ func (m *Manager) GetRequestToJoinIDByPkAndCommunityID(pk *ecdsa.PublicKey, comm
 }
 
 func (m *Manager) GetCommunityRequestToJoinClock(pk *ecdsa.PublicKey, communityID string) (uint64, error) {
-	request, err := m.persistence.GetRequestToJoinByPkAndCommunityID(common.PubkeyToHex(pk), []byte(communityID))
+	id, err := types.DecodeHex(communityID)
```
Comment (MishkaRogachev) [inline protocol/communities/manager.go]: i suggest to name it `communityIDBytes`

File: protocol/messenger.go [hunk 2]
```diff
@@ -3560,13 +3560,13 @@ func (r *ReceivedMessageState) addNewActivityCenterNotification(publicKey ecdsa.
 	}
 
 	if chat.CommunityChat() {
-		joinedClock, err := m.communitiesManager.GetCommunityRequestToJoinClock(&publicKey, message.CommunityID)
+		// Ignore mentions & replies in community before joining
+		joinedClock, err := m.communitiesManager.GetCommunityRequestToJoinClock(&publicKey, chat.CommunityID)
```
Comment (MishkaRogachev) [inline protocol/messenger.go]: is it possible to add a test for it?

**Review by MishkaRogachev — COMMENTED** [review]
A few questions

File: protocol/messenger.go (hunk 2 above)
Comment (friofry) [reply protocol/messenger.go]: Yeah sure, it's work in progress at the moment

Comment (friofry) [reply protocol/messenger.go]: Actually, there is already a test `TestAliceDoesNotReceiveCommunityNotificationsBeforeJoined`.

It doesn't fail even when I undo this PR commit. 
So my idea was to test the following scenario
1. After community is **created** and **announced** to Alice. She should not see any mentions from Bob
2. When she **spectates** the community, she should get a message, but the activity centre should have no notifications
3. And after **joining** the community, she should see all mentions in the activity centre.

```
	s.advertiseCommunityTo(community, bob, alice)
	_, err := alice.SpectateCommunity(community.ID())
	s.Require().NoError(err)

	mentionMessage := common.NewMessage()
	mentionMessage.ChatId = chat.ID
	mentionMessage.ContentType = protobuf.ChatMessage_TEXT_PLAIN
	mentionMessage.Text = "Good news, @" + common.EveryoneMentionTag + " !"

	response, err = bob.SendChatMessage(context.Background(), mentionMessage)
	s.Require().NoError(err)

	response, err = WaitOnMessengerResponse(
		alice,
		func(r *MessengerResponse) bool {
			return len(r.Messages()) > 0
		},
		"no messages",
	)
	s.Require().NoError(err) <-- it doesn't receive any messages
```

Comment (friofry) [reply protocol/messenger.go]: Updated PR

Comment (friofry) [reply protocol/messenger.go]: One thing I don't understand and it's bothering me 

So, the test does the following:
1. Create a community with the default channel
2. Bob joins the community, alice is a spectator
3. Owner creates a new dummy channel (!)
4. Bob sends a message with a mention to the default channel
5. Alice gets the message, and she has no notifications in the activity center as expected
6. Alice joins the community, Bob sends another mention
7. Alice gets the message and an activity center notification. And all is good

I don't understand why the CHAT_MESSAGE is not handled/delivered in RetrieveAll if I skip step 3

**Review by jrainville — APPROVED** [review]
Nice job

File: protocol/communities_messenger_test.go [hunk 3]
```diff
@@ -4337,3 +4337,101 @@ func (s *MessengerCommunitiesSuite) TestMemberMessagesHasImageLink() {
...
+	}
+
+	response, err := s.owner.CreateCommunityChat(community.ID(), newChannel)
+	s.Require().NoError(err)
+	s.Require().Len(response.CommunityChanges, 1)
+	s.Require().Len(response.CommunityChanges[0].ChatsAdded, 1)
+	s.Require().Len(response.Communities(), 1)
+	s.Require().Len(response.Chats(), 1)
+
+	// Check Alice gets the correct member list for a new channel
```
Comment (mprakhov) [inline protocol/communities_messenger_test.go]: the comment tells to check member list, but you check channels count

File: protocol/communities_messenger_test.go [hunk 4]
```diff
@@ -4337,3 +4337,101 @@ func (s *MessengerCommunitiesSuite) TestMemberMessagesHasImageLink() {
...
+	advertiseCommunityTo(&s.Suite, community, s.owner, s.alice)
+	_, err := s.alice.SpectateCommunity(community.ID())
+	s.Require().NoError(err)
+
+	aliceCommunity, err := s.alice.GetCommunityByID(community.ID())
+	s.Require().NoError(err)
+	s.Require().Len(aliceCommunity.Chats(), 1)
+
+	// Owner creates a new channel
+	newChannel := &protobuf.CommunityChat{
```
Comment (mprakhov) [inline protocol/communities_messenger_test.go]: why do we need newChannel?

File: protocol/communities_messenger_test.go [hunk 5]
```diff
@@ -4337,3 +4337,101 @@ func (s *MessengerCommunitiesSuite) TestMemberMessagesHasImageLink() {
...
+	s.Require().Len(response.Messages(), 1)
+	s.Require().True(response.Messages()[0].Mentioned)
+	return response.Messages()[0]
+}
+
+func (s *MessengerCommunitiesSuite) TestAliceDoesNotReceiveMentionWhenSpectating() {
+	// GIVEN: Create an open community
+	community, communityChat := s.createCommunity()
+	s.Require().Len(community.Chats(), 1)
+	s.Require().False(community.Encrypted())
```
Comment (mprakhov) [inline protocol/communities_messenger_test.go]: There is a bug/inconsistency.
s.createCommunity() will create a community + chat and separate another chat.
The second chat will not be present in community, returned by `s.createCommunity()`
So you need to request community from DB and then advertise it to all other members

File: protocol/messenger.go (hunk 2 above)
Comment (mprakhov) [reply protocol/messenger.go]: answered https://github.com/status-im/status-go/pull/5180#discussion_r1608648440

File: protocol/communities_messenger_test.go (hunk 5 above)
Comment (MishkaRogachev) [reply protocol/communities_messenger_test.go]: do you mean this?
```
	community, err := s.owner.GetCommunityByID(community.ID())
	s.Require().NoError(err)
	s.Require().Len(community.Chats(), 2)
```
So the default community has 2 channels?

Comment (mprakhov) [reply protocol/communities_messenger_test.go]: yes, for that util... it needs to be fixed as it is confusing (I think I'll create a separate ticket tomorrow and will take a look on this issue)

File: protocol/communities_messenger_test.go (hunk 4 above)
Comment (friofry) [reply protocol/communities_messenger_test.go]: Alice doesn't get a message from B when I remove this part. Any advice on why this can happen is welcome

(described in the comment https://github.com/status-im/status-go/pull/5180#discussion_r1608439306)

File: protocol/communities_messenger_test.go (hunk 5 above)
Comment (friofry) [reply protocol/communities_messenger_test.go]: Fixed

File: protocol/communities_messenger_test.go (hunk 3 above)
Comment (friofry) [reply protocol/communities_messenger_test.go]: Fixed

File: protocol/communities_messenger_test.go [hunk 6]
```diff
@@ -4337,3 +4337,110 @@ func (s *MessengerCommunitiesSuite) TestMemberMessagesHasImageLink() {
...
+			Identity: &protobuf.ChatIdentity{
+				DisplayName: "new channel",
+				Emoji:       "",
+				Description: "chat created after joining the community",
+			},
+		}
+
+		_, err := s.owner.CreateCommunityChat(community.ID(), newChannel)
+		s.Require().NoError(err)
+	}
```
Comment (mprakhov) [inline protocol/communities_messenger_test.go]: you don't need dummy chat any more

Comment (mprakhov) [reply protocol/communities_messenger_test.go]: P.S. and check below can be removed

File: protocol/communities_messenger_test.go [hunk 7]
```diff
@@ -4337,3 +4337,110 @@ func (s *MessengerCommunitiesSuite) TestMemberMessagesHasImageLink() {
...
+	s.Require().NoError(err)
+	s.Require().Len(response.Messages(), 1)
+	s.Require().True(response.Messages()[0].Mentioned)
+	return response.Messages()[0]
+}
+
+func (s *MessengerCommunitiesSuite) TestAliceDoesNotReceiveMentionWhenSpectating() {
+	// GIVEN: Create an open community
+	community, communityChat := s.createCommunity()
+	community, err := s.owner.GetCommunityByID(community.ID())
```
Comment (mprakhov) [inline protocol/communities_messenger_test.go:4428]: Please, check that you have 2 chats in community

Comment (friofry) [reply protocol/communities_messenger_test.go:4428]: Done

**Review by osmaczko — APPROVED** [review]
Cool  :+1:

**Review by MishkaRogachev — APPROVED** [review]
Great work!

File: protocol/messenger.go (hunk 2 above)
Comment (friofry) [reply protocol/messenger.go]: I've fixed the test.
I just moved Bob to join the community after Alice starts spectating. And Alice waits for the community to be updated.

When Bob calls `joinCommunity`, it eventually calls `SaveAndPublish`, and on the Alice side it updates the community `persistence.SaveCommunity`.

**Review by mprakhov — APPROVED** [review]

**Comment by friofry** [comment]
quick update: 
These two tests failed because the community owner was Joined() but there was no RequestToJoin
* `TestEveryoneMentionTag`
* `TestMarkMessageWithNotificationAsUnreadInCommunityChatSetsNotificationAsUnread` 

I've added function `isCommunityJoinedBeforeClock` which first checks if user is joined and joined before message.clock. And if it's not joined than we check if it has request to join the community older that message.clcok

**Review by MishkaRogachev — APPROVED** [review]
