### PR TITLE
test_: flaky router tests fixed

### LINKED ISSUE #5601: Flaky test: `TestNoBalanceForTheBestRouteRouterV2/ERC20_transfer_-_No_Specific_FromChain_-_Specific_ToChain_-_Enough_Token_Balance_On_Arbitrum_Chain_But_Not_Enough_Native_Balance`
# Problem

```go
--- FAIL: TestNoBalanceForTheBestRouteRouterV2 (0.12s)
    --- FAIL: TestNoBalanceForTheBestRouteRouterV2/ERC20_transfer_-_No_Specific_FromChain_-_Specific_ToChain_-_Enough_Token_Balance_On_Arbitrum_Chain_But_Not_Enough_Native_Balance (0.00s)
        router_v2_test.go:218: 
                Error Trace:    /Users/igorsirotin/Repositories/Status/status-go/services/wallet/router/router_v2_test.go:218
                Error:          Not equal: 
                                expected: "{\"code\":\"WR-017\",\"details\":\"{\\\"token\\\": \\\"ETH\\\", \\\"chainId\\\": 1}\"}"
                                actual  : "{\"code\":\"WR-017\",\"details\":\"{\\\"token\\\": \\\"ETH\\\", \\\"chainId\\\": 42161}\"}"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -{"code":"WR-017","details":"{\"token\": \"ETH\", \"chainId\": 1}"}
                                +{"code":"WR-017","details":"{\"token\": \"ETH\", \"chainId\": 42161}"}
                Test:           TestNoBalanceForTheBestRouteRouterV2/ERC20_transfer_-_No_Specific_FromChain_-_Specific_ToChain_-_Enough_Token_Balance_On_Arbitrum_Chain_But_Not_Enough_Native_Balance
FAIL
FAIL    github.com/status-im/status-go/services/wallet/router   15.177s
FAIL

```

It's this test case:
https://github.com/status-im/status-go/blob/870ede082949d9f314cce45029a3c96857e8467a/services/wallet/router/router_v2_test_data.go#L2755

I guess the actual returned error is flaky because both Mainnet and Arbitrum balances are 0?
https://github.com/status-im/status-go/blob/870ede082949d9f314cce45029a3c96857e8467a/services/wallet/router/router_v2_test_data.go#L2779-L2781

### PR DESCRIPTION
**Pull request by saledjenic**
Closes https://github.com/status-im/status-go/issues/5601

### CODE REVIEW

File: services/wallet/router/router_v2.go [hunk 1]
```diff
@@ -189,6 +189,14 @@ func newSuggestedRoutesV2(
 	allRoutes := node.buildAllRoutesV2()
 	allRoutes = filterRoutesV2(allRoutes, amountIn, fromLockedAmount)
 
+	if len(allRoutes) > 0 {
```
Comment (ilmotta) [inline services/wallet/router/router_v2.go:192]: Are we sorting routes and candidates just to make test assertions more reliable or is there a requirement to sort? If it's because of the former, can we remove all the prod code added in this PR and only sort the expected & actual results in the test file?

Comment (saledjenic) [reply services/wallet/router/router_v2.go:192]: Sorting routes/paths should provide the same best route if there are more routes with the same cost. So that's one reason for adding sorting, this also helps solve test assertions.

> can we remove all the prod code added in this PR

I'm not sure which prod code are you exactly referring to in this PR?

Comment (ilmotta) [reply services/wallet/router/router_v2.go:192]: Prod code would be anything not in test files. I just had the impression we could fix the flakiness by sorting the results only in the test, thus keeping prod code unchanged. But if you think it's beneficial to sort then it's fine 👍🏼 Thanks @saledjenic

**Review by ilmotta — APPROVED** [review]

File: services/wallet/router/router_v2.go (hunk 1 above)
Comment (saledjenic) [reply services/wallet/router/router_v2.go:192]: Yes, that's what I thought as well at first, but in the example I shared here https://github.com/status-im/status-go/pull/5605#issuecomment-2255215560 you can see that 2 routes with 2 transactions each like this
```
route 1:
10 from mainnet
2 from optimism
```
and this
```
route 2:
2 from mainnet
10 from optimism
```
in theory, may have exactly the same fee, which means when we sort them we will always have the same route.

Comment (saledjenic) [reply services/wallet/router/router_v2.go:192]: Thanks for the review. :)

Comment (igor-sirotin) [reply services/wallet/router/router_v2.go:192]: I agree that sorting in prod is good to have, it will give idempotent results to the user as well

**Review by igor-sirotin — APPROVED** [review]
Thank you!
