### PR TITLE
fix(unfurl)_: The application crashes when generating status user profile link preview

### LINKED ISSUE #15297: The application crashes when generating status user profile link preview
# Bug Report
## Steps to reproduce

Paste link to status user profile to chat (we use this one for autotest - https://status.app/u/iwWACgoKCHNxdWlzaGVyAw==#zQ3shvMPZSyaUbjBjaNpNP1bPGsGpQDp59dZ4Gmz7UEy5o791)

#### Expected behavior

Link preview is generated and shown

#### Actual behavior

Link is generating but at some point the app crashes

### Additional Information

- Status desktop version: the latest master build
- Operating System: Mac OS Ventura 13.5

### PR DESCRIPTION
**Pull request by friofry**
It happened because `FetchContact` returned the contact and the error both nil 

Closes status-im/status-desktop#15297

https://github.com/status-im/status-go/assets/1083341/04f943c6-010c-4636-a860-249d03308638

### CODE REVIEW

File: protocol/messenger_storenode_request_test.go [hunk 1]
```diff
@@ -633,6 +633,20 @@ func (s *MessengerStoreNodeRequestSuite) TestRequestProfileInfo() {
...
+func (s *MessengerStoreNodeRequestSuite) TestRequestProfileInfoError() {
+	s.createOwner()
+	defer s.tearDownOwner()
+	// Non-existent contact used by QA team for e2e autotests: (https://github.com/status-im/status-desktop/issues/15297)
+	fetchedContact, err := s.owner.FetchContact("0x04e972b2a794c315e16411fc0930a65bffffe4f885341683f4532fbbd883a447d849ac0be63d6a4f721affa0d0408160974ff831408433972de2c4556ef06d1ae1", true)
+	s.Require().Nil(fetchedContact)
+	s.Require().Error(err)
+
+	u := "https://status.app/u/iwWACgoKCHNxdWlzaGVyAw==#zQ3shvMPZSyaUbjBjaNpNP1bPGsGpQDp59dZ4Gmz7UEy5o791"
+	response, err := s.owner.UnfurlURLs(nil, []string{u})
```
Comment (friofry) [inline protocol/messenger_storenode_request_test.go:645]: I use this test suite because Unfurl fetches the contact from store node if it's not found locally.
 
```
Unfurl -> buildContactData -> FetchContact (from StoreNode)
```

**Review by jrainville — APPROVED** [review]

**Review by mprakhov — APPROVED** [review]

File: protocol/messenger_storenode_request_test.go (hunk 1 above)
Comment (igor-sirotin) [reply protocol/messenger_storenode_request_test.go:645]: This is the right place for such a test 👍 
It allows to request from a in-memory store node, not from real fleet.

File: protocol/messenger_contacts.go [hunk 2]
```diff
@@ -1323,7 +1323,14 @@ func (m *Messenger) FetchContact(contactID string, waitForResponse bool) (*Conta
 		WithWaitForResponseOption(waitForResponse),
 	}
 	contact, _, err := m.storeNodeRequestsManager.FetchContact(contactID, options)
-	return contact, err
+	if err != nil {
+		return nil, err
+	}
+
+	if contact == nil {
+		return nil, ErrContactNotFound
```
Comment (igor-sirotin) [inline protocol/messenger_contacts.go]: I wonder if this is the right solution 🤔 

The idea of returning `nil` was to explicitly show that there was no error during requests. Just the contact not found. So both return args were `nil`.

Yes, we use `ErrContactNotFound` in some places. Just to prevent checking both `err` and `contact`. I'm personally not both hands on this idea. At some upper levels maybe yes, but not on lower levels.

I believe right now all of the usages of `FetchContact` and `FetchCommunity` expect `nil, nil` to be returned when the content wasn't found. It's noted in the function description:
https://github.com/status-im/status-go/blob/b1433e6bfa8406fb31017e86be53bf8dca12d439/protocol/messenger_store_node_request_manager.go#L76

So maybe in this case we could just check the returned value in `UnfurlURLs` to prevent regressions?

Comment (friofry) [reply protocol/messenger_contacts.go]: Thanks for clarification! I'll fix it

Comment (friofry) [reply protocol/messenger_contacts.go]: done

File: protocol/linkpreview_unfurler_status.go [hunk 3]
```diff
@@ -59,7 +59,7 @@ func (u *StatusUnfurler) buildContactData(publicKey string) (*common.StatusConta
 
 	// If no contact found locally, fetch it from waku
 	if contact == nil {
-		if contact, err = u.m.FetchContact(contactID, true); err != nil {
+		if contact, err = u.m.FetchContact(contactID, true); contact == nil || err != nil {
 			return nil, fmt.Errorf("failed to request contact info from mailserver for public key '%s': %w", publicKey, err)
```
Comment (igor-sirotin) [inline protocol/linkpreview_unfurler_status.go:64]: Just a minor thing: maybe makes sense to separate the checks?
Otherwise when contact not found it will be `failed to request contact info from mailserver for public key '0xdeadbeef': nil` 😄

File: protocol/messenger_store_node_request_manager.go [hunk 4]
```diff
@@ -150,6 +150,8 @@ func (m *StoreNodeRequestManager) FetchCommunities(communities []communities.Com
 	return outErr
 }
 
+// FetchContact - similar to FetchCommunity
```
Comment (igor-sirotin) [inline protocol/messenger_store_node_request_manager.go:153]: 👍

**Review by igor-sirotin — APPROVED** [review]

File: protocol/linkpreview_unfurler_status.go (hunk 3 above)
Comment (friofry) [reply protocol/linkpreview_unfurler_status.go:64]: Now should be pretty enough :)

**Review by igor-sirotin — APPROVED** [review]
