### PR TITLE
fix(messenger_communities): block messages and reactions to token gated or spectated communities

### LINKED ISSUE #11915: Able to send reaction in token gated communities
Members not yet approved in the communities are able to send reaction to message

Expected: they should not be able to react

### PR DESCRIPTION
**Pull request by shinnok**
Right now, if the QML UI control checks are disabled, the user can send messages to spectated, non-joined and, possibly, token-gated communities with _invalid tokens_?

Right now the PR is in draft stage with possible code culprits.

---
Closes https://github.com/status-im/status-desktop/issues/11915

### CODE REVIEW

File: protocol/communities/community.go [hunk 1]
```diff
@@ -902,6 +902,7 @@ func (o *Community) Leave() {
 
 func (o *Community) Spectate() {
 	o.config.Spectated = true
+	o.config.Joined = false // this doesn't seem to fix anything, but looks proper to do
```
Comment (jrainville) [inline protocol/communities/community.go]: This is probably not needed. It defaults to false. We can keep it or not.

File: protocol/communities/community.go [hunk 2]
```diff
@@ -1605,6 +1606,11 @@ func (o *Community) CanPost(pk *ecdsa.PublicKey, chatID string, grantBytes []byt
 		return false, nil
 	}
 
+	// this resolves the issue, however, I'm not sure how it should play with grants and tokens below
+	if !o.isMember() {
```
Comment (jrainville) [inline protocol/communities/community.go]: That looks right. We don't need to check the tokens or whatever if this condition doesn't pass. If someone is not a member, they cannot post.

File: protocol/messenger.go [hunk 3]
```diff
@@ -2218,13 +2218,18 @@ func (m *Messenger) sendChatMessage(ctx context.Context, message *common.Message
...
 		}
+	} else if len(message.AudioPath) != 0 {
+		err := message.LoadAudio()
+		if err != nil {
+			return nil, err
+		}
+	}
 
-	} else if len(message.CommunityID) != 0 {
+	if len(message.CommunityID) != 0 {
```
Comment (jrainville) [inline protocol/messenger.go]: I think this code path is only to send an invitation to the community. So it's probably not the culprit

**Review by jrainville — COMMENTED** [review]
The line in `CanPost` seems like the right culprit for the Sender side.

We should also do a similar check on the receiver side.
The entry point for that is in `messenger_handlers.go` > `dispatchToHandler`. 
That's where we dispatch the received message to the right handler. 
In this case, it would be `handleChatMessageProtobuf`.

Pro tip: using `fmt.Println("...")`  is a good way to add logs to status-go that will show up in the console when running Status Desktop.

But even better is using the Go tests. You'll find a lot of useful tests in `community_test.go`. For example `TestCanPost`. `TestValidateRequestToJoin` might be a good one to validate that messages only work for those joined, but maybe it's better to create a new test case.

File: protocol/communities/community.go (hunk 1 above)
Comment (shinnok) [reply protocol/communities/community.go]: Reverted.

File: protocol/messenger.go (hunk 3 above)
Comment (shinnok) [reply protocol/messenger.go]: I tried to split the logic here a bit, so it's more obvious what we're checking for. Will keep this bit.

**Comment by shinnok** [comment]
I can't get the `SendPinMessage()` call to go through even though I have `PinMessageAllMembersEnabled` set to **true**.

[`39789d9` (#4064)](https://github.com/status-im/status-go/pull/4064/commits/39789d9a80d212ccd611835a20ece38e61da1704#diff-d4f4b1d3dcfd1f9dda7f6d7a397650c30b499042a7770a1df9a6fe80d61f04feR441)

https://github.com/status-im/status-go/blob/fix/11915/send-message-to-gated-community/protocol/messenger_pin_messages.go#L42

Not sure how critical it is to get the `TestPinMessageInCommunityChat` working for this particular issue, thus I'm enabling this PR for review and also welcome to help on investigating why isn't the community message pin working in the test suite, when it is fine otherwise.

File: protocol/communities_messenger_test.go [hunk 4]
```diff
@@ -436,12 +436,37 @@ func (s *MessengerCommunitiesSuite) TestCommunityContactCodeAdvertisement() {
 	s.Require().NoError(err)
 }
 
-func (s *MessengerCommunitiesSuite) TestPostToCommunityChat() {
+func (s *MessengerCommunitiesSuite) TestPinMessageInCommunityChat() {
 	community, chat := s.createCommunity()
+	community.AdminSettings().PinMessageAllMembersEnabled = true // FIXME: this doesn't work
 
 	s.advertiseCommunityTo(community, s.alice)
+	s.alice.SpectateCommunity(community.ID()) // TODO: also test in stages like TestPostToCommunityChat
```
Comment (osmaczko) [inline protocol/communities_messenger_test.go]: This line seems unnecessary, there is no strict requirement to spectate before joining.

File: protocol/communities_messenger_test.go [hunk 5]
```diff
@@ -436,12 +436,37 @@ func (s *MessengerCommunitiesSuite) TestCommunityContactCodeAdvertisement() {
 	s.Require().NoError(err)
 }
 
-func (s *MessengerCommunitiesSuite) TestPostToCommunityChat() {
+func (s *MessengerCommunitiesSuite) TestPinMessageInCommunityChat() {
```
Comment (osmaczko) [inline protocol/communities_messenger_test.go]: No one can prevent a peer from sending a pinned message in the community channel (someone might modify the status-go source code for their client). We should also check on the receiver's side to ensure that pinned messages from non-approved members are rejected.

File: protocol/communities_messenger_test.go [hunk 6]
```diff
@@ -436,12 +436,37 @@ func (s *MessengerCommunitiesSuite) TestCommunityContactCodeAdvertisement() {
...
 	community, chat := s.createCommunity()
+	community.AdminSettings().PinMessageAllMembersEnabled = true // FIXME: this doesn't work
```
Comment (osmaczko) [inline protocol/communities_messenger_test.go]: This doesn't work because the changes aren't saved. When a community is advertised to the user, only the community ID is propagated. Then, when constructing the community message, it is fetched from the database.

**Review by osmaczko — COMMENTED** [review]
Looks good in general :+1: some minor things to address.

File: protocol/messenger.go [hunk 7]
```diff
@@ -2241,11 +2244,6 @@ func (m *Messenger) sendChatMessage(ctx context.Context, message *common.Message
 		message.Payload = &protobuf.ChatMessage_Community{Community: wrappedCommunity}
 
 		message.ContentType = protobuf.ChatMessage_COMMUNITY
-	} else if len(message.AudioPath) != 0 {
-		err := message.LoadAudio()
-		if err != nil {
-			return nil, err
-		}
```
Comment (jrainville) [inline protocol/messenger.go]: The changes above can be reverted

**Review by jrainville — COMMENTED** [review]
Code looks good, though there is a small cleanup needed.

As we discussed in our 1-1, the Pin message test can be added in another PR, because it seems like the Setting to let users pin in a community is not being saved correctly on the receiver side, so it's worth another issue.

**Comment by osmaczko** [comment]
> it seems like the Setting to let users pin in a community is not being saved correctly on the receiver side

I believe the root cause is different: https://github.com/status-im/status-go/pull/4064#discussion_r1350782701

**Comment by jrainville** [comment]
> > it seems like the Setting to let users pin in a community is not being saved correctly on the receiver side
> 
> I believe the root cause is different: [#4064 (comment)](https://github.com/status-im/status-go/pull/4064#discussion_r1350782701)

Yeah I know. When I was in the 1-1 with him, we did add the `saveCommunity` call. Even though I checked that the owner's DB did have the right value afterwards, Alice's DB didn't have it. So, it seems like maybe members don,t save settings correctly?

Or maybe we do not publish community settings with `advertiseCommunity`?

**Comment by osmaczko** [comment]
> > > it seems like the Setting to let users pin in a community is not being saved correctly on the receiver side
> > 
> > 
> > I believe the root cause is different: [#4064 (comment)](https://github.com/status-im/status-go/pull/4064#discussion_r1350782701)
> 
> Yeah I know. When I was in the 1-1 with him, we did add the `saveCommunity` call. Even though I checked that the owner's DB did have the right value afterwards, Alice's DB didn't have it. So, it seems like maybe members don,t save settings correctly?
> 
> Or maybe we do not publish community settings with `advertiseCommunity`?

The `saveCommunity` should be executed on the control node side before it is advertised to the users. The admin settings are a part of the `CommunityDescription`. The description sent by the control node should be identical on the receiver side because the proto lib handles unmarshaling. I would try to investigate what admin settings (`CommunityDescription`) is distributed exactly.

File: protocol/communities_messenger_test.go (hunk 6 above)
Comment (shinnok) [reply protocol/communities_messenger_test.go]: Moved the `TestPinMessageInCommunityChat` and afferent investigation to https://github.com/status-im/status-go/pull/4139.

File: protocol/communities_messenger_test.go (hunk 5 above)
Comment (shinnok) [reply protocol/communities_messenger_test.go]: This is fixed for both sender and receiver in my testing. Check out the consolidated fixes in final commit dace1b28d8510bc9514ff4661928d2fb5c0302e6.

File: protocol/messenger.go (hunk 7 above)
Comment (shinnok) [reply protocol/messenger.go]: Done. Check consolidated changes in dace1b28d8510bc9514ff4661928d2fb5c0302e6.

**Comment by shinnok** [comment]
I've created issue https://github.com/status-im/status-go/issues/4138 to further investigate the channel message pin issue and forked the new test method `TestPinMessageInCommunityChat` to PR https://github.com/status-im/status-go/pull/4139.

---

The current squashed commit contains the sufficient changes to block messages, reactions and pins to channels for which the user is not a member, both for him and other members. Please review again.

**Review by osmaczko — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

File: protocol/communities/community_test.go [hunk 8]
```diff
@@ -483,18 +483,30 @@ func (s *CommunitySuite) TestValidateRequestToJoin() {
...
+
+//FIXME: add complete permissions matrix
+// | Community Perm | Chat Perm | Chat Member | Grant   | Can Post |
+// |----------------|-----------|-------------|---------|----------|
+// | MEMBERSHIP     | x         | Yes         | -       | Yes      |
+// | MEMBERSHIP     | x         | No          | -       | No       |
+// | NO-MEMBERSHIP  | x         | Yes         | -       | Yes      |
+// | NO-MEMBERSHIP  | x         | No          | -       | No       |
+// | NO-MEMBERSHIP  | x         | No          | Valid   | Yes?     |
+// | NO-MEMBERSHIP  | x         | No          | Invalid | No       |
```
Comment (jrainville) [inline protocol/communities/community_test.go]: @cammellos can you shortly explain what a grant is? I feel like it's probably something from an old requirement, but I don't remember seeing it in any of the new requirements or code.

I'm of the opinion that if someone is not part of the member list, they shouldn't be able to post ever. However, this test below seems to imply that with a grant, it should be possible. Is that still something we want? If not, might as well remove all the grant code I guess?

cc @John-44 to clarify requirements. Basically, am I correct that you 100% need to be a member of a community/chat to be able to post to it?

File: protocol/communities_messenger_test.go (hunk 5 above)
Comment (shinnok) [reply protocol/communities_messenger_test.go]: To expand on the matter a bit, both a community and individual chats of access permissions of these type:
https://github.com/status-im/status-go/blob/fix/11915/send-message-to-gated-community/protocol/protobuf/communities.pb.go

On top of that, there is the distinction that a user is a member, or not, of a community and then an individual chat. A user becomes a member of a Community when it is first advertised by another user B and A requests to join. Then what happens to A's request to join depends on _Community.Access.Permission_. After joining, when A attempt a post, the protocol code decides whether to allow a post, a reaction or a pin, based on _Community.Chat.Access.Permission._ Please correct if any of these is incorrect.

Now, where do grants fit in? As I could not find either documentation nor help pages describing what it is, nor the code hints seems to be implemented fully:

[`156bf39` (#4064)](https://github.com/status-im/status-go/pull/4064/commits/156bf3942a7d2ecf855628fa6aad82c03072f50d)

File: protocol/communities/community_test.go (hunk 8 above)
Comment (jrainville) [reply protocol/communities/community_test.go]: I just discussed this with @cammellos and he said:
> so, the idea is that when you join a community, you get a "grant"
and that's a proof you have been added
so when you send a message, you send also the grant
so other clients can optimistically process the message, if the community description hasn't reached them yet

But it turns out we never fully supported it anyway:
> we never really supported it

He then told me it's fine to remove it.

I'll open an issue in a few.

@shinnok that means you can just set the grant tests to `canPost: false`, so that the test will pass. Then someone will have the chore of removing the grant code that's no longer useful later.

Comment (jrainville) [reply protocol/communities/community_test.go]: I added the issue to remove the grant code here: https://github.com/status-im/status-go/issues/4180

Comment (shinnok) [reply protocol/communities/community_test.go]: I adjusted the expected result for the sub-tests that are supposed to fail in TestCanPost().

File: protocol/communities/community.go [hunk 9]
```diff
@@ -1742,6 +1742,12 @@ func (o *Community) CanPost(pk *ecdsa.PublicKey, chatID string, grantBytes []byt
 		return false, nil
 	}
 
+	// if not a member can't post or react on message
+	if !o.IsMemberInChat(pk, chatID) {
```
Comment (jrainville) [inline protocol/communities/community.go]: The condition `if o.config.CommunityDescription.Members == nil {` at line 1780 (the comment on it seems not ok) should be moved above this one or merged with this one.

**Review by jrainville — COMMENTED** [review]
Looks good, the order of conditions in `canPost` can be improved a little

File: protocol/messenger_activity_center_test.go
Comment (osmaczko) [inline protocol/messenger_activity_center_test.go:1]: Thanks for cleanup.

**Review by osmaczko — APPROVED** [review]
:+1:

**Comment by shinnok** [comment]
Attaching a video showing the changes in effect, the top left Status instance has adjustments in this PR in place, the bottom right doesn't, but instead has the QML UI checks disabled for sending, reacting and pinning. This effectively verifies that the receiving side effectively blocks non-member actions, however, once applied, this patch also denies non-member actions on the sender's side for efficiency. Testing this exact same workflow without this patch on either side, but with the [UI checks disabled](https://github.com//status-im/status-desktop/tree/fix/11915/send-message-to-gated-community), will allow a non-member to send, react and pin before being approved in a on-request community or before spectating for no-request community.

https://github.com/status-im/status-go/assets/544446/870f70ec-0a10-4ba0-97a5-327b3f95243d

* video is encoded to H.265/HEVC due to size/length, might help to download and play with VLC/Mplayer instead of the browser *
