### PR TITLE
fix: endless send loop if RawMessage was stored to DB with invalid ID

### LINKED ISSUE #15466: Ping-pong loop if HandleCommunityRequestToJoinResponse returns an error
# Bug Report

## Description
Precondition:
Community with minted owner token. Member A is a TokenMaster

1. Member A sends the request to join to the control node (message 1)
2. The control node receives a request to join from member A (message 1) handles it and sends a response to member A (message 2)
3. Member A while handling the request to join response (message 2) returned an error (it could happen, if `CommunityDescription` update will be received before request to join response)

If this sequence is met, we will have a ping pong loop with steps 2, 3

Repro steps are unclear so far. Was not able to reproduce it again, but have 2 accounts with stable reproduce
The interesting part is that for step 3 the control node doesn't need to be online. I have a loop of receiving community request to join response
Step 2 requires member A node to be online

## Steps to reproduce

Unknown

See  a description

### Additional Information

- Status desktop version: latest master `7146d5af5b6643965dd83d1836740321e7b73b7c`
- Operating System: macos

### PR DESCRIPTION
**Pull request by mprakhov**
During sending `RawMessage`, we calculate ID.
If `RawMessage` with ID `A` was not stored to `raw_messages` after the send and msg A `payload/sender/type` data was changed and stored to the DB, next time we will try to send this msg, it will calculate msg ID as `B` due to changed content and `upsertRawMessageToWatch` will never increase `send_count` for message A, and it will be sending in the loop all the time

Important changes:
- [x] validate `RawMessage` on `ID` change before adding to  `raw_messages`
- [x] do not send `RawMessage` if the `ID` was changed
- [x] fixed RequestToJoinCommunity logic which leads to the loop

Closes # https://github.com/status-im/status-desktop/issues/15466

### CODE REVIEW

**Comment by mprakhov** [comment]
Note: I'm working under tests, but it would be nice to review PR meantime

File: protocol/messenger_communities.go [hunk 1]
```diff
@@ -1490,48 +1490,51 @@ func (m *Messenger) RequestToJoinCommunity(request *requests.RequestToJoinCommun
...
-			_, err := m.sender.SendPrivate(context.Background(), member, &rawMessage)
+		for _, member := range rawMessage.Recipients {
+			_, err := m.sender.SendPrivate(context.Background(), member, rawMessage)
 			if err != nil {
 				return nil, err
 			}
 		}
-	}
 
-	if _, err = m.UpsertRawMessageToWatch(&rawMessage); err != nil {
```
Comment (mprakhov) [inline protocol/messenger_communities.go:1549]: This was the root cause of the loop.
There were no privileged members, but RawMessage was modified and stored to the DB, what invalidate prev ID and during SendPrivate we calculated different ID

**Review by jrainville — APPROVED** [review]
Very good job! This looked super hard to find :clap:

**Comment by mprakhov** [comment]
@richard-ramos I need help with test
There is an existing test: `TestMessageSent`. It was false-positive as it doesn't test if msg was sent. After [fixing the condition](https://github.com/status-im/status-go/pull/5515/files#diff-4fa8249e4f267412d19f6cc7ad1cc7e2d1459f471120acdf64d460478ee4cd0cR221) test become flaky

I did some investigation and found out, that during the failure, in `messageHashBasedQuery` `w.node.Store()` returns 0 messages and we send the envelope event as Expired, so this message is not marked as sent

image

Where do we add messages to this `w.node.Store()`? Could it be an invalid test configuration or a bug in the code?
Note: it does not related to my changes in this PR, if you'll take the latest `develop` and [fix the condition](https://github.com/status-im/status-go/pull/5515/files#diff-4fa8249e4f267412d19f6cc7ad1cc7e2d1459f471120acdf64d460478ee4cd0cR221)  test will became flaky

**Comment by richard-ramos** [comment]
> Where do we add messages to this w.node.Store()? Could it be an invalid test configuration or a bug in the code?

`w.node.Store()` is used to retrieve messages from a store node, in this case by using the message hash. 

IMO you should not have this feature enabled for this test. This functionality can be disabled by using this flag when instantiating waku: https://github.com/status-im/status-go/blob/d07f9b5b162c078f71bf19a189e2e26c118a0db4/wakuv2/config.go#L68 

Otherwise you would have to use your own store node like it is done in  `TestWakuV2Store` in wakuv2/waku_test.go

**Comment by kaichaosun** [comment]
@mprakhov the solution richard provides sounds good, another option is remove `rawMessage.Sent` condition since sent status is set only if store hash query success in relay mode.

**Comment by qfrank** [comment]
Sorry for the delay to review, I had been off for a few days before, will take a look today, thanks for the PR @mprakhov

File: api/messenger_raw_message_resend_test.go [hunk 2]
```diff
@@ -208,34 +209,44 @@ func (s *MessengerRawMessageResendTest) setCreateAccountRequest(displayName, roo
...
-
-	err = tt.RetryWithBackOff(func() error {
-		rawMessage, err := s.bobMessenger.RawMessageByID(ids[0])
+func (s *MessengerRawMessageResendTest) waitForMessageSent(messageID string) {
+	err := tt.RetryWithBackOff(func() error {
+		rawMessage, err := s.bobMessenger.RawMessageByID(messageID)
 		s.Require().NoError(err)
 		s.Require().NotNil(rawMessage)
-		if rawMessage.SendCount > 0 {
+		if rawMessage.SendCount > 1 {
```
Comment (qfrank) [inline api/messenger_raw_message_resend_test.go]: why changed `> 0` to `> 1` ? if `SendCount > 1` it means resending happened, no? There was a comment before:
`TestMessageSent tests if ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN is in state `sent` without resending` , when I wrote the test `TestMessageSent`, I just want to ensure that there will be a rawmessage record in db table after sending the message. When the rawmessage get saved to db table first time, the initial value of SendCount should be 1, now the function is more like `waitForMessageReSent`?

File: protocol/messenger_communities.go [hunk 3]
```diff
@@ -1880,22 +1883,47 @@ func (m *Messenger) CancelRequestToJoinCommunity(ctx context.Context, request *r
 		return nil, err
 	}
 
+	// NOTE: rawMessage.ID is generated from payload + sender + messageType
+	// rawMessage.ID will be the same for control node and privileged members, but for
+	// community without owner token resend type is different
+	// in order not to override msg to control node by message for privileged members,
+	// we skip storing the same message for privileged members
+	skipUpsertForPrivilegedMembers := community.AutoAccept() || rawMessage.ResendMethod != common.ResendMethodSendPrivate
+	if skipUpsertForPrivilegedMembers {
```
Comment (qfrank) [inline protocol/messenger_communities.go]: this variable name confused me, maybe you meant `notSkipUpsertForPrivilegedMembers`?

File: api/messenger_raw_message_resend_test.go (hunk 2 above)
Comment (mprakhov) [reply api/messenger_raw_message_resend_test.go]: A small problem with this test related to the request to join.
So, in this test suite, you didn't provide revealed addresses during the request to join. This will lead to having 2 messages with the same messageID. One will be sent to community PK, and another to the owner without PK.
So sending and upsert 2 same messages will lead to 2, that's why I changed it to 1. 
Note: I'm working on PR, where we do not allow to do request to join without revealed addresses, this broke a lot of tests, but after the fix, the described issue will not be a problem and the test must fail due to > 1.

Now I understand what you were trying to do. Comment `TestMessageSent tests if ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN is in state sent without resending` confused me and I thought you were expecting to receive sent status for the envelope and store msg as sent. Only in this case we can be sure, that msg will not be resent

File: protocol/messenger_communities.go (hunk 3 above)
Comment (mprakhov) [reply protocol/messenger_communities.go]: will rename to `skipAddPrivilegedMembersRawMessageToWatch`

File: api/messenger_raw_message_resend_test.go (hunk 2 above)
Comment (mprakhov) [reply api/messenger_raw_message_resend_test.go]: returned to 0

File: protocol/messenger_communities.go (hunk 3 above)
Comment (mprakhov) [reply protocol/messenger_communities.go]: renamed

File: protocol/messenger_communities.go [hunk 4]
```diff
@@ -1885,22 +1888,47 @@ func (m *Messenger) CancelRequestToJoinCommunity(ctx context.Context, request *r
...
 
+	// NOTE: rawMessage.ID is generated from payload + sender + messageType
+	// rawMessage.ID will be the same for control node and privileged members, but for
+	// community without owner token resend type is different
+	// in order not to override msg to control node by message for privileged members,
+	// we skip storing the same message for privileged members
+	skipAddRawMessageToWatchForPrivilegedMembers := community.AutoAccept() || rawMessage.ResendMethod != common.ResendMethodSendPrivate
+	if skipAddRawMessageToWatchForPrivilegedMembers {
+		if _, err = m.AddRawMessageToWatch(&rawMessage); err != nil {
+			return nil, err
```
Comment (qfrank) [inline protocol/messenger_communities.go:1899]: skipAddRawMessageToWatchForPrivilegedMembers is true, but you're still trying to `AddRawMessageToWatch`, shouldn't it be something like?
```
if !skipAddRawMessageToWatchForPrivilegedMembers {
   m.AddRawMessageToWatch ...
```

Comment (qfrank) [reply protocol/messenger_communities.go:1899]: that's why the name confused me🤔

File: api/messenger_raw_message_resend_test.go (hunk 2 above)
Comment (qfrank) [reply api/messenger_raw_message_resend_test.go]: > Note: I'm working on PR, where we do not allow to do request to join without revealed addresses, this broke a lot of tests, but after the fix, the described issue will not be a problem and the test must fail due to > 1.

so you will update the test as well in that PR right?

Comment (qfrank) [reply api/messenger_raw_message_resend_test.go]: > returned to 0

?

**Review by qfrank — APPROVED** [review]
overall LGTM, left minor questions

**Comment by pavloburykh** [comment]
Hey @mprakhov! Do we have a Desktop PR? I want to test these changes on mobile side https://github.com/status-im/status-mobile/pull/20848 but I need updated Desktop build as well. Or should I test joining communities against Desktop nightly builds?

**Comment by mprakhov** [comment]
@pavloburykh I will create a desktop PR

File: protocol/messenger_communities.go (hunk 4 above)
Comment (mprakhov) [reply protocol/messenger_communities.go:1899]: No, please, take a look at Note

```
// NOTE: rawMessage.ID is generated from payload + sender + messageType
// rawMessage.ID will be the same for the control node and privileged members, but for
// community without owner token resend type is different
// in order not to override msg to control node by message for privileged members,
// we skip storing the same message for privileged members
```

**Comment by mprakhov** [comment]
@pavloburykh status-desktop PR https://github.com/status-im/status-desktop/pull/15724

**Comment by mprakhov** [comment]
> so you will update the test as well in that PR right?

Yes, right

File: protocol/messenger_communities.go (hunk 4 above)
Comment (qfrank) [reply protocol/messenger_communities.go:1899]: no, the naming shouldn't be relate to the comment, let's just think about the variable name,
```
if skipAddRawMessageToWatchForPrivilegedMembers {
   // we shouldn't invoke m.AddRawMessageToWatch as it means skip AddRawMessageToWatch ...
}
```

Comment (mprakhov) [reply protocol/messenger_communities.go:1899]: Are you missing another part - ForPrivilegedMembers? :)
So the logic is 
- if we send a message to community ID - we will store msg and skip storing it for privileged members
- if we send a message as a private - that means that the community with minted owner token and receiver will be the owner pubkey, and the owner pubkey will be added to the recipients during sending a message to privileged members

Anyway, I'm ok to rename, just point out how you want to name this variable :)

Comment (qfrank) [reply protocol/messenger_communities.go:1899]: what about `avoidDuplicateWatchingForPrivilegedMembers`? :)

**Comment by pavloburykh** [comment]
@mprakhov thanks. smoke checked on [mobile](https://github.com/status-im/status-mobile/pull/20848#issuecomment-2245143898), no issues from my side. 

I believe this PR requires more deep testing by Desktop QA team.

File: protocol/messenger_communities.go (hunk 4 above)
Comment (mprakhov) [reply protocol/messenger_communities.go:1899]: renamed
