### PR TITLE
Fix contact details large image is always empty

### LINKED ISSUE #13563: [Profile] Contact details' `largeImage` is always empty
# Bug Report

Profile:
image

Chat:
image

## Description
~~Looks like a regression from https://github.com/status-im/status-desktop/pull/13197 ; `getContactDetailsAsJson.largeImage`~~ (and maybe other image related fields) always returns an empty string

### Additional Information

- Status desktop version: master
- Operating System: linux

### PR DESCRIPTION
**Pull request by kounkou**
### Description

fixes https://github.com/status-im/status-desktop/issues/13563

The current code contains a bug where a 1:1 chat is incorrectly assigned a context of "Public chat." According to the existing logic:

> When the context is 'public-chat', only the 'thumbnail' IdentityImage is attached.
When the context is 'private-chat', all IdentityImages are attached.

As a consequence, messages with the ChatIdentity have only one image (thumbnail), leading to the large image being consistently empty on the client receiver side.

This PR corrects this behavior by ensuring that 1:1 chats are correctly assigned the 'private-chat' context, allowing all IdentityImages to be attached to messages, thus resolving the issue of the large image being empty.

### What does the PR do

The PR uses the ChatType store inside the chat passed in parameter, and uses the correct ChatType before adding the chatIdentity.

### Screenshot of functionality (including design for comparison)

[testing.webm](https://github.com/status-im/status-go/assets/2589171/0e1be89c-c144-4901-982d-cfe1c6d5eb21)

### CODE REVIEW

File: protocol/chat.go [hunk 1]
```diff
@@ -636,3 +636,12 @@ func stringSliceContains(slice []string, item string) bool {
 	}
 	return false
 }
+
+func ConvertChatType(chatType ChatType) chatContext {
```
Comment (jrainville) [inline protocol/chat.go]: `ConvertChatType` might not be the best name. It conveys that we are changing the type from what it was before to something else, but this is more a mapping.

I suggest instead something like `GetChatContextFromChatType`

File: protocol/messenger_test.go [hunk 2]
```diff
@@ -2484,6 +2484,22 @@ func (t *testTimeSource) GetCurrentTime() uint64 {
...
+
+	err = s.m.handleStandaloneChatIdentity(chat)
+	s.NoError(err)
+
+	chat = CreateOneToOneChat("test-private-chat", &s.privateKey.PublicKey, s.m.transport)
+	err = s.m.SaveChat(chat)
+	s.NoError(err)
+
+	err = s.m.handleStandaloneChatIdentity(chat)
+	s.NoError(err)
```
Comment (jrainville) [inline protocol/messenger_test.go]: Here we could add an assert to check that the large image is there

**Review by jrainville — COMMENTED** [review]
Nice find. Some small suggestions

**Comment by kounkou** [comment]
Thanks for the review, still fixing some linting issues though. I'll add second reviewer after everything is passing.

File: protocol/messenger_test.go (hunk 2 above)
Comment (kounkou) [reply protocol/messenger_test.go]: > Here we could add an assert to check that the large image is there

That's right, working on a proper test here.

---------------

I am now done with the testing, I believe these tests will help catch any future regressions on this topic.

File: protocol/chat.go [hunk 3]
```diff
@@ -31,6 +31,8 @@ var chatColors = []string{
 
 type ChatType int
 
+type ChatContext string
```
Comment (igor-sirotin) [inline protocol/chat.go:34]: does this need to be public? seems to be only used in `protocol` package.
```suggestion
type chatContext string
```

**Review by igor-sirotin — APPROVED** [review]
Good finding! 👏

File: protocol/chat.go (hunk 3 above)
Comment (kounkou) [reply protocol/chat.go:34]: Yes, to my knowledge it should be possible normally to use `chatContext` instead of `ChatContext` to make sure the type isn't exported from the package, however, I get a golint error 😢  It must be a misconfiguration in the linting, I suspect the files in the package are compile independently or something. Is this blocking?

Comment (igor-sirotin) [reply protocol/chat.go:34]: Weird, but not blocking of course 🙂

**Review by jrainville — APPROVED** [review]
