### PR TITLE
fix(backup)_: do not show the backup notifi backup during normal fetch

### LINKED ISSUE #17555: Fetching profile details notification shown after account creation
# Bug Report

## Description

There is a notification about "Fetching profile details" after creating an account with fresh keys (password). This is unexpected as there will be no profile data to be fetched for a new account.

Image

## Steps to reproduce

Create new account (password)
Check notification centre

### Additional Information

- Status desktop version: StatusIm-Desktop-2.33.0-rc.1-37-gbea44dae1-dirty-bea44d-aarch64
- Operating System: Mac

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/17555

We were adding the Notification of the back ups by accident when creating a normal account (not restored), because I added the code to create the notification in the `RequestAllHistoricMessages` function as well, even though the Messenger already does it. So for normal restores, it probably tried to add it twice, though they have the same ID, so it wasn't noticed

### CODE REVIEW

File: protocol/messenger_backup_handler.go [hunk 1]
```diff
@@ -127,6 +127,10 @@ func (m *Messenger) handleBackup(state *ReceivedMessageState, message *protobuf.
 }
 
 func (m *Messenger) updateBackupFetchProgress(message *protobuf.Backup, response *wakusync.WakuBackedUpDataResponse, state *ReceivedMessageState) error {
+	if m.backedUpFetchingStatus == nil {
+		return nil
+	}
```
Comment (jrainville) [inline protocol/messenger_backup_handler.go:132]: Im not sure this is needed. I don't think we had any crashes, but I just realized that on normal app runs (way after the actual restore), this code could still run and it's better to guard against any crashes.

File: protocol/messenger_mailserver.go [hunk 2]
```diff
@@ -324,11 +324,6 @@ func (m *Messenger) RequestAllHistoricMessages(forceFetchingBackup, withRetries
 
 	allResponses := &MessengerResponse{}
 	if forceFetchingBackup || !backupFetched {
```
Comment (jrainville) [inline protocol/messenger_mailserver.go:322]: I wonder if we should add the `if m.processBackedupMessages` here too. What happens here is that even though we are not restoring the account, we end up doing a full backup fetch anyway for no reason?

I did not touch it right now just in case it would cause a regression, but I don't see the point of doing a full (30 days) fetch of backups if we created an account from scratch. Let me know if I'm missing something. The person that added that code was Andrea 4 years ago :sweat_smile: 

Also, if `processBackedupMessages` is `false`, we don,t even handle the backups:
```go
func (m *Messenger) HandleBackup(state *ReceivedMessageState, message *protobuf.Backup, statusMessage *v1protocol.StatusMessage) error {
	if !m.processBackedupMessages {
		return nil
	}
```

cc @status-im/status-go-guild

**Comment by jrainville** [comment]
@igor-sirotin @osmaczko @seanstrom friendly reminder to review

File: protocol/messenger_mailserver.go (hunk 2 above)
Comment (osmaczko) [reply protocol/messenger_mailserver.go:322]: I don't think it makes much sense to fetch backups for newly created accounts. Adding this condition seems reasonable to me and definitely better than removing backup fetching tracking.

**Review by osmaczko — COMMENTED** [review]
I would go with `m.processBackedupMessages`.

File: protocol/messenger_mailserver.go (hunk 2 above)
Comment (igor-sirotin) [reply protocol/messenger_mailserver.go:322]: I think you're right, the messages will be skipped in `HandleBackup`. But to me the issue is actually `HandleBackup`, not here. 

If I would call `RequestAllHistoricMessages` with `forceFetchingBackup = true`, I'd expect backup to be fetched and the messages to be processed.

I'd keep as is for now, we should carefully refactor the way backup is handled.

**Review by igor-sirotin — APPROVED** [review]

File: protocol/messenger_mailserver.go (hunk 2 above)
Comment (igor-sirotin) [reply protocol/messenger_mailserver.go:322]: So I think:

1. either the condition should be `forceFetchingBackup || (!backupFetched && m.processBackedupMessages`
both here and in `HandleBackup` (which will bring some weird dependencies between those functions)

2. or we remove `forceFetchingBackup` option completely
I think it's only called from desktop in [`asyncFetchWakuBackupMessagesTask`](https://github.com/status-im/status-desktop/blob/e0590e5c64ab1477de53196a6330323616e774eb/src/app_service/service/general/async_tasks.nim#L8). Which I think is bound to the explicit button in settings and is only used (if used) for testing.

I'd prefer (2), as it would remove the code, not add it 😄 

cc @osmaczko @jrainville

Comment (jrainville) [reply protocol/messenger_mailserver.go:322]: > I think it's only called from desktop in [asyncFetchWakuBackupMessagesTask](https://github.com/status-im/status-desktop/blob/e0590e5c64ab1477de53196a6330323616e774eb/src/app_service/service/general/async_tasks.nim#L8). Which I think is bound to the explicit button in settings and is only used (if used) for testing.

It is indeed only used in Desktop, in the `backupSyncingComponent` in the ActivityCenterPopup of all places.

I'll dig some more to understand why we added this force fetch, but I'm very tempted to just remove it as you proposed

Comment (jrainville) [reply protocol/messenger_mailserver.go:322]: ## Source of the code

Ok I found it. It's used to force the re-fecth of everything in the onboarding.

So when re-importing from the seed phrase, we fetch everything. In the old onboarding, we waited on the page until everything was fetched, now we do it in the background.
In both cases, the user can click `Retry` if something didn't get fetched.

It at least confirms that it's only used in the case were were are re-importing an old account, ie `processBackedupMessages` is gonna be set to true.

### Remaining problem

However, I just realized that removing the `forceFetchingBackup` param won't help us in this case, because `RequestAllHistoricMessages` gets called during the normal flow of the app too (like going back from sleep).

So at somepoint, we'll end up doing the full history fetch anyway.

## Possible solutions

I guess we have two options:
a. we could set `BackupFetched` to `true` for accounts created from scratch
b. just add the `processBackedupMessages` like in @igor-sirotin 's option 1.

I think option b is the simpler one, but it does feel weird that `BackupFetched` will stay `false` for the whole life of that account.
We could also rename it to `fetchAndProcessBackedupMessages` so that it's clearer that it's not just about not parsing them, because it's weird to think that we might want to fetch backups but never process them (useless request and computation)

cc @igor-sirotin @osmaczko

Comment (igor-sirotin) [reply protocol/messenger_mailserver.go:322]: Hmm, setting `BackupFetched` to `true` for new accounts sounds good to me for now. 
@osmaczko wdyt?

Comment (osmaczko) [reply protocol/messenger_mailserver.go:322]: > Hmm, setting `BackupFetched` to `true` for new accounts sounds good to me for now. @osmaczko wdyt?

Not ideal, because it is untrue, the backup will never be fetched for new accounts.. but it is good enough for now indeed.

Comment (jrainville) [reply protocol/messenger_mailserver.go:322]: I updated the code to do as you guys proposed. I put it in the same commit by accident, but it's still pretty small so it shouldn't be an issue

**Review by osmaczko — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]
