### PR TITLE
fix_: block on logout

### LINKED ISSUE #15939: The app doesn't die when closing with the X (or right click - close on Mac)
# Bug Report

## Description

If you close the app with the X button (and most likely with any other means other than CTRL-C), it doesn't die (stays "logging out...")

## Steps to reproduce

1. Open the app in a console
2. Login
3. Make the computer go to sleep
4. Come back from sleep
5. Close the app with the X
6. See the console

#### Expected behavior

The app dies in less than 5 seconds

#### Actual behavior

The app doesn't die even after 2 minutes

### Additional Information

- Status desktop version: 2.30 RC3
- Operating System: Ubuntu 22

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-desktop/issues/15939

1. Check `ctx.Done()` on writing to channel in `processAndPushTelemetry`
2. Added `wg.Done()` in waku.Start under `EnableMissingMessageVerification` condition.
3. Refactored `wg` management in waku for less bugs possibility

### CODE REVIEW

File: telemetry/client.go [hunk 1]
```diff
@@ -243,7 +245,12 @@ func (c *Client) processAndPushTelemetry(data interface{}) {
 		return
 	}
 
-	c.telemetryCh <- telemetryRequest
+	select {
+	case <-c.ctx.Done():
+		return
+	case c.telemetryCh <- telemetryRequest:
```
Comment (igor-sirotin) [inline telemetry/client.go:248]: Fix number 1

File: wakuv2/waku.go [hunk 2]
```diff
@@ -1152,7 +1155,9 @@ func (w *Waku) Start() error {
 
 		w.missingMsgVerifier.Start(w.ctx)
 
+		w.wg.Add(1)
 		go func() {
+			w.wg.Done()
```
Comment (igor-sirotin) [inline wakuv2/waku.go:1160]: Fix number 2

File: wakuv2/waku.go [hunk 3]
```diff
@@ -1275,16 +1279,27 @@ func (w *Waku) Stop() error {
 
 	w.node.Stop()
 
+	time.Sleep(2 * time.Second)
+	w.logger.Info("<<< push to telemetry client")
+
+	if w.statusTelemetryClient != nil {
+		w.statusTelemetryClient.PushPeerCount(w.PeerCount())
+	}
+
```
Comment (richard-ramos) [inline wakuv2/waku.go:1288]:
```suggestion
```

File: telemetry/client.go [hunk 4]
```diff
@@ -93,6 +93,7 @@ type PeerConnFailure struct {
 }
 
 type Client struct {
+	ctx                  context.Context
```
Comment (richard-ramos) [inline telemetry/client.go]: storing context in a struct is discouraged because it hides the flow of context propagation, making the code harder to understand and maintain. 
context are meant to be passed explicitly, reflecting their ephemeral and request-scoped nature. (This is described in https://pkg.go.dev/context)

I'd say that instead of having the context being part of the struct, the `processAndPushTelemetry` should receive a context parameter and use that for the request. That means that `PushReceivedMessages`, `PushSentEnvelope`, `PushSentEnvelope`,  `PushErrorSendingEnvelope`,  `PushPeerCount` and `PushPeerConnFailures` should be modified to receive a context as well

**Review by richard-ramos — APPROVED** [review]
LGTM. But left some comments regarding the usage of context for your consideration

File: wakuv2/waku.go [hunk 5]
```diff
@@ -1275,16 +1279,27 @@ func (w *Waku) Stop() error {
 
 	w.node.Stop()
 
+	time.Sleep(2 * time.Second)
+	w.logger.Info("<<< push to telemetry client")
+
+	if w.statusTelemetryClient != nil {
+		w.statusTelemetryClient.PushPeerCount(w.PeerCount())
```
Comment (richard-ramos) [inline wakuv2/waku.go]: This is not needed, right?

File: wakuv2/waku.go [hunk 6]
```diff
@@ -1275,16 +1279,27 @@ func (w *Waku) Stop() error {
...
+	}
+
 	if w.protectedTopicStore != nil {
 		err := w.protectedTopicStore.Close()
 		if err != nil {
 			return err
 		}
 	}
 
+	w.logger.Info("<<< wait for wait group")
```
Comment (richard-ramos) [inline wakuv2/waku.go]: And maybe this should be removed as well, (and also line 1301)

File: wakuv2/waku.go (hunk 5 above)
Comment (jrainville) [reply wakuv2/waku.go]: Yeah this is leftover from the way we had to trigger the freeze

**Comment by jrainville** [comment]
@igor-sirotin I added a commit with the fix to the pendingTracker. It was also never stopped. I think it ended up not being a real issue, but it's better to close it still

File: wakuv2/waku.go (hunk 5 above)
Comment (igor-sirotin) [reply wakuv2/waku.go]: oops

File: telemetry/client.go (hunk 4 above)
Comment (igor-sirotin) [reply telemetry/client.go]: Wow, never saw this rule. TIL, thank you! ❤️ 

I'll do this for sure. 
Though there's we'll still pass `Messenger.ctx` everywhere 😄

File: wakuv2/waku.go (hunk 5 above)
Comment (igor-sirotin) [reply wakuv2/waku.go]: 452fb5e078dec81bdaf2460eb292b92f3bde956c

File: wakuv2/waku.go (hunk 6 above)
Comment (igor-sirotin) [reply wakuv2/waku.go]: 452fb5e078dec81bdaf2460eb292b92f3bde956c

File: telemetry/client.go (hunk 4 above)
Comment (igor-sirotin) [reply telemetry/client.go]: @richard-ramos ca40216ed6d811e767ad345ae99b5fcffc9b5e74

**Review by jrainville — APPROVED** [review]

File: telemetry/client.go (hunk 4 above)
Comment (richard-ramos) [reply telemetry/client.go]: :rocket:
