### PR TITLE
fix(news)_: make sure we do not fetch old news when the user re-enables

### LINKED ISSUE #17926: News published while polling disabled retrieved later
# Bug Report

## Description

It's expected that news published while news notifications or rss are disabled will not be delivered. Currently news published since notifications were previously enabled get displayed when either news notifications or rss is re-enabled.

## Steps to reproduce

- Disabled news
- Publish news
- Enable news
- Notifications for the post are displayed

#### Expected behavior

Only news published since news most recently enabled.

#### Actual behavior

News published while notifications disabled get displayed 

### Additional Information

- Status desktop version: StatusIm-Desktop-250509-152322-7222ee-pr17830-aarch64
- Operating System: Mac

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/17926

Fixes the issue by reseting the the `fetchFrom` time to the current time when the user re-enables the setting. That way, the news posted in between the time it was disabled and then re-enabled will be ignored.

### CODE REVIEW

**Review by osmaczko — APPROVED** [review]

File: internal/newsfeed/news_feed_manager.go [hunk 1]
```diff
@@ -100,7 +100,7 @@ func (n *NewsFeedManager) FetchRSS() ([]*gofeed.Item, error) {
 
 	if len(filteredItems) > 0 {
 		// Update fetchFrom to now since we have new items
-		n.fetchFrom = time.Now()
+		n.SetFetchFrom(time.Now())
```
Comment (igor-sirotin) [inline internal/newsfeed/news_feed_manager.go]: Hmm, just noted this. We should probably use `time.Now().UTC()`

File: protocol/messenger_news_feed.go [hunk 2]
```diff
@@ -122,6 +122,13 @@ func (m *Messenger) changeNewsFeedManagerAfterUpdate() error {
 	}
 
 	if isNewsFeedEnabled {
+		// Reset the fetchFrom time to now since we don't want to fetch items that were posted while the feed was disabled
+		m.newsFeedManager.SetFetchFrom(time.Now())
+		err = m.settings.SaveSetting(settings.NewsFeedLastFetchedTimestamp.GetReactName(), time.Now())
```
Comment (igor-sirotin) [inline protocol/messenger_news_feed.go]: Extract `time.Now().UTC()` to a variable to ensure it's exactly the same value?

**Review by igor-sirotin — APPROVED** [review]
