### PR TITLE
Bug: Fix view&post token-permitted channel input not locked

### LINKED ISSUE #14117: Community: View&Post token-permitted channel input is not locked when requirements do not match
### Description

1. create community
2. create a permission saying "Keep 0.1 ETH to view and post in general channel"
3. for community member, create 2 addresses. One address should match the requirements, second address should not
4. invite member to community
5. as the member, share the address that do not match the requirements and confirm

As result, member is somewhat joined the community, is able to see a channel and the channel input is not locked. However, posting to the channel do not send the messages (they are not delivered)

https://github.com/status-im/status-desktop/assets/82375995/d8af264c-f9d3-4a4c-954b-97343e20c447

### PR DESCRIPTION
**Pull request by kounkou**
### Description

In previous version of status-go, we failed to compute the permission for communities with token permitted channels. This caused the UI to display the wrong UI when displaying the channel UI. Indeed, the user was enable to view the channel and couldn't send messages.
In this PR, we are now able to lock consistently the channel if we do not have permission to view&post. This PR fixes [#14117](https://github.com/status-im/status-desktop/issues/14117)
The change consists in adding a retrieval of the Revealed accounts for cases when the addresses are not shared, and where the purpose isn't to have all accounts considered for the calculation of permissions on channel.

### Testing

Multiple tests already cover the functions `CheckAllChannelsPermissions` and `CheckChannelPermissions`, making sure all tests are passed. If any strong opinion on the testing side, I can allocate a bit more time.

- community_test.go
- manager_test.go

I have also checked the flows : 

-[x] Restore write when channel is unlocked
-[x] Set the channel permissions at boot
-[x] Detect changes when user
   -[x] edit permissions
   -[x] create permissions
   -[x] delete permissions

### Demo

[Screencast from 2024-04-08 12:18:14 AM.webm](https://github.com/status-im/status-go/assets/2589171/100bbd52-d622-49d4-b87f-9bd0c713dc77)

### CODE REVIEW

File: protocol/messenger_communities.go [hunk 1]
```diff
@@ -4067,28 +4067,51 @@ func (m *Messenger) CheckPermissionsToJoinCommunity(request *requests.CheckPermi
 	return m.communitiesManager.CheckPermissionToJoin(request.CommunityID, addresses)
 }
 
-func (m *Messenger) CheckCommunityChannelPermissions(request *requests.CheckCommunityChannelPermissions) (*communities.CheckChannelPermissionsResponse, error) {
-	if err := request.Validate(); err != nil {
-		return nil, err
-	}
+func (m *Messenger) checkCommunityPermissions(communityID string, sharedAddresses []*protobuf.RevealedAccount, requestAddresses []string) ([]gethcommon.Address, error) {
```
Comment (jrainville) [inline protocol/messenger_communities.go]: I think this function name doesn't really make sense. We're not really checking anything here, just getting the right addresses right?

File: protocol/messenger_communities.go [hunk 2]
```diff
@@ -4097,21 +4120,14 @@ func (m *Messenger) CheckAllCommunityChannelsPermissions(request *requests.Check
...
 	}
 
-	var addresses []gethcommon.Address
-
-	if len(request.Addresses) == 0 {
-		accounts, err := m.settings.GetActiveAccounts()
-		if err != nil {
-			return nil, err
-		}
+	sharedAddresses, err := m.GetRevealedAccounts(request.CommunityID, common.PubkeyToHex(&m.identity.PublicKey))
```
Comment (jrainville) [inline protocol/messenger_communities.go]: Both function do the `GetRevealedAccounts` call, so it can be moved to the `checkCommunityPermissions` function (or whatever new name)

**Review by jrainville — COMMENTED** [review]
Does the Edit shared addresses flow still work with this?
Let's say you had all accounts selected at first, go in the edit popup and unselect the address with ETH, does the popup show correctly that we do not have ETH?

**Comment by kounkou** [comment]
> Does the Edit shared addresses flow still work with this? Let's say you had all accounts selected at first, go in the edit popup and unselect the address with ETH, does the popup show correctly that we do not have ETH?

Yes, here is a video recording

[Screencast from 2024-04-08 07:59:35 AM.webm](https://github.com/status-im/status-go/assets/2589171/653829c1-f6b5-4adb-a9dd-75a6e88a402a)

File: protocol/messenger_communities.go (hunk 2 above)
Comment (kounkou) [reply protocol/messenger_communities.go]: Looking into it.

File: protocol/messenger_communities.go (hunk 1 above)
Comment (kounkou) [reply protocol/messenger_communities.go]: oh yeah, I forgot renaming it. Thanks.

**Comment by jrainville** [comment]
> Yes, here is a video recording

In the video, we can see that it didn't work as intended. The Account with 0.15 ETH was unselected, and still, all the channel were marked a `Can Post`. 
What should have happened is that when unselecting the account, the permissioned channels should have been marked as `Can't post` in the popup.

**Comment by kounkou** [comment]
> > Yes, here is a video recording
> 
> In the video, we can see that it didn't work as intended. The Account with 0.15 ETH was unselected, and still, all the channel were marked a `Can Post`. What should have happened is that when unselecting the account, the permissioned channels should have been marked as `Can't post` in the popup.

Oh right, I misread your sentence. I think while preparing the code for testing I inadvertently changed something, let me double check. This flow should already work.
Here it is...

[Screencast from 2024-04-08 02:28:18 PM.webm](https://github.com/status-im/status-go/assets/2589171/d0510e07-51e0-4501-8673-e603334948cc)

**Review by jrainville — APPROVED** [review]
Ok, seeing the new video, the behaviour seems correct now. The fact that the chat content in the background updates at the same time is known and will be addressed in another issue

File: protocol/messenger_communities.go [hunk 3]
```diff
@@ -4067,51 +4067,64 @@ func (m *Messenger) CheckPermissionsToJoinCommunity(request *requests.CheckPermi
 	return m.communitiesManager.CheckPermissionToJoin(request.CommunityID, addresses)
 }
 
-func (m *Messenger) CheckCommunityChannelPermissions(request *requests.CheckCommunityChannelPermissions) (*communities.CheckChannelPermissionsResponse, error) {
-	if err := request.Validate(); err != nil {
-		return nil, err
+func (m *Messenger) getSharedAddresses(communityID types.HexBytes, requestAddresses []string) ([]gethcommon.Address, error) {
```
Comment (MishkaRogachev) [inline protocol/messenger_communities.go:4070]: Does these changes requires test?

**Review by MishkaRogachev — APPROVED** [review]

File: protocol/messenger_communities.go (hunk 3 above)
Comment (kounkou) [reply protocol/messenger_communities.go:4070]: Added test
