### PR TITLE
fix(metrics)_: cleanup old metrics so that new ones can be processed

### LINKED ISSUE #6860: Wrong metrics get retried infinitely, making it impossible to send new metrics.
Found by @caybro 

If you try to send a malformed metric or it just fails for some random reason, then only log again 5 days later, it will get those metrics again from the DB and they will fail again, but this time with a timestamp error.

```
2025-08-19T12:53:58.007Z        INFO    GethStatusBackend.MetricService centralizedmetrics/metrics.go:123       processing metrics
2025-08-19T12:53:58.007Z        INFO    GethStatusBackend.MetricService centralizedmetrics/metrics.go:129       polled metrics
2025-08-19T12:53:58.007Z        INFO    GethStatusBackend.MetricService centralizedmetrics/metrics.go:134       processing metrics
2025-08-19T12:53:58.008Z        INFO    GethStatusBackend       providers/mixpanel.go:77        sending metrics to      {"url": "https://api.mixpanel.com/track?project_id=3350627&strict=1", "metric": [{"event":"navigation","properties":{"$insert_id":"19606e07-dd7a-40e4-9eba-15022bc4
311a","app_version":"v2.34.0-dev-541-ge907f0b62","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","platform":"linux","time":1750933477217,"token":"5c73bda2d36a9f688a5ee45641fb6775","viewId":"Messages"}},{"event":"navigation","properties":{"$insert_id":"4bc84c77-7df9-404d-b280-dc
bdf899b1ea","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","platform":"linux","time":1751470521576,"token":"5c73bda2d36a9f688a5ee45641fb6775","viewId":"DidYouKnowSplashScreen"}},{"event":"user-logged-in","properties":{"$insert_id":"bf
dd0ac9-0556-4b8c-8407-8d463ea26589","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","flowType":"Password","platform":"linux","time":1751470523027,"token":"5c73bda2d36a9f688a5ee45641fb6775"}},{"event":"navigation","properties":{"$insert
_id":"8aed5924-b3f3-4f7a-89c6-9bb590a800fd","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","platform":"linux","time":1751470523034,"token":"5c73bda2d36a9f688a5ee45641fb6775","viewId":"shell"}},{"event":"dapps-health","properties":{"$i
nsert_id":"920c6d69-fc68-430b-98a0-087f66b8bcbc","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","error":"","platform":"linux","state":"chains-down","time":1751470524394,"token":"5c73bda2d36a9f688a5ee45641fb6775"}},{"event":"dapps-heal
th","properties":{"$insert_id":"7b97ef2b-914b-4dc0-8cc5-1cdcb88bb479","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","error":"","platform":"linux","state":"network-down","time":1751470524394,"token":"5c73bda2d36a9f688a5ee45641fb6775"}
},{"event":"dapps-health","properties":{"$insert_id":"89a5596d-9aa5-4bea-98b3-f8dfc61192fe","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","error":"","platform":"linux","state":"wc-available","time":1751470525841,"token":"5c73bda2d36a
9f688a5ee45641fb6775"}},{"event":"navigation","properties":{"$insert_id":"2a66e7cc-3ece-4695-bbf7-4943a8057915","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","platform":"linux","time":1751470529943,"token":"5c73bda2d36a9f688a5ee45641
fb6775","viewId":"profileSettings"}},{"event":"navigation","properties":{"$insert_id":"2c9ed167-d747-41d6-9a35-f4a9fa1b57a0","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","platform":"linux","time":1751470532491,"token":"5c73bda2d36a9
f688a5ee45641fb6775","viewId":"shell"}},{"event":"dapps-health","properties":{"$insert_id":"8afad9a3-731e-4e48-927c-470c8b6ce276","app_version":"v2.34.0-dev-554-gb04868a1a","distinct_id":"45c4a8ea-04f7-40e8-94ca-eba4b4a7521a","error":"","platform":"linux","state":"network-down","tim
e":1751470614783,"token":"5c73bda2d36a9f688a5ee45641fb6775"}}], "secret": "EDITED_OUT"}
```

gives:
```
failed to send metric<->{"status-code": 400, "body": "{\"error\":\"time, 54.2 days in the past (max 5.0)\"}
```

As you can see, it now fails with the time being too far away.

So those events will **never** be sent, meaning they will **never** be deleted from the DB and they will be retried to infinity.

We need to add a check before sending the event to see if the date is greater than X days, then we just delete these events as they are not useful.
We can just do a "cleanUp" function in the persistence module that removes old events before doing the polling.

We could use 5 days, but in case Mixpanel changes their API, I think day old events are safe to delete as well.

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #6860

The solution is to cleanup metrics older than two days at the start of the metrics module. That way, we start pilling, we only process valid metrics

I decided to put the clean up on Start and not in the process function, because I don't think it's worth cleaning every 10 seconds.
I think the only time it would bite us if if someone has an internet issue, so the metric event fails to send, puts their computer in sleep mode without closing the app, then comes back 5 days later. Then the events would get stuck.

However, the next time they restart, it will still go back to working as expected, so it should be fine.

### CODE REVIEW

**Comment by jrainville** [comment]
I tested with Desktop too and the cleanup does work (no error) and events get sent as expected

**Review by igor-sirotin — APPROVED** [review]

File: centralizedmetrics/sqlite_persistence.go [hunk 1]
```diff
@@ -98,6 +98,26 @@ func (r *SQLiteMetricRepository) Delete(metrics []common.Metric) error {
...
+			err = tx.Commit()
+			return
+		}
+		// don't shadow original error
+		_ = tx.Rollback()
+	}()
+
+	const cleanupThreshold = 5 * 24 * time.Hour // 5 days is the MixPanel limit
+
+	_, err = tx.Exec("DELETE FROM centralizedmetrics_metrics WHERE timestamp < ?", time.Now().Add(-cleanupThreshold).UnixNano()/int64(time.Millisecond))
```
Comment (dlipicar) [inline centralizedmetrics/sqlite_persistence.go:117]: I'll blindly trust your time units

**Review by dlipicar — APPROVED** [review]

File: centralizedmetrics/sqlite_persistence.go [hunk 2]
```diff
@@ -98,6 +98,26 @@ func (r *SQLiteMetricRepository) Delete(metrics []common.Metric) error {
...
 }
 
+func (r *SQLiteMetricRepository) CleanupOldMetrics() error {
+	tx, err := r.db.BeginTx(context.Background(), &sql.TxOptions{})
+	if err != nil {
+		return err
+	}
+	defer func() {
+		if err == nil {
+			err = tx.Commit()
```
Comment (saledjenic) [inline centralizedmetrics/sqlite_persistence.go:108]: This error is never returned, so either update the line below to `return err` or just name the result parameter `func (r *SQLiteMetricRepository) CleanupOldMetrics() (err error) {`.

**Review by saledjenic — APPROVED** [review]

File: centralizedmetrics/sqlite_persistence.go (hunk 2 above)
Comment (jrainville) [reply centralizedmetrics/sqlite_persistence.go:108]: This is how all the code in persistence files in status-go are. So they are either all broken or there is some magic happening that I don't know about :smile:

**Comment by jrainville** [comment]
I cherry-picked the commit to remove schema validation, because RPC tests were failing on a schema difference

**Comment by jrainville** [comment]
Ok, it broke more things then helped. I'll remove it and just fix the schema lol

**Comment by jrainville** [comment]
Merging as the builds have been renamed and they passed under the new name
